[18.06] https-dns-proxy: update binary to 2020-08-21
openwrt/packages pull request #13514
Opened 2020-09-28 20:16 UTC by stangri

Maintainer: me
Compile tested: mvebu, WRT3200ACM, 18.06.8/19.07.4
Run tested: mvebu, WRT3200ACM, 18.06.8, start/stop, query DoH servers

Description: this updates to the latest release binary and contains cosmetic fixes to README and init script.

PS. I'm also requesting merge rights to packages.

Signed-off-by: Stan Grishin <stangri@melmac.net>

2020-09-29 07:08 UTC, BKPepe commented
Is this a security fix or why this is submitted against 18.06 branch?

2020-09-29 15:37 UTC, stangri commented
There's a pesky issue of 100% CPU spikes on some systems and there's a hope this new binary will fix it.

2020-10-16 15:18 UTC, BKPepe requested changes

2020-10-16 15:18 UTC, BKPepe commented on net/https-dns-proxy/files/README.md
> +# README
This is no go for me. Sorry! This is almost breaking change in OpenWrt 18.06.

2020-10-16 15:18 UTC, BKPepe commented on net/https-dns-proxy/test.sh
> +/etc/init.d/"$1" version 2>&1 | grep "$2"
Why? Test.sh is not used in OpenWrt 18.06 branch.

2020-10-31 01:18 UTC, stangri reviewed
To maintain same code across branches. This has already been accepted for the other packages I maintain.

2020-12-10 09:33 UTC, merged