cgroupfs-mount: fix symbolic link name
openwrt/packages pull request #13827
Opened 2020-11-02 07:25 UTC by cobaltchang

Fix the symbolic link name to /etc/rc.d/S01cgroupfs-mount.

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:
The created symbolic link S1cgroupfs-mount will be executed between S19 and S20.
Fix the START setting to ensure that cgroupfs-mount is executed at S01.

2020-11-09 04:53 UTC, neheb commented
ping @G-M0N3Y-2503

2020-11-09 12:20 UTC, G-M0N3Y-2503 requested changes
LGTM, just need to increment the [`PKG_RELEASE`](https://github.com/openwrt/packages/blob/master/utils/cgroupfs-mount/Makefile#L4) I believe.

Also, I'm curious as to what issues you had before this change?

2020-11-09 12:33 UTC, feckert commented
@G-M0N3Y-2503 

> Also, I'm curious as to what issues you had before this change?

as mentioned by @cobaltchang:
The created symbolic link S1cgroupfs-mount will be executed after S10fstab.
Fix the START setting to ensure that cgroupfs-mount is executed at S01.

This i also done in https://github.com/openwrt/packages/blob/master/net/sshtunnel/files/sshtunnel.init#L8

2020-11-09 13:09 UTC, cobaltchang commented
@G-M0N3Y-2503 
Thank you very much, I updated PKG_RELEASE and force-pushed.

2020-11-09 13:28 UTC, merged

2020-11-09 13:28 UTC, feckert commented
Thanks

2020-11-10 07:51 UTC, G-M0N3Y-2503 commented
> as mentioned by @cobaltchang:
> The created symbolic link S1cgroupfs-mount will be executed after S10fstab.
> Fix the START setting to ensure that cgroupfs-mount is executed at S01.

Oh, I wasn't disputing whether it was wrong before, I was just wondering if anything was broken.  
I couldn't find a `S10fstab`, just a [`S40fstab`](https://github.com/openwrt/openwrt/blob/master/package/system/fstools/files/fstab.init#L4) so I couldn't reproduce it myself.
Also, I thought the only thing that had cgroup v1 mounts in it was `procd`?