ocserv：libseccomp doesn't build
openwrt/packages pull request #15377
Opened 2021-04-09 13:51 UTC by zxlhhyccc

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2021-04-09 14:29 UTC, feckert commented
Can you please fill the template.
And while you are at it, can you first wrap the line so that it is not so long and then add your change?

2021-04-10 01:14 UTC, neheb commented
@ping yousong

2021-04-10 01:15 UTC, neheb commented
ping @cotequeiroz I think you've dealt with libseccomp circular dependencies before.

2021-04-10 02:01 UTC, cotequeiroz requested changes
I see this is your first contribution.  Welcome.

You still need to add a proper signed commit message.  Something like:
```
ocserv: don't build with libseccomp on ARC

libseccomp can't be built on ARC, so we must disable the option here as well.

Signed-off-by: Your Actual Name <zxlhhy@gmail.com>
```

You should use your own words, but feel free to take mine this time. 😉

2021-04-10 02:05 UTC, cotequeiroz commented
> ping @cotequeiroz I think you've dealt with libseccomp circular dependencies before.

Does it have a circular dependency in current master or only with the proposed change applied?  I'm not seeing it here in master, but I haven't tested with this PR.

2021-04-10 02:07 UTC, neheb commented
Current master. Fresh make menuconfig:

```
tmp/.config-package.in:127118:error: recursive dependency detected!
tmp/.config-package.in:127118:  symbol PACKAGE_strongswan is selected by PACKAGE_strongswan-libnttfft
tmp/.config-package.in:127365:  symbol PACKAGE_strongswan-libnttfft is selected by PACKAGE_strongswan-full
tmp/.config-package.in:127217:  symbol PACKAGE_strongswan-full depends on PACKAGE_strongswan
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

feeds/packages/net/ocserv/Config.in:10:error: recursive dependency detected!
feeds/packages/net/ocserv/Config.in:10: symbol OCSERV_SECCOMP depends on PACKAGE_ocserv
tmp/.config-package.in:126792:  symbol PACKAGE_ocserv depends on OCSERV_SECCOMP
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"



*** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.
```

2021-04-10 03:18 UTC, cotequeiroz commented
#15382 should take care of strongswan.  Also, some packages are selecting the libseccomp without checking for `!arc` first.  I have spotted one place in luci, but I'm shutting down the shop now.  I'll look at it tomorrow.

2021-04-12 00:58 UTC, cotequeiroz commented
Once this is fixed & merged, #15400 should finish up the fixes in the packages feed.  The order of the merges does not matter.
There's openwrt/luci#4983 handling a possible lxc circular dependency as well.

2021-04-12 08:26 UTC, hnyman commented on net/ocserv/Makefile
> +  DEPENDS:= +OCSERV_RADIUS:libradcli +OCSERV_HTTP_PARSER:libhttp-parser +(!arc&&OCSERV_SECCOMP):libseccomp +libgnutls +certtool +libncurses +libreadline +OCSERV_PAM:libpam +OCSERV_PROTOBUF:libprotobu
+1 for this solution proposal from @cotequeiroz 
It looks much nicer and more correct than the dependency change originally proposed in this PR

2021-04-12 17:10 UTC, cotequeiroz commented
The build system appears to not show a recursive dependency now.  Nonetheless, this still needs to be fixed.  @zxlhhyccc, do you want to take care of this, or should I?

2021-04-13 11:14 UTC, hnyman commented
> or should I?

Please do.
you will get formal commit syntax right.

2021-04-15 01:53 UTC, closed without merging