miniupnpd: add force_forwarding option support
openwrt/packages pull request #16011
Opened 2021-07-02 11:31 UTC by ptpt52

This option replace the 'ext_ip_reserved_ignore', and replace the
patch with new one

as addr_is_reserved() behavior should not be changed, so drop the
ext_ip_reserved_ignore

use a force_forwarding option to make the port forwarding force to
work when the router is behind NAT

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2021-07-02 11:32 UTC, ptpt52 commented
need some tested

2021-07-02 11:34 UTC, ptpt52 commented
https://github.com/openwrt/packages/issues/15258
may related

2021-07-02 12:38 UTC, BKPepe requested changes
Even though I appreciate your work, I am not in favor to merge this because what happened here: https://github.com/openwrt/packages/issues/15258

We can not carry patches, which are refused to be part of upstream and are causing several issues, and then they are reported upstream, which they need to solve and refuse it as they are right about it.

If you want to have this merged, send this upstream, cooperate with them to be sure that it is accepted, and once it is merged, it can be backported here or you can wait until it's part of a new release.

For now, I am closing this to prevent the situation, which happened in the past. You should really remove the patch which you created. Because this is not an acceptable state. Users are confused about what to do with the error message, which is cryptic and does not say many details what to do.

2021-07-02 12:38 UTC, BKPepe commented
Even though, I appreciate your work, I am not in favor to merge this because what happened here: https://github.com/openwrt/packages/issues/15258

We can not carry patches, which are refused to be part of upstream and they are causing several issues and then they are reported to upstream, which they needs to solve.

If you want to have this merged, send this upstream, cooperate with them to be sure that it is accepted and once it is merged, it can be backported here or you can wait until its part of a new release.

2021-07-02 12:38 UTC, closed without merging

2021-09-15 23:31 UTC, Neustradamus commented
@openips: What do you think about this PR from @ptpt52?
It replaces "301-ext_ip_reserved_ignore.patch"...

2021-09-15 23:52 UTC, openips commented
@Neustradamus I test this pr in openwrt package and find not work， i can report bug here，thks a lot

2021-09-15 23:54 UTC, openips commented
@ptpt52 大神 最新的补丁有问题  force_forwarding失效 具体描述请看 [16480](https://github.com/openwrt/packages/issues/16480) 有时间修复一下 需要提供测试请联系我 谢谢

2021-09-16 00:42 UTC, ptpt52 commented
@openips  try to enable stun
```
upnpd.config.use_stun='1'
upnpd.config.stun_host='iphone-stun.strato-iphone.de'
upnpd.config.stun_port='3478'
```

2021-09-16 00:45 UTC, ptpt52 commented
specify the wan interface:
```
upnpd.config.external_iface='wan or what'
```

2021-09-16 00:59 UTC, openips commented
@ptpt52 我还是习惯您之前的301补丁的工作方式 非常省心 能否修改一下

2021-09-16 03:04 UTC, ptpt52 commented
try this one: https://github.com/x-wrt/packages/commit/62b923a284d899d02895af9006f5bd991246e89c
@openips

2021-09-16 03:07 UTC, openips commented
好的 我编译一下试试看 结果稍后反馈

2021-09-16 07:58 UTC, openips commented
![image](https://user-images.githubusercontent.com/47168453/133573359-bafe3089-3eef-4e83-8d6c-84124349c374.png)
![image](https://user-images.githubusercontent.com/47168453/133573394-96403270-eb5a-41bf-ac30-ee3cfe8c158c.png)
@ptpt52 @Neustradamus x-wrt/packages@62b923a worked very well ，thks a lot

2021-09-16 09:31 UTC, Neustradamus commented
@openips: Nice!

Thanks @ptpt52 :)
Can you create a new PR?

2021-09-16 18:20 UTC, stangri commented on net/miniupnpd/files/upnpd.config
> +	option force_forwarding 1
Please don't make this option default. Previously when you made `ext_ip_reserved_ignore` default, it resulted in cryptic syslog messages for miniupnpd users outside of China.

2021-09-16 20:36 UTC, Neustradamus commented
@ptpt52: Important: Please do new PRs for 19.07.x/21.02.x/master branches.
- https://github.com/openwrt/packages/commits/master/net/miniupnpd
- https://github.com/openwrt/packages/commits/openwrt-21.02/net/miniupnpd
- https://github.com/openwrt/packages/commits/openwrt-19.07/net/miniupnpd

Thanks a lot in advance.

PS: @neheb: Too late to have same miniupnp version in 18.06.x?

2021-09-16 20:38 UTC, champtar commented
Please do a PR for master only first, then we will backport once reviewed ;)

2021-09-16 20:39 UTC, Neustradamus commented
@ptpt52: Important: Please do new PRs for 19.07.x/21.02.x/master branches.
- https://github.com/openwrt/packages/commits/master/net/miniupnpd
- https://github.com/openwrt/packages/commits/openwrt-21.02/net/miniupnpd
- https://github.com/openwrt/packages/commits/openwrt-19.07/net/miniupnpd

Thanks a lot in advance.

PS: @neheb: Too late to have same miniupnp version in 19.07.x/21.07.x/master?

2022-09-18 03:04 UTC, skill7899 commented
it not work at 23.03 fw4，focre_forwarding or ext_ip_reserved_ignore  Illegal parameter when i add in /var/etc/miniupnp.conf。 
invalid option in file /var/etc/miniupnpd.conf line 11 : ext_ip_reserved_ignore=no
invalid option in file /var/etc/miniupnpd.conf line 11 : focre_forwarding=yes
@ptpt52

2022-09-18 03:29 UTC, ptpt52 commented
> it not work at 23.03 fw4，focre_forwarding or ext_ip_reserved_ignore Illegal parameter when i add in /var/etc/miniupnp.conf。 invalid option in file /var/etc/miniupnpd.conf line 11 : ext_ip_reserved_ignore=no invalid option in file /var/etc/miniupnpd.conf line 11 : focre_forwarding=yes @ptpt52

these two config options never supported  by upstream miniupnpd

2022-09-18 08:21 UTC, skill7899 commented
> > it not work at 23.03 fw4，focre_forwarding or ext_ip_reserved_ignore Illegal parameter when i add in /var/etc/miniupnp.conf。 invalid option in file /var/etc/miniupnpd.conf line 11 : ext_ip_reserved_ignore=no invalid option in file /var/etc/miniupnpd.conf line 11 : focre_forwarding=yes @ptpt52
> 
> these two config options never supported by upstream miniupnpd

Does it mean that I need to merge patch and compile myself？

2022-10-02 23:54 UTC, skill7899 commented
@ptpt52 
compile fail with ntfatbles and firewall4
Patch failed!  Please fix ./patches/301-options-force_forwarding-support.patch!
make[3]: Leaving directory '/data/cpl/packages/net/miniupnpd'
time: package/feeds/packages/miniupnpd/nftables/compile#0.18#0.08#0.23
    ERROR: package/feeds/packages/miniupnpd failed to build (build variant: nftables).

2025-04-28 08:07 UTC, rmilecki commented
Our attempts to upstream this feature have failed, see:
* https://github.com/miniupnp/miniupnp/pull/511
* https://github.com/miniupnp/miniupnp/pull/741

It seems however a similar option (`ignore_private_ip`) was added in the upstream by https://github.com/miniupnp/miniupnp/pull/813 and is present in the 2.3.9 release.