tvheadend update to v4.2.8
openwrt/packages pull request #16343
Opened 2021-08-12 14:00 UTC by M95D

Signed-off-by: M95D <m95d+git@psihoexpert.ro>

Maintainer: I guess I'm the new maintainer. The package was not updated in a long time.
Compile tested: mvebu (Marvel Armada XP), Linksys WRT1900AC v1 (mamba), OpenWRT latest snapshot
Run tested: same router, OpenWRT r16521-a3c7633ddc. tvheaded used for a few months with USB DVB tuner. UI works, live streaming works, recording works, playback works.

Description:
- version update
- removed two patches that no longer work; one of them is still needed, but I replaced it with CONFIG_OPENSSL_WITH_DEPRECATED
- added a few needed config options; build fails without them.

2021-08-12 18:08 UTC, neheb commented on multimedia/tvheadend/Makefile
> +  DEPENDS:=+libopenssl +@OPENSSL_WITH_DEPRECATED +librt +zlib +TVHEADEND_AVAHI_SUPPORT:libavahi-client $(ICONV_DEPENDS)
Please no.

2021-08-12 18:09 UTC, neheb commented on multimedia/tvheadend/Makefile
> +TARGET_CFLAGS+= -fcommon
Curious. Was this fixed upstream?

2021-08-12 18:10 UTC, neheb commented on multimedia/tvheadend/Makefile
> +PKG_RELEASE:=7
Change to $(AUTORELEASE)

2021-08-13 01:06 UTC, BKPepe requested changes
Formalities:
- In the `Signed-off-by` and also in the `PKG_MAINTAINER` field, you need to use your real name.
- Add your email (from the `Signed-off-by`) to your GitHub account. In that case, you can be recognized in that commit

2021-08-13 01:06 UTC, BKPepe commented on multimedia/tvheadend/Makefile
> +	--disable-ffmpeg_static \
This change should be described in the commit message, because you are doing more changes than just version bump.

2021-08-13 01:06 UTC, BKPepe commented on multimedia/tvheadend/Makefile
> +	--nowerror=format-truncation \
Why this is necessary at all?

2021-08-13 10:09 UTC, M95D commented
OK. I'm working on it.

2021-08-13 19:13 UTC, closed without merging