acme: Fix uhttpd restart to load new certificates (issue #16256)
openwrt/packages pull request #16482
Opened 2021-08-28 03:10 UTC by scde

Maintainer: @tohojo
Compile tested: No
Run tested: No

Description:
You have to restart `uhttpd` after cert updates for it to load them.
Right now I have to manually restart `uhttpd` after a cert expires and a reload won't work (see #16256). I am guessing because the process still has the old cert files loaded (although they are already replaced on the filesystem). You can check and see that `/etc/init.d/uhttpd reload` does not start a new process (no new PID for `uhttpd`).

Sorry for not really testing this but I am guessing this change might be small enough for it to not break anything major. Although if there are concerns about the script restarting `uhttpd` too often you might want to make a few more changes (see [my comment in the issue](https://github.com/openwrt/packages/issues/16256#issuecomment-903186029))

Best regards
scde

2021-08-29 01:22 UTC, stangri commented
As per https://openwrt.org/submitting-patches#sign_your_work, please use your real name in the signed off by.

2021-08-31 17:32 UTC, scde commented
Hi @stangri,
sorry for not reading the contribution info correctly. It should be fixed now.
BR Dennis

2021-08-31 20:54 UTC, tohojo approved these changes

2021-08-31 20:56 UTC, tohojo requested changes
Ah wait; please bump the package revision (in Makefile) along with the change...

2021-09-01 21:14 UTC, neheb commented
@scde @tohojo misspoke. Undo your change.

2021-09-02 06:05 UTC, merged

2021-09-02 08:15 UTC, scde commented
Hi,
thanks for merging.
But one more question. I am not familiar with the release process. Will this be backported to 19.07 and 21.02? Or more broadly when and where will this land?
BR Dennis

2021-09-02 08:52 UTC, neheb commented
Propose new PRs targeting whichever version. For 19.07, PKG_RELEASE will need to be bumped.