miniupnpd: add force_forwarding option support
openwrt/packages pull request #16639
Opened 2021-09-17 00:11 UTC by ptpt52

This option replace the 'ext_ip_reserved_ignore', and replace the
patch with new one

as addr_is_reserved() behavior should not be changed, so drop the
ext_ip_reserved_ignore

use a force_forwarding option to make the port forwarding force to
work when the router is behind NAT

by default force_forwarding is set to 0(disabled), where change
nothing with the original behavior, and users can turn it on
according to their wishes

related: https://github.com/openwrt/packages/pull/16011

2021-09-17 00:14 UTC, ptpt52 commented
for use case:
1. router get private IP but it is full cone nat environment, the force forwarding UPNP redirect works.

2021-09-17 00:18 UTC, ptpt52 commented
Theoretically and technically, all IPs are equal. Don't make any difference because it is a private IP. Under the understanding of this concept, this option is useful

2021-09-17 01:11 UTC, champtar commented
You need to refresh the patches (make package/miniupnpd/refresh)

2021-09-17 02:30 UTC, stangri requested changes

2021-09-17 02:30 UTC, stangri commented on net/miniupnpd/patches/301-options-force_forwarding-support.patch
> ++				syslog(LOG_NOTICE, "force_forwarding enable, private/reserved address %s used as external IP", ext_ip_addr);
If I understand the concept correctly, `force_forwarding enabled, private/reserved address %s used as external IP` is a correct way of saying this.

2021-09-17 02:32 UTC, stangri commented
> Theoretically and technically, all IPs are equal. Don't make any difference even if it is a private IP. Under this concept, this option is useful

Since this came up before, would it be possible to submit this upstream so that no modifications are needed for OpenWrt package?

Also, including @BKPepe as he has merged some PRs for this before.

2021-09-17 13:19 UTC, BKPepe requested changes
In your latest changes, you tried to upstream something, which was refused to be merged by upstream as you were changing some logics, etc. It was clearly hacked, which was merged here, and your warnings, errors were cryptic. Nobody knows what they meant. (= https://github.com/openwrt/packages/issues/15258 )

My response from the previous PR with the same changes didn't change:
https://github.com/openwrt/packages/pull/16011#pullrequestreview-698143667

TL;DR: We can not carry patches that are refused to be part of upstream and are causing several (even security) issues.  (= https://github.com/miniupnp/miniupnp/issues/556#issuecomment-907191205 ). Cooperate with upstream to get it right.

In the meantime, NAK.

2021-09-22 09:52 UTC, BKPepe commented
This was not sent to upstream and because of that, I'm closing it.

2021-09-22 09:52 UTC, closed without merging

2025-04-28 08:08 UTC, rmilecki commented
Our attempts to upstream this feature have failed, see:
* https://github.com/miniupnp/miniupnp/pull/511
* https://github.com/miniupnp/miniupnp/pull/741

It seems however a similar option (`ignore_private_ip`) was added in the upstream by https://github.com/miniupnp/miniupnp/pull/813 and is present in the 2.3.9 release.