prometheus-node-exporter-lua: add dsl error vectors to ltq-dsl
openwrt/packages pull request #16799
Opened 2021-10-04 07:39 UTC by dhewg

Maintainer: @champtar 
    
These are useful stats to debug vector related line deteriorations, see [0].

NOTE: this depends on https://github.com/openwrt/openwrt/pull/4633

[0] https://forum.openwrt.org/t/vectoring-on-lantiq-vrx200-vr9-missing-callback-for-sending-error-samples/104046

2021-10-31 15:21 UTC, dhewg commented
Anyone? Bueller?

2021-10-31 15:48 UTC, champtar commented on utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/ltq-dsl.lua
> +    mode = m.mode,
There is no need to move `mode`

2021-10-31 15:50 UTC, champtar requested changes
Sorry for the delay, can you not move `mode` and squash everything in 1 commit ?

2021-10-31 16:47 UTC, dhewg commented
np, and done! ;)

2021-11-01 01:12 UTC, champtar commented
If we move to autorelease commit should be `update to 2021.10.31`. Maybe we need an 'autoversion' for packages with source in tree. For now I think autorelease will produce weird results, so maybe drop it (or tell me what you get)

2021-11-01 06:33 UTC, dhewg commented
It's mostly to not care about the pkg version anymore, as that's increased with each commit for the package. I think it's useful to have and gets rid of the "you forgot to bump the version" churn on reviews.

But it's basically just for convenience, I removed it again as requested

2021-11-02 06:47 UTC, champtar approved these changes

2021-11-02 06:49 UTC, merged

2021-11-02 07:49 UTC, dhewg commented
Thanks!

2021-11-02 07:51 UTC, champtar commented
Thank you for the patch !