ovpn-dco: Add package
openwrt/packages pull request #16965
Opened 2021-10-23 13:53 UTC by zhaojh329

Signed-off-by: Jianhui Zhao <zhaojh329@gmail.com>

Maintainer: me
Compile tested: (mipsel, U7621-06, master)
Run tested: (mipsel, U7621-06, master, tests done)

Description:
OpenVPN Data Channel Offload in the linux kernel.
https://github.com/OpenVPN/ovpn-dco

2021-10-31 17:13 UTC, BKPepe requested changes

2021-10-31 17:13 UTC, BKPepe commented on kernel/ovpn-dco/Makefile
> +#
You should assign it to yourself or remove it completely. 
Reference:
https://github.com/openwrt/packages/blob/19596a013cc6f3c161f96ce34f48466fe8ddd99d/CONTRIBUTING.md#makefile-contents-should-contain

2021-10-31 17:13 UTC, BKPepe commented on kernel/ovpn-dco/Makefile
> +PKG_MAINTAINER:=Jianhui Zhao <zhaojh329@gmail.com>
There is missing some order. You should take a look at others Makefile in this repository.

2021-11-12 19:02 UTC, merged

2021-11-16 07:35 UTC, maurerr commented
@zhaojh329 I successfully compiled it on the 21.02 sdk and installed it -  how can I test this module - what openvpn package/option ?

2021-11-16 10:40 UTC, zhaojh329 commented
> @zhaojh329 I successfully compiled it on the 21.02 sdk and installed it - how can I test this module - what openvpn package/option ?

https://github.com/OpenVPN/openvpn3

2021-11-16 10:48 UTC, maurerr commented
> https://github.com/OpenVPN/openvpn3
is there a makefile for openvpn3 in openwrt (as I haven't found any) ?

2021-11-27 12:32 UTC, ecsv commented
@zhaojh329 Seems like this PR added a package with a bug which was also described in https://github.com/openwrt/routing/pull/757

A fix for it is to adjust the ```NOSTDINC_FLAGS``` to have at the beginning:

```
$(KERNEL_NOSTDINC_FLAGS) \
```

See also:

* https://github.com/openwrt/openwrt/commit/9ac47ee46918c45b91f4e4d1fa76b1e26b9d57fe