php8: add mod php for apache
openwrt/packages pull request #17029
Opened 2021-10-30 19:23 UTC by micmac1

The module will be available, once php8 is selected, at the same place
as the other apache modules.

Signed-off-by: Sebastian Kemper <sebastian_ml@gmx.net>

Maintainer: @mhei 

Compile tested: master from today, ath79
Run tested: same

Description:
Hi @mhei,

I still got occasionally pinged by people from the forum for mod php. So I'm hoping that will stop if this gets merged :-)

I don't know much about web servers, but I managed to get the simple example from [this link](https://rimuhosting.com/howto/php.jsp) working.

I hope I'm not forgetting any steps:

1. I installed apache-mod-php8
2. I set date.timezone in /etc/php.ini
3. I installed the zoneinfo package for my timezone
4. In /etc/apache2/apache2.conf I added 
    `LoadModule php_module lib/apache2/libphp.so`
   and also
```
    <IfModule php_module>
    AddType application/x-httpd-php .php                                
    </IfModule>
```

With this the website was working.

Kind regards,
Seb

2021-10-31 18:04 UTC, mhei requested changes
Thanks for this PR, I already wondered why nobody requested this before :smiley: 
Personally, I'm traditionally using lighttpd on embedded platforms, so I did not had a personal requirement for mod-php but why not...
That said, I've one minor change request, see comment for a specific line. Other than that, this looks really good - thanks a lot.

2021-10-31 21:52 UTC, micmac1 commented
> +define Package/apache-mod-php8/install
> +	$(INSTALL_DIR) $(1)/usr/lib/apache2
> +	$(INSTALL_BIN) $(PKG_BUILD_DIR)/staging/usr/lib/apache2/libphp.so $(1)/usr/lib/apache2
>
> This line does not work for me when doing `make package/php8/{clean,compile} V=s -j8`.  It results in:
> ```
> install: cannot stat '/srv/openwrt/openwrt-2.git/build_dir/target-arm_arm926ej-s_musl_eabi/php-8.0.12/staging/usr/lib/apache2/libphp.so': No such file or directory
> ```
>
> When changing it to
> ```
> $(INSTALL_BIN) $(PKG_BUILD_DIR)/libs/libphp.so $(1)/usr/lib/apache2
> ```
> then it works.

Hello @mhei,

For me it exists:

ls -lh build_dir/target-mips_24kc_musl/php-8.0.12/staging/usr/lib/apache2/libphp.so
-rwxr-xr-x 1 sk sk 4,0M 31. Okt 22:48 build_dir/target-mips_24kc_musl/php-8.0.12/staging/usr/lib/apache2/libphp.so

Maybe the build system hasn't copied the file to it's destination due to
"-j8"? I cannot reproduce this here (but I don't have many cores
anyway).

I'll change it as you suggested. The files seem identical anyway.

Kind regards,
Seb

2021-10-31 22:19 UTC, mhei commented
> Maybe the build system hasn't copied the file to it's destination due to
> "-j8"? I cannot reproduce this here (but I don't have many cores
> anyway).

This was my first guess, too. But also with `-j1` it does not work and I'll receive the error... I don't understand why it works on your side and where a difference between our both systems could be.
But since you changed it anyway, I'd merge this PR once the CI completed successfully.

2021-11-01 05:01 UTC, mhei approved these changes

2021-11-01 05:01 UTC, merged