ddns-scripts: Add script for TransIP.nl
openwrt/packages pull request #17136
Opened 2021-11-15 21:38 UTC by Atema

Maintainer: @chris5560 / @feckert
Compile tested: No
Run tested: Manual installation of the script on openwrt 21.02 with the current version of ddns-scripts, curl, and openssl-utils installed works as expected.

Description: Adds a custom script for updating DNS records at TransIP.nl (one of the largest registrars in The Netherlands) with ddns-scripts

2021-11-16 07:29 UTC, feckert requested changes
Unfortunately, I can't test this because I don't have an account with this provider. Everything else looks good so far

2021-11-16 07:29 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_transip_nl.sh
> +__tmp_keyfile="/tmp/ddns-transip-$(openssl rand -hex 4)"
Please use mktemp for this
https://github.com/openwrt/packages/search?q=mktemp

2021-11-16 07:29 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_transip_nl.sh
> +if [ $? -ne 0 ]
Please use `if [ $? -ne 0 ]; then`

2021-11-16 07:29 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_transip_nl.sh
> +if [ -z ${__auth_status} ] || [ ${__auth_status} -ne 201 ]
Please use ` ]; then`

2021-11-16 07:29 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_transip_nl.sh
> +if [ $? -ne 0 ]
Please use ` ]; then`

2021-11-16 07:29 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_transip_nl.sh
> +if [ -z ${__update_status} ] || [ ${__update_status} -ne 204 ]
Please use ` ]; then`

2021-11-16 09:08 UTC, Atema commented
@feckert I've updated with the requested changes. Can I assume that `mktemp` is always available?

2021-11-16 10:01 UTC, feckert commented
In the openwrt repository the requested busybox app is set to `y`
https://github.com/openwrt/openwrt/blob/b6cbbbb6ef4deaba00f5c128ea66696fc64c5bf0/package/utils/busybox/Config-defaults.in#L703
I don't expect it to change, but to be on the safe side we could add this as a dependency to.
https://github.com/openwrt/packages/pull/17136/files#diff-c0e9e626f2ba612f4284522051479b373f8481892313fdc5c766dae5e70cbf1dR213

Have a look how this could be done in openwrt https://github.com/openwrt/openwrt/blob/master/package/network/utils/wireguard-tools/Makefile#L40

2021-11-16 10:55 UTC, Atema commented
@feckert I added a dependency for `coreutils-mktemp` only if the symbol `BUSYBOX_CONFIG_MKTEMP` is not set (using syntax from https://openwrt.org/docs/guide-developer/dependencies). That should make it work in any scenario.

2021-11-30 12:13 UTC, feckert commented
@Atema thanks for this :+1: . I have update the PKG_RELEASE number so I pushed it directly.
https://github.com/openwrt/packages/commit/aa820a2cae321311097e59de9b67dfa5c648cbeb

2021-11-30 12:13 UTC, closed without merging