adguardhome: update to 0.107.0
openwrt/packages pull request #17409
Opened 2021-12-21 16:36 UTC by alaviss

Maintainer: @dobo90
Compile tested: arm64, Linksys E8450, OpenWrt SNAPSHOT r18371-5a4685cfa2
Run tested: arm64, Linksys E8450, OpenWrt SNAPSHOT r18371-5a4685cfa2, runs and functions normally.

Description:

Full changelog available at: https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.0

Also added the ability to configure working directory location.

This directory is used by AdGuard to store persistent data like query
logs, filter lists, etc.

Data stored in this directory can get really huge, as such allowing
this directory to be moved elsewhere (ie. an USB drive) is very
beneficial.

Fixes https://github.com/openwrt/packages/issues/16698
Fixes https://github.com/openwrt/packages/issues/16594

2021-12-21 21:31 UTC, dobo90 requested changes
Thanks for this pull request.

packr has been removed in
https://github.com/AdguardTeam/AdGuardHome/commit/c6888326b034daea9e69de5ee0a8f37aede45892#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261L2

So please remove:
* "packr/host" from PKG_BUILD_DEPENDS
* "packr -z -v -i internal" from Build/Compile

I've compiled this with packr removed and it seems to be working on NanoPi R2S.

My diff:
```
commit c45eb29cf7433275a3b384c711289dc339718761
Author: Dobroslaw Kijowski <dobo90@gmail.com>
Date:   Tue Dec 21 19:38:32 2021 +0100

    adguardhome: drop packr

diff --git a/net/adguardhome/Makefile b/net/adguardhome/Makefile
index f58640818..b6bbf67d1 100644
--- a/net/adguardhome/Makefile
+++ b/net/adguardhome/Makefile
@@ -18,7 +18,7 @@ PKG_LICENSE:=GPL-3.0-only
 PKG_LICENSE_FILES:=LICENSE.txt
 PKG_MAINTAINER:=Dobroslaw Kijowski <dobo90@gmail.com>
 
-PKG_BUILD_DEPENDS:=golang/host node/host node-yarn/host packr/host
+PKG_BUILD_DEPENDS:=golang/host node/host node-yarn/host
 PKG_BUILD_PARALLEL:=1
 PKG_USE_MIPS16:=0
 
@@ -57,7 +57,6 @@ define Build/Compile
        ( \
                pushd $(PKG_BUILD_DIR) ; \
                make js-deps js-build ; \
-               packr -z -v -i internal ; \
                popd ; \
                $(call GoPackage/Build/Compile) ; \
        )
```

2021-12-21 22:56 UTC, alaviss commented
Confirmed working here as well @dobo90. I pushed a new commit with your patch.

2021-12-22 12:11 UTC, BKPepe commented
I have one nitpick. Can you add to the commit description that there was removed packr? Otherwise, this is very good contribution. Thank you for that. You even added `Co-authored-by`. 👍 More contributions like this.

2021-12-22 19:02 UTC, jefferyto commented on net/adguardhome/files/adguardhome.config
> +	option workdir /tmp/adguardhome
```suggestion
	option workdir /var/adguardhome
```

`/var` is usually symlinked to `/tmp`, and if the user decides to move `/var` to persistent storage then this directory would also become persistent.

2021-12-25 20:30 UTC, mercyground commented
The adguard team use /opt/AdGuardHome for their install folder. It would make things easier if you use same location so people using the AGH wiki get to use same locations? Also that also makes it easier to redirect that folder to a usb key or an exroot partition.

2021-12-25 21:55 UTC, alaviss commented
I don't think it is a good idea to keep the working directory in the flash by default. It experiences a lot of writes due to the aggressive default logging and filter updating policy and can easily fill up root and/or wear down the flash used by routers.

Knowledgeable users that setup their own extroot should be able to modify the UCI configuration to move the folder to their external devices.

Also, `/opt` is generally meant for software that cannot be fitted into the file system hierarchy, which is not the case here.

> It would make things easier if you use same location so people using the AGH wiki get to use same locations

For this I think we should just update the AGH wiki to explain about the package provided by OpenWRT, or we can provide a readme in this repo and link it there.

2021-12-25 22:14 UTC, mercyground commented
Agreed on the flash issues. 

> For this I think we should just update the AGH wiki to explain about the package provided by OpenWRT, or we can provide a readme in this repo and link it there.

Maybe just a wiki entry on OpenWrt's wiki explaining the differences?

Due to when i originally set out to use AGH, the opkg version was 104 and had serious issues with it which i detailed in this thread. https://forum.openwrt.org/t/howto-running-adguard-home-on-openwrt/51678/224?u=mercygroundabyss

More recently i wrote up how to install and use the 107 edge build as a clean install using AGH's script with tweaks done to swap Dnsmasq to just local ptr requests and use AGH for primary DNS. Mostly because i do not have much experience with doing PRs or fixing how packages are packaged for OpenWrt. That post is here. https://forum.openwrt.org/t/how-to-updated-2021-installing-adguardhome-on-openwrt/113904

Potentially some of the work done there could be used to improve the opkg version? I've detailed my choices and decisions and some of the background for those choices in that post.

2021-12-25 22:29 UTC, mercyground commented
A few notes from my explorations:

AGH still requires some settings to be manually done via their yaml file. There is requests to be able to configure those initial setup parameters on the setup page on port 3000 or be able to configure them better. At present you either have to select which interface to use singularly or use ALL interfaces. The ability to select and manage that would make configuring easier (by selecting ALL it also includes the WAN interface which is not ideal) I believe this is due in 108.

Another issue is AGH's webinterface clashing with Luci. In my install i just installed it on port 8080 as a secondary webinterface. This also has issues with SSL. You have to setup and run SSL AGH interface on a different port.

There did used to be a luci adguardhome plugin but this appears to be unmaintained and very out of date.

rebind_protection on dnsmasq needs disabling if you switch AGH to be primary DNS.

DHCP option 6: which DNS (Domain Name Server) to include in the IP configuration for name resolution. Used to redirect clients to use AGH DNS. (I set it up this way in case others wanted to run AGH separately on a different port)

What sort of default config do we offer to opkg installed AGH users? or do we leave it for them to configure from scratch?

2021-12-25 22:49 UTC, BKPepe commented
CI failure is related to cryptodev, which is not related to somehow, so merging.

2021-12-25 22:49 UTC, merged

2021-12-25 23:05 UTC, alaviss commented
@mercyground 

Your forum post is great, though there is only this tiny correction:

> The primary being that it installs to /tmp/AdGuardHome. This means every time you reboot your router you will have to re-setup AGH.

This is false, `/tmp/adguardhome` is used as the persistent data directory, but the configuration is stored in `/etc/adguardhome.yml`, making it persistent between reboots/upgrades. So you will only lose logs, stats and filter lists (which will be automatically re-downloaded) on reboot.

Your dnsmasq configuration script is a bit overkill, though. Turning off `peerdns` and turning on `localuse` should be enough to force DNS to be done solely on the router. I will comment on some potential improvements in the forum when I find some time.

The forum post is otherwise excellent, though.

> What sort of default config do we offer to opkg installed AGH users? or do we leave it for them to configure from scratch?

Changing users settings on installation is error prone and is a side-effect that most won't expect (especially since you can't revert them on uninstall). I think it might be better to either provide a wiki entry guiding them through the installation/usage like the ones for DoH and DoT: https://openwrt.org/docs/guide-user/services/dns/dot_dnsmasq_stubby. I think your forum post is an excellent starting point for that.

I can't commit on writing wiki entries for this though, due to a lack of time.

> Hope some of my explorations and details will make the opkg version easier to install for OpenWrt users instead of having to install via the install script and do manual changes.

For now we can only avoid the tools you need to run AGH installation script and the update script with the opkg package, unfortunately.

> Another issue is AGH's webinterface clashing with Luci. In my install i just installed it on port 8080 as a secondary webinterface. This also has issues with SSL. You have to setup and run SSL AGH interface on a different port.

FWIW, I solved this problem on my system by running LuCI via nginx and setup `/adguard` as a reverse-proxy to AGH, though I couldn't get DoH interface to work this way.

2021-12-25 23:24 UTC, mercyground commented
> This is false, `/tmp/adguardhome` is used as the persistent data directory, but the configuration is stored in `/etc/adguardhome.yml`, making it persistent between reboots/upgrades. So you will only lose logs, stats and filter lists (which will be automatically re-downloaded) on reboot.

This is referring to the /much/ older 104 build. I hadn't tried the opkg version since then. I should update and make that clear.

> Your dnsmasq configuration script is a bit overkill, though. Turning off `peerdns` and turning on `localuse` should be enough to force DNS to be done solely on the router. I will comment on some potential improvements in the forum when I find some time.

I deliberately set out to make the OpenWrt DNS more bullet proof. By repointing the router DNS to Cloudflare and ignoring ISP DNS then we avoid ISP dns failures and allow the router to do NTP updates and opkg updates while AGH loads. Clients are pointed to AGH DNS so filtering is effective. The router is excluded from that because we should not need to filter the router itself.

> The forum post is otherwise excellent, though.

Thanks. It was a combined effort however. I took the original 2yr long thread from https://forum.openwrt.org/t/howto-running-adguard-home-on-openwrt/51678 and summerised it and redid it with explainations to ensure that people could follow my directions and reasoning behind it. Blindly following instructions from randomers on the internet should be considered... unwise (rm / -r? ) :)

> Changing users settings on installation is error prone and is a side-effect that most won't expect (especially since you can't revert them on uninstall). I think it might be better to either provide a wiki entry guiding them through the installation/usage like the ones for DoH and DoT: https://openwrt.org/docs/guide-user/services/dns/dot_dnsmasq_stubby. I think your forum post is an excellent starting point for that.
> I can't commit on writing wiki entries for this though, due to a lack of time.

Agreed. I do have wiki edit so i could potentially re-write my instructions into a wiki post by using a backup router and trialing the opkg version.

> For now we can only avoid the tools you need to run AGH installation script and the update script with the opkg package, unfortunately.

Making things simpler for users should hopefully reduce questions.

> FWIW, I solved this problem on my system by running LuCI via nginx and setup `/adguard` as a reverse-proxy to AGH, though I couldn't get DoH interface to work this way.

maybe using Traefik instead? but i feel that's adding potentially more complex issues. I don't see a reason personally to do more than just use AGH on port 8080 to keep things simple.

2021-12-25 23:49 UTC, alaviss commented
> By repointing the router DNS to Cloudflare and ignoring ISP DNS then we avoid ISP dns failures and allow the router to do NTP updates and opkg updates while AGH loads.

I think the only part we need to be aware of is NTP updates since correct time is required for upstream DoT/DoH servers, of which you can `[/pool.ntp.org/]1.1.1.1` to bypass it by using insecure DNS. Granted, I haven't rebooted my router to test this theory :P

> The router is excluded from that because we should not need to filter the router itself.

Do note that LuCI uses reverse DNS to resolve IP into names in wireless overview, so not using router's DNS might break it.

I haven't fully verified this, only verified that it does use rDNS since my AGH reported an insane amount of rDNS requests coming from `127.0.0.1` whenever I keep LuCI open.

And you might want to use AGH for the router just so you benefit from the same DNS cache that is shared with your other clients.

> maybe using Traefik instead? but i feel that's adding potentially more complex issues. I don't see a reason personally to do more than just use AGH on port 8080 to keep things simple.

I looked into it but settled on nginx for two reasons:

- `luci-nginx-ssl` is officially supported and basically install-and-run.
- AGH wiki has [sample configuration](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#nginx) for nginx reverse proxy.

2021-12-26 00:02 UTC, mercyground commented
> I think the only part we need to be aware of is NTP updates since correct time is required for upstream DoT/DoH servers, of which you can `[/pool.ntp.org/]1.1.1.1` to bypass it by using insecure DNS. Granted, I haven't rebooted my router to test this theory :P
> Do note that LuCI uses reverse DNS to resolve IP into names in wireless overview, so not using router's DNS might break it.
> I haven't fully verified this, only verified that it does use rDNS since my AGH reported an insane amount of rDNS requests coming from `127.0.0.1` whenever I keep LuCI open.
> And you might want to use AGH for the router just so you benefit from the same DNS cache that is shared with your other clients.

The way I approached it was to ensure OpenWrt's dnsmasq remains active but on port 5353 instead. I just point its upstream at Cloudflare. This means the routers DNS is insecure but avoids issues with ntp and luci.

To solve your issues with rdns lookups? you need to enable rDNS lookups on AGH and also a bit of interception (this is needed for multiple networks such as VLANS) This means AGH is primary DNS but dnsmasq is downstream for ptrs. Potentially in future AGH may just take over DHCP too but it is far inferior right now against OpenWrt's DHCP setup.

[https://forum.openwrt.org/uploads/default/original/3X/d/0/d0da99936ac7351015bef47ea7166be54d2009a3.png](url)

The yaml settings for this:

```
  resolve_clients: true
  use_private_ptr_resolvers: true
  local_ptr_upstreams:
  - 127.0.0.1:5353
```
Domain interception :

If you have the default OpenWrt DHCP then adding :

[/lan/]127.0.0.1:5353
[//]127.0.0.1:5353

to the upstream list that will intercept lan (internal domain) and domainless requests and pass those requests back to openwrt. "lan" is OpenWrt's default domain. (You may need to put your ip address instead of just local host.) This is necessary for multi ip networks. For simple IP networks rDNS should cover this.

> I looked into it but settled on nginx for two reasons:
> 
> * `luci-nginx-ssl` is officially supported and basically install-and-run.
> * AGH wiki has [sample configuration](https://github.com/AdguardTeam/AdGuardHome/wiki/FAQ#nginx) for nginx reverse proxy.

That is a simpler option and less work to document. Rubberstamp that idea!

2021-12-26 07:46 UTC, mercyground commented
https://forum.openwrt.org/t/request-to-create-page-for-adguard-home-under-dns-section/115582

standby for documentation /placeholder/ 👍

2021-12-26 20:12 UTC, mercyground commented
https://openwrt.org/docs/guide-user/services/dns/adguard-home

thanks to jamesmacwhite for his work with that.