netdata flavor with cloud enabled
openwrt/packages pull request #17517
Opened 2022-01-07 16:10 UTC by bolemo

Flavor were cloud is enabled

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2022-01-07 16:40 UTC, stintel requested changes
This is not a new flavour with cloud enabled, you just changed the config for the existing package. Add a new package, netdata-cloud, with the option enabled.

2022-01-07 16:52 UTC, bolemo commented
I am trying…

I only used GitHub for my own projects, alone.
I never used advanced git features or collaborated with other developers on that platform. Please allow me to learn.

There is a lot I don't understand at this point. Learning curve.

Sorry for my inexperience, but it seems the only way to have cloud enabled with netdata on openwrt is to do it myself… as you suggested.

2022-01-07 16:53 UTC, bolemo commented
> This is not a new flavour with cloud enabled, you just changed the config for the existing package. Add a new package, netdata-cloud, with the option enabled. Please also provide compile/run tested, and tag the maintainer if there is one.

How can I clone the actual package? I don't want to reinvent the wheel here…

2022-01-07 16:55 UTC, stintel commented
Appreciate the effort! I think if you `git grep VARIANT` on openwrt.git or packages.git you will find some examples. Alternatively turn to IRC, the forum or the ML for assistance.

2022-04-22 17:55 UTC, BKPepe commented
Closing for now.

2022-04-22 17:55 UTC, closed without merging