aria2: fix aria2.init re-mount issue
openwrt/packages pull request #18270
Opened 2022-04-08 08:14 UTC by Narakuku

The original procd_add_jail_mount "$config_file" will cause the init script unable to start the aria2 process.

Signed-off-by: Naraku <74468372+Narakuku@users.noreply.github.com>

Maintainer: me
Compile tested: (Linux MIPS, OpenWrt 21.02.1)
Run tested: (Linux MIPS, OpenWrt 21.02.1)

Description:
Re-mount `$config_file` inside `$config_dir` in jail will cause all files unreadable, thus unable to start the service, besides the second `procd_add_jail_mount_rw "$dir" "$config_dir"` already includes the `$config_file`.

Also, it is necessary to read-only all certificate files, so update `procd_add_jail_mount "$config_file"` to `procd_add_jail_mount "$ca_certificate" "$certificate" "$rpc_certificate" "$rpc_private_key"`.

2022-04-10 07:52 UTC, leonghui commented
Fixed #16963

Run tested: mvebu/Linksys WRT1900AC v2 OpenWrt SNAPSHOT r19417

2022-04-10 08:11 UTC, Narakuku commented
@leonghui Thank you! Exactly what is the issue and how I solved it!

But I wonder how come the package that I installed from latest OpenWrt 21.02.1 still in the wrong format. 

Nobody ever committed the fix?

2022-04-10 08:54 UTC, leonghui commented
This PR was created against the `master` branch (which is used for OpenWrt SNAPSHOT and future branches).

If the issue is also affecting 21.02, the same change will need to be backported to the `openwrt-21.02` branch (usually in a separate PR). Once the PR has been accepted and merged, the change will be picked up by the buildbots before the package gets rebuilt and updated.

I noticed that `openwrt-22.03` has branched, so the fix will need to be ported there eventually.

The review process will take time (testers and reviewers volunteer their time), so please be patient and continue enjoying OpenWrt!

2022-04-10 17:54 UTC, Narakuku commented
@leonghui 
Alright, we sit tight and assess! Got it!

2022-04-22 17:43 UTC, BKPepe requested changes
``PKG_RELEASE`` needs to be bumped in the Makefile.

2022-07-04 19:00 UTC, Acris commented
Hi @Narakuku , could you please update `PKG_RELEASE` in the Makefile to merge this pull request?

2022-07-04 19:36 UTC, Narakuku commented
@Acris @BKPepe Am I doing this correctly?

2022-09-12 19:04 UTC, merged