sexpect: Expect for Shells
openwrt/packages pull request #18332
Opened 2022-04-19 13:17 UTC by clarkwang

Sexpect is another implementation of Expect which is specifically
designed for shells. It's lightweight and has no dependency on other
packages.

Signed-off-by: Clark Wang <dearvoid@gmail.com>

Maintainer: Clark Wang <dearvoid@gmail.com>
Compile tested: 21.02.3-ramips-mt7621
Run tested: 21.02.3-ramips-mt7621 (Netgear R6220)

Description:

2022-04-22 15:25 UTC, BKPepe commented on utils/sexpect/Makefile
> +PKG_LICENSE       := GPL-3.0
This is outdated SPDX LICENSE Identifier.

2022-04-22 15:28 UTC, BKPepe requested changes
I know that this was merged to master, but I am not sure who reviewed this.

1. Would you please create file ``test.sh`` to be run-tested in GitHub Actions?
2. I know that you are using a different editor than most of us, but can you please remove additional spaces/tabs between variable and ``:=``? This is a minor thing and mostly a cosmetic one, but we need to stick to some format, which we have here. It might be wrong or not, but this is what we have here. 

3. I am not sure why this package is necessary or what the usage is.

2022-04-22 16:43 UTC, clarkwang commented
Hi BKPepe,

I've updated the license to GPL-3.0-only.

> I know that this was merged to master, but I am not sure who reviewed this.
> 
> 1. Would you please create file `test.sh` to be run-tested in GitHub Actions?

Done.

> 2. I know that you are using a different editor than most of us, but can you please remove additional spaces/tabs between variable and `:=`? This is a minor thing and mostly a cosmetic one, but we need to stick to some format, which we have here. It might be wrong or not, but this is what we have here.

Done.

> 3. I am not sure why this package is necessary or what the usage is.

It's like Expect (for Tcl) or pexpect (for Python)but does not depend on any other packages so you don't need to install Tcl or Python. It's used to automate interactive commands.

A few discussions:

* https://forum.archive.openwrt.org/viewtopic.php?id=57624
* https://forum.archive.openwrt.org/viewtopic.php?id=57254

2022-04-22 18:13 UTC, jefferyto commented
I think it would be better to make changes to master first, then cherry pick the commits for the openwrt-22.03 branch.

2022-04-28 13:17 UTC, clarkwang commented
Hi @BKPepe ,

I've made the change on master branch. Not sure if I need to combine 2 commits into 1 commit before merging to 22.03 branch. Please advise.

2022-04-28 13:18 UTC, BKPepe commented
Hi,

They should be cherry-picked from master. Right now, it is not clear from the commit description, that they were. You might want to use ``git cherry-pick -x hash`` or you can add it there manually.

2022-05-10 19:51 UTC, merged