passh: an sshpass alternative
openwrt/packages pull request #18333
Opened 2022-04-19 13:19 UTC by clarkwang

Sshpass does not work well in a few scenarios. Passh is an sshpass
alternative which tries to fix the issues.

Signed-off-by: Clark Wang <dearvoid@gmail.com>

Maintainer: Clark Wang <dearvoid@gmail.com>
Compile tested: 21.02.3-ramips-mt7621
Run tested: 21.02.3-ramips-mt7621 (Netgear R6220)

Description:

2022-04-22 15:29 UTC, BKPepe requested changes
Same as https://github.com/openwrt/packages/pull/18332#pullrequestreview-950258582

2022-04-22 15:29 UTC, BKPepe commented on utils/passh/Makefile
> +PKG_LICENSE       := GPL-3.0
This is old SPDX License Identifier.
Please see: https://spdx.org/licenses/

2022-04-22 16:44 UTC, clarkwang commented
Hi BKPepe,

I've updated the license and added a test.sh.

2022-04-22 17:33 UTC, BKPepe commented
Thanks! Please split the changes to the separate commit and send it to the master first

2022-04-29 02:48 UTC, clarkwang commented
Has committed to master first and cherry-picked to 22.03 branch.

2022-05-10 19:49 UTC, merged