Libraries and tools for SRT
openwrt/packages pull request #18817
Opened 2022-06-25 11:35 UTC by qiankehan

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (x86_64, KVM, OpenWrt 21.02.2)
Run tested: (x86_64, KVM, OpenWrt 21.02.2, tests done)

Description:
Add package srt-utils, libsrt, and srt-live-server. These would provide live stream servers for Secure Reliable Tranport(SRT)

2022-06-28 08:22 UTC, feckert requested changes
I do not know if this is necessary, but could you please add a lincense header to your make files?
```
#
# Copyright (C) 2022 Han Han
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
```

2022-06-28 08:22 UTC, feckert commented on multimedia/srt-live-server/Makefile
> +		               CXX="$(TARGET_CXX)" \
The indentation does not fit please use `tabs`

2022-06-28 08:22 UTC, feckert commented on multimedia/srt-live-server/Makefile
> +PKG_SOURCE_NAME:=$(PKG_NAME)
see above `libs/srt/Makefile`

2022-06-28 08:22 UTC, feckert commented on multimedia/srt-live-server/Makefile
> +PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_SOURCE_NAME)-$(PKG_VERSION)
see above `libs/srt/Makefile`

2022-07-01 15:47 UTC, qiankehan commented
@feckert Thanks for your review. I am not familiar with the makefile of OpenWRT packages. So I copy some formats from other packages while I do not quite understand them.

2024-10-18 11:43 UTC, BKPepe commented
Done in https://github.com/openwrt/packages/pull/25069, closing!

2024-10-18 11:43 UTC, closed without merging