Fixed dependencies to avoid building unneeded packages
openwrt/packages pull request #19021
Opened 2022-07-22 18:27 UTC by borkra

This prevents building of unused packages during OpenWRT image build

2022-07-22 20:03 UTC, cotequeiroz requested changes

2022-07-22 20:03 UTC, cotequeiroz commented on net/gensio/Makefile
> +
We should not add this blank line here.

2022-07-22 20:08 UTC, borkra commented on net/gensio/Makefile
> +  BUILD_DEPENDS:=+PACKAGE_python3-gensio:swig +PACKAGE_python3-gensio:python3
It seems like BUILD_DEPENDS is there until I changed it, it kept building Python. But I will look more.

2022-07-22 20:21 UTC, borkra commented on net/gensio/Makefile
> +
Fixed

2022-07-22 20:21 UTC, borkra commented on net/gensio/Makefile
> +  BUILD_DEPENDS:=+PACKAGE_python3-gensio:swig +PACKAGE_python3-gensio:python3
Fixed

2022-08-03 13:46 UTC, borkra commented
@cotequeiroz could you please remove 'changes requested' since they were done

2022-08-03 13:54 UTC, cotequeiroz approved these changes
I’ll let the Ci build it, then it can be merged.

2022-08-04 02:44 UTC, merged