apinger: add rrd graph support
openwrt/packages pull request #19073
Opened 2022-07-28 14:37 UTC by jempatel

- add rrdtool1 and rrdcgi1 dependency for RRD graphs
- add RPC to get an overview and update graphs
- fix interface hotplug to restart apinger instance
- add patch to split alarms list in the status

Signed-off-by: Jaymin Patel <jem.patel@gmail.com>

Maintainer: @samm-git
Run tested: x86-64, aarch64, virtual box, marvell_armada-3720-db, v21.02.3

Description:
Add RRD configuration support in UCI

2022-07-28 17:24 UTC, samm-git commented
Looks amazing. My only concern is hard dependency on rrd, so on minimal setups this would increase significantly. Should we have a subpackage instead?

2022-07-28 22:23 UTC, jempatel commented
> Looks amazing. My only concern is hard dependency on rrd, so on minimal setups this would increase significantly. Should we have a subpackage instead?

Added another package apinger-rrd, dependencies are also handled in luci-app-apinger.
https://github.com/openwrt/luci/pull/5887

2022-07-29 07:02 UTC, feckert requested changes

2022-07-29 09:50 UTC, jempatel commented on net/apinger/files/apinger.init
> +	[ "$rrd" == "1" ]                 && append_config_line "rrd file \"$APINGER_RRD/apinger-target-$target.rrd\""
Updated

2022-07-29 09:51 UTC, jempatel commented on net/apinger/Makefile
> +	$(INSTALL_DATA) ./files/graphs.sh $(1)/lib/apinger/rpc
Updated

2022-07-29 14:12 UTC, feckert commented
looks good

2022-07-29 14:12 UTC, merged