rclone: fix init script on CIDR format ipaddr
openwrt/packages pull request #19109
Opened 2022-08-04 09:15 UTC by jjm2473

Signed-off-by: 练亮斌 <jjm2473@gmail.com>

Maintainer: Elon Huang <elonhhuang@gmail.com>
Compile tested: none
Run tested: ARS2, arm64, openwrt 21.02.3

Description:
fix rclone init script on CIDR format ipaddr

2022-08-04 15:34 UTC, 1715173329 requested changes

2022-08-05 13:45 UTC, 1715173329 approved these changes
LGTM - Thanks.

btw, after this PR getting merged, please cherry-pick it to 21.02 and 22.03 branch.

2022-08-08 14:35 UTC, jjm2473 commented
👌

2022-08-13 09:34 UTC, merged

2022-08-13 09:35 UTC, BKPepe commented
- OpenWrt 22.03: https://github.com/openwrt/packages/commit/b621a75f36f15475bb2537c1d5522c673480e784
- OpenWrt 21.02: https://github.com/openwrt/packages/commit/5b5685f90aa9964719e83720b6f8a510ecc4c2fd