bcp38: migration to nftables
openwrt/packages pull request #19354
Opened 2022-09-13 07:23 UTC by ne20002

Maintainer: me / Toke Høiland-Jørgensen <toke@toke.dk>
Compile tested: no compile, script
Run tested: mvebu, WRT3200ACM, Openwrt 22.03.0

Description: this is a migration of bcp38 package to nftables

This implementation creates a new ip table with priority 2 (can be set in options) to filter spoofed packages.

2022-09-14 18:56 UTC, hnyman commented
This should first got into master, and then possibly later backported into 22.03. 
But not vice versa.

cc maintainer @tohojo

2022-09-15 15:31 UTC, ne20002 commented
I fixed the script output. The filter shall now work as expected.

What's the correct way for the merge request? Create a new one for master?
Is there a way to squash commits in github.com UI?

2022-09-15 17:08 UTC, hnyman requested changes
I made some suggestions about the code style / minor nitpicking, but my nftables skills do not really enable be to understand if your changes actually work in the fw4 system. 

Would be great if @jow- would look into the code.

2022-09-16 06:04 UTC, ne20002 commented
Thanks you.
I'll do as advised. I let this PR open until then.

2022-09-16 08:24 UTC, tohojo commented
Hannu Nyman ***@***.***> writes:

> @hnyman requested changes on this pull request.

I'll take a look at this next week!

2022-09-16 16:50 UTC, ne20002 commented
I created a new  [`pull request`](https://github.com/openwrt/packages/pull/19387)  going to master as advised.
I close this one.

2022-09-16 16:50 UTC, closed without merging