mdk4 - add aircrack-ng/mdk4 to net/
openwrt/packages pull request #19587
Opened 2022-10-11 07:39 UTC by commonism

Compile tested: OpenWrt Docker SDK / mips_24kc / mipsel_74kc.ipk
Run tested: TP-Link Archer C7 v2

Description: MDK is a proof-of-concept tool to exploit common IEEE 802.11 protocol weaknesses.

2022-10-13 23:02 UTC, neheb commented on net/mdk4/Makefile
> +    DEPENDS:= +libnl +libpcap
noreply.github.com ...

2022-10-14 05:53 UTC, commonism commented
I can build this with the docker sdk image easily.

I seem to fail to understand the usage of PKG_HASH or PKG_MIRROR_HASH for git clones.
Somebody to help out?

```
mkdir -p /home/build/openwrt/dl
SHELL= flock /home/build/openwrt/tmp/.mdk4-2021-07-07-683e074f.tar.xz.flock -c '  	 /home/build/openwrt/scripts/dl_github_archive.py --dl-dir="/home/build/openwrt/dl" --url="https://github.com/aircrack-ng/mdk4" --version="683e074f081624418f50090641a09db53ce0378d" --subdir="mdk4-2021-07-07-683e074f" --source="mdk4-2021-07-07-683e074f.tar.xz" --hash="x" || ( 	echo "Checking out files from the git repository..."; mkdir -p /home/build/openwrt/tmp/dl && cd /home/build/openwrt/tmp/dl && rm -rf mdk4-2021-07-07-683e074f && [ \! -d mdk4-2021-07-07-683e074f ] && git clone  https://github.com/aircrack-ng/mdk4 mdk4-2021-07-07-683e074f && (cd mdk4-2021-07-07-683e074f && git checkout 683e074f081624418f50090641a09db53ce0378d && git submodule update --init --recursive) && echo "Packing checkout..." && export TAR_TIMESTAMP=`cd mdk4-2021-07-07-683e074f && git log -1 --format='\''@%ct'\''` && rm -rf mdk4-2021-07-07-683e074f/.git && 	tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c mdk4-2021-07-07-683e074f | 	xz -zc -7e > /home/build/openwrt/tmp/dl/mdk4-2021-07-07-683e074f.tar.xz && mv /home/build/openwrt/tmp/dl/mdk4-2021-07-07-683e074f.tar.xz /home/build/openwrt/dl/ && rm -rf mdk4-2021-07-07-683e074f; );     '
mdk4-2021-07-07-683e074f.tar.xz: Download from https://github.com/aircrack-ng/mdk4 failed
mdk4-2021-07-07-683e074f.tar.xz: Requires sha256sum for verification
Checking out files from the git repository...
Cloning into 'mdk4-2021-07-07-683e074f'...
Note: switching to '683e074f081624418f50090641a09db53ce0378d'.
…

HEAD is now at 683e074 .
Packing checkout...
make[2]: Leaving directory '/feed/net/mdk4'
```

```
 Config-build.in:3939:warning: defaults for choice values not supported
#
# No change to .config
#
make[1]: Entering directory '/home/build/openwrt'
make[2]: Entering directory '/feed/net/mdk4'
WARNING: PKG_MIRROR_HASH is missing, set to f4fa0abb8c3b2191d70b2cbf7a52d807fbce20eaed29908e24588141872225ef
make[2]: Leaving directory '/feed/net/mdk4'
time: package/feeds/packages_ci/mdk4/check#0.00#0.00#0.02
make[1]: Leaving directory '/home/build/openwrt'
Package HASH check failed
Error: Process completed with exit code 1.
```

2022-10-14 06:09 UTC, neheb commented
make package/mdk4/check FIXUP=1

2022-10-14 06:17 UTC, commonism commented
```
build@807d5f894a3e:~/openwrt$ make package/mdk4/check FIXUP=1
Collecting package info: done
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'eip197-mini-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'r8169-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'e100-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'bnx2x-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'ar3k-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'mwifiex-sdio-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb2', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'edgeport-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'r8152-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'kmod-phy-bcm-ns-usb3', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'amdgpu-firmware', which does not exist
WARNING: Makefile 'package/kernel/linux/Makefile' has a dependency on 'radeon-firmware', which does not exist
make[2]: Entering directory '/home/build/openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory '/home/build/openwrt/scripts/config'
tmp/.config-package.in:70:warning: ignoring type redefinition of 'PACKAGE_libc' from 'bool' to 'tristate'
tmp/.config-package.in:98:warning: ignoring type redefinition of 'PACKAGE_libgcc' from 'bool' to 'tristate'
tmp/.config-package.in:219:warning: ignoring type redefinition of 'PACKAGE_libpthread' from 'bool' to 'tristate'
Config-build.in:3931:warning: defaults for choice values not supported
Config-build.in:3935:warning: defaults for choice values not supported
Config-build.in:3939:warning: defaults for choice values not supported
#
# No change to .config
#
 make[1] package/mdk4/check
 make[2] -C feeds/packages/net/mdk4 check

2022-10-29 03:42 UTC, BKPepe requested changes
1. Missing description for the package in the Makefile
  - In the commit message, there should be some reasons why this package should be here and what it does
  
 2. Commit subject could me somehow improved e.g. "mdk4: add a new package"
    - Because folder ``/net`` should not be there as it is obvious that you are adding a new package
    
 3. No reply e-mails are not preferred and should not be used here
 
 4.  Having ``test.sh`` would be nice.
 
 5. Why don't you use MDK4 releases or tags?

2022-10-29 03:42 UTC, BKPepe commented on net/mdk4/Makefile
> +PKG_MIRROR_HASH:=f4fa0abb8c3b2191d70b2cbf7a52d807fbce20eaed29908e24588141872225ef
```suggestion
PKG_NAME:=mdk4
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://github.com/aircrack-ng/mdk4
PKG_SOURCE_DATE:=2021-07-07
PKG_SOURCE_VERSION:=683e074f081624418f50090641a09db53ce0378d
PKG_MIRROR_HASH:=f4fa0abb8c3b2191d70b2cbf7a52d807fbce20eaed29908e24588141872225ef

PKG_LICENSE:=GPL-3.0-or-later
PKG_LICENSE_FILES:=COPYING
```

2023-02-23 07:09 UTC, BKPepe commented
Closing due to OP inactivity. Feel free to reopen it once you address the review.

2023-02-23 07:09 UTC, closed without merging