fvpn: initial stable release v0.2.1
openwrt/packages pull request #19724
Opened 2022-10-28 13:11 UTC by anatolio-deb

Signed-off-by: Anatolio Nikiforidis anatoly@forestvpn.com

Maintainer: me
Compile tested: main/arm64
Run tested: main/arm64

2022-10-28 14:25 UTC, BKPepe requested changes
I briefly checked it and found something what could be improved. Anyway, I am not sure if this can be merged when looking into https://forestvpn.com/pricing/ , so I will leave it to the other guys to decide.

2022-10-28 14:25 UTC, BKPepe commented on net/fvpn/Makefile
> +endef
Why are you calling the same?

2022-10-28 14:25 UTC, BKPepe commented on net/fvpn/Makefile
> +define Package/fvpn/template
No need to use template.

2022-10-28 16:21 UTC, BKPepe commented on net/fvpn/Makefile
> +PKG_SOURCE:=v$(PKG_VERSION).tar.gz
Oh, this is wrong. The tarball will be downloaded as "v$(PKG_VERSION).tar.gz" in dl folder w/o any name.

2022-10-31 07:59 UTC, anatolio-deb commented
> I briefly checked it and found something what could be improved. Anyway, I am not sure if this can be merged when looking into https://forestvpn.com/pricing/ , so I will leave it to the other guys to decide.

Hi, thank you for your review. We are going to change our business plan and make some of our resources available fo free and without ads.

2022-11-02 05:23 UTC, 1715173329 commented on net/fvpn/Makefile
> +PKG_SOURCE_URL:=https://codeload.github.com/forestvpn/cli/tar.gz/refs/tags/v$(PKG_VERSION)
```suggestion
PKG_SOURCE_URL:=https://codeload.github.com/forestvpn/cli/tar.gz/v$(PKG_VERSION)?
```

2022-11-02 05:23 UTC, 1715173329 commented on net/fvpn/Makefile
> +
```suggestion

```

2022-11-02 05:23 UTC, 1715173329 commented on net/fvpn/Makefile
> +  ForestVPN - Fast, secure, and modern VPN.
This description is really tiny, just move it to TITLE.

2022-11-02 05:23 UTC, 1715173329 commented on net/fvpn/test.sh
> +		fvpn --version 2>&1 | grep "$PKG_VERSION"
As there only exists one package, the usage of `case` can be removed.

2022-11-02 11:07 UTC, 1715173329 commented on net/fvpn/Makefile
> +PKG_SOURCE_URL:=https://codeload.github.com/forestvpn/cli/tar.gz/refs/tags/v$(PKG_VERSION)
`?` is necessary here

2022-11-06 10:56 UTC, 1715173329 commented
Final step is to squash all of your commits into a single one.
But looks like repo managers here do not like this package...

2022-11-06 11:19 UTC, anatolio-deb commented
> Final step is to squash all of your commits into a single one.
> But looks like repo managers here do not like this package...

Thank you for your feedback. We are going to provide freeware services in this package.

2022-11-12 14:55 UTC, closed without merging