ruby: update to 3.1.3
openwrt/packages pull request #20041
Opened 2022-12-08 02:24 UTC by bradfordzhang

Add a comment about confusing code
---
 configure.ac | 1 +
 1 file changed, 1 insertion(+)

Signed-off-by: Bradford Zhang <zyc@zyc.name>

2022-12-08 04:40 UTC, 1715173329 requested changes

2022-12-08 04:40 UTC, 1715173329 commented on lang/ruby/patches/001-fix-build-with-libressl-3.5.patch
> +From: Bradford Zhang <zyc@zyc.name>
what? this is not good. please keep original authorship.

2022-12-08 04:40 UTC, 1715173329 commented on lang/ruby/patches/001-fix-build-with-libressl-3.5.patch
> +@@ -710,7 +710,7 @@ ossl_pkey_export_traditional(int argc, VALUE *argv, VALUE self, int to_der)
run `make package/ruby/refresh V=s` to refresh patches.

2022-12-08 05:20 UTC, bradfordzhang commented on lang/ruby/Makefile
>  PKG_RELEASE:=$(AUTORELEASE)
Thanks but I give up

2022-12-08 05:20 UTC, closed without merging

2022-12-12 03:17 UTC, luizluca commented
Thanks @bradfordzhang . I'll take it from here (#20064). But, please, try it again next time. Minor version bumps are normally straightforward.  

The $(AUTORELEASE) change hit you mid air. It is not directly related to ruby (or any other package) but it was recently deprecated by openwrt team. Any changes that touches a package that uses it should replaced that with a fixed number,  manually incremented on each package change.  As we are changing the version number as well, the release number rewinds back to 1.

And the `make package/ruby/refresh V=s` would fix the patches automatically for you. It looks like you did it manually because the line was not truncated. And we don't change author when a patch is refreshed. If you needed to modify it, you can explicitly add your info after the original commit message (before the ---).

Your commit message had a strange content: "Add a comment about confusing code". Version bumps do not need to be very verbose but it is nice to add CVE numbers when they are fixed.

2022-12-12 03:21 UTC, bradfordzhang commented
> Thanks @bradfordzhang . I'll take it from here (#20064). But, please, try it again next time. Minor version bumps are normally straightforward.
> 
> The $(AUTORELEASE) change hit you mid air. It is not directly related to ruby (or any other package) but it was recently deprecated by openwrt team. Any changes that touches a package that uses it should replaced that with a fixed number, manually incremented on each package change. As we are changing the version number as well, the release number rewinds back to 1.
> 
> And the `make package/ruby/refresh V=s` would fix the patches automatically for you. It looks like you did it manually because the line was not truncated. And we don't change author when a patch is refreshed. If you needed to modify it, you can explicitly add your info after the original commit message (before the ---).
> 
> Your commit message had a strange content: "Add a comment about confusing code". Version bumps do not need to be very verbose but it is nice to add CVE numbers when they are fixed.

Thanks a lot. I'll do it better next time. :-)