Package dependencies for ble2mqtt python package
openwrt/packages pull request #20633
Opened 2023-03-10 23:08 UTC by QuintinHill

Maintainer: me 
Compile tested: Unfortunately not (I tried without success to build this out on my machine but I think this is more of a failure in my setup.)  Hopefully CI will test this.
Run tested: Unfortunately not

Description: [ble2mqtt](https://github.com/devbis/ble2mqtt) is an interesting python package unfortunately it requires [Bleak](https://github.com/hbldh/bleak) which requires [dbus-fast](https://github.com/Bluetooth-Devices/dbus-fast) and this latter package cannot be successfully installed on a router with 128MB of RAM using pip (it runs out of memory and crashes).  This PR packages the dependencies for ble2mqtt but dbus-fast is the priority here.

2023-03-12 09:34 UTC, 1715173329 requested changes

2023-03-12 09:34 UTC, 1715173329 commented on lang/python/python-ble2mqtt/Makefile
> +  VARIANT:=python3
```suggestion
  DEPENDS:=+python3 +python-bleak +python-aio-mqtt-mod
```

the dependency list is short enough, no need to wrap new lines.
`VARIANT:=python3` has been deprecated in py3 makefile.

2023-03-12 09:34 UTC, 1715173329 commented on lang/python/python-bleak/Makefile
> +  VARIANT:=python3
```suggestion
  DEPENDS:=+python3 +python3-asyncio +python-dbus-fast
```

2023-03-12 09:34 UTC, 1715173329 commented on lang/python/python-dbus-fast/Makefile
> +  VARIANT:=python3
```suggestion
  DEPENDS:=+python3 +python3-async-timeout
```

2023-03-12 09:34 UTC, 1715173329 commented on lang/python/python-aio-mqtt-mod/Makefile
> +  VARIANT:=python3
```suggestion
```

2023-03-13 09:13 UTC, jefferyto reviewed
I also suggest you:

* Test build these packages using a local build environment. I suggest [using the SDK](https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk).

  If you do this (after applying the changes suggested by @1715173329 and myself) you will find the packages will still not build, for reasons outside of your control, but this is still important because:

* Run, for each package:

  ```
  make package/<package name>/{clean,configure} PY3=stdlib V=s
  ```

  This will show you which Python standard library packages are used by each package. If a package requires 3 or less standard library packages, I suggest replacing the `+python3` dependency with `+python3-light` plus the reported dependencies.

2023-03-13 09:13 UTC, jefferyto commented on lang/python/python-dbus-fast/Makefile
> +  TITLE:=Python DBus library
```suggestion
  TITLE:=A faster version of dbus-next
```

2023-03-14 11:06 UTC, karlp commented on lang/python/python-bleak/Makefile
> +  	+python3-asyncio
well, yes, but also no.  You absolutely can't use bleak withotu asyncio, but that's stricly speaking on the user end.
I'd packaged this locally, but was batching it up with some other stuff.  I just used python3-light, and that's "enough" but you absolutely need asyncio to _use_ bleak.

2023-03-14 11:08 UTC, karlp commented
The bleak and dbus-fast packages (after suggested changes), are virtually identical to what I've been using locally, so they look good.  No comments on the other two

2023-03-17 23:05 UTC, QuintinHill commented on lang/python/python-bleak/Makefile
> +  	+python3-asyncio
I've made it depend on both and put a note about the runtime dependency in the commit message.

2023-03-17 23:10 UTC, QuintinHill commented
@jefferyto  I tried those commands but got no error apart from:
`WARNING: Makefile 'package/feeds/local/python-ble2mqtt/Makefile' has a dependency on 'python-bleak', which does not exist
WARNING: Makefile 'package/feeds/local/python-ble2mqtt/Makefile' has a dependency on 'python-aio-mqtt-mod', which does not exist
WARNING: Makefile 'package/feeds/local/python-bleak/Makefile' has a dependency on 'python-dbus-fast', which does not exist
`
It was a useful exercise as I found had got the PyPI name of dbus-fast wrong (it needs to be dbus_fast).  Hopefully everything is more in order now.  Thank you for your help with this.

2023-03-17 23:21 UTC, QuintinHill commented on lang/python/python-bleak/Makefile
> +  	+python3-asyncio
It looks like in release of v0.20.0 release of bleak a few minutes ago the dependency will be dropped when using python 3.11+

2023-03-20 07:29 UTC, jefferyto commented on lang/python/python-ble2mqtt/Makefile
> +  DEPENDS:=+python3-light +python-aio-mqtt-mod +python3-asyncio +python-bleak +python3-logging
```suggestion
  DEPENDS:=+python3-light +python3-aio-mqtt-mod +python3-asyncio +python3-bleak +python3-logging
```

2023-03-20 07:29 UTC, jefferyto commented on lang/python/python-bleak/Makefile
> +	+python-dbus-fast +python3-ctypes +python3-logging
```suggestion
	+python3-dbus-fast +python3-ctypes +python3-logging
```

2023-03-20 07:29 UTC, jefferyto commented on lang/python/python-dbus-fast/Makefile
> +	+python3-distutils +python3-logging +python3-urllib +python3-xml
```suggestion
	+python3-logging +python3-urllib +python3-xml
```

distutils is only used in [build_ext.py](https://github.com/Bluetooth-Devices/dbus-fast/blob/v1.84.2/build_ext.py#L4), which should be only used during build/setup and not run-time.

2023-03-20 07:29 UTC, jefferyto commented on lang/python/python-dbus-fast/Makefile
> +PYPI_NAME:=dbus_fast
```suggestion
PYPI_NAME:=dbus-fast
PYPI_SOURCE_NAME:=dbus_fast
```

2023-03-20 07:36 UTC, jefferyto commented
> I did see the following warnings but I guess they can be ignored:

The names in `DEPENDS` should be the opkg package names (e.g. `python3-bleak`) not the source package name (python-bleak).

Also, since bleak is a new package, I would prefer if the "upgrade" commit was squashed into the "add package" commit.

2023-03-21 13:06 UTC, QuintinHill commented on lang/python/python-bleak/Makefile
> +  URL:=https://github.com/hbldh/bleakpython3-ctypes
Copy and paste error!

2023-03-21 13:06 UTC, QuintinHill commented
I'm not sure why the test is failing:
```
Testing package python3-ble2mqtt-src in version 0.1.5 from python-ble2mqtt
Installing python3-ble2mqtt-src (0.1.5-1) to root...
Configuring python3-ble2mqtt-src.
No test.sh script available
Removing package python3-ble2mqtt-src from root...
Testing package python3-ble2mqtt in version 0.1.5 from python-ble2mqtt
Unknown package 'python3-ble2mqtt'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency python3-aio-mqtt-mod for python3-ble2mqtt
 * pkg_hash_check_unresolved: cannot find dependency python3-bleak for python3-ble2mqtt
 * pkg_hash_fetch_best_installation_candidate: Packages for python3-ble2mqtt found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package python3-ble2mqtt.
Error: Process completed with exit code 255.
```

I have the copy & paste error to fix but I will refrain from updating until I can understand why this is failing.

2023-03-22 03:11 UTC, jefferyto commented
> I'm not sure why the test is failing:

That error is because those packages are new, they are not available to download by opkg yet. The run-test installs each package from the locally compiled ipk file, but opkg doesn't know to look to other locally compiled ipk files to satisfy dependencies.

I think this is okay to merge once the bleak URL has been fixed :smile:

2023-03-22 09:07 UTC, QuintinHill commented
Done!

2023-03-30 04:28 UTC, merged

2023-03-30 04:28 UTC, jefferyto commented
Thanks again!