openvpn: update to 2.6.4
openwrt/packages pull request #21322
Opened 2023-06-10 03:57 UTC by blackzafiqz

Maintainer: @mkrkn
Compile tested: mt7622, snapshot
Run tested: Xiaomi AX3200

Updated to 2.6.4

2023-06-12 03:32 UTC, blackzafiqz commented
@mkrkn  can you approve test build again?

2023-06-15 19:42 UTC, AuthorReflex commented
compile && runtime tested builds:
ramips mt7621/Xiaomi Mi router pro - openssl variant
ramips mt7620/TP-Link Archer C50 - mbedtls variant
ramips mt7621/Beeline Smartbox Giga - wolfssl variant

MiR3P is a server, many clients (windows, linux, embedded) works without problems
also, MiR3P is a client to vps in another country
Everything works fine.

2023-06-16 06:39 UTC, AuthorReflex commented
And 2.6.5 is out
no changes in patches requred

2023-06-16 06:58 UTC, blackzafiqz commented
I will update it tonight.

On Fri, 16 Jun 2023, 14:40 Ivan Pavlov, ***@***.***> wrote:

> And 2.6.5 is out
> no changes in patches requred
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/21322#issuecomment-1594183789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AECGSRGCQBRIRX7SLLWDNA3XLP5ULANCNFSM6AAAAAAZBNKZ6E>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-16 16:21 UTC, blackzafiqz commented
@AuthorReflex may i know why github build throw up: Dirty patches detected, please refresh and review the diff. I already tried make package/openvpn/{clean,refresh}

2023-06-16 16:30 UTC, AuthorReflex commented
> @AuthorReflex may i know why github build throw up: Dirty patches detected, please refresh and review the diff. I already tried `make package/openvpn/{clean,refresh}`

cause is described in my review (in patch file removed lines must be ```---a``` added lines must be ```+++b```) in patch 101 it's wrong

2023-06-16 17:55 UTC, blackzafiqz commented
Thank you, fixed and pushed.

2023-06-16 17:59 UTC, AuthorReflex commented
> Thank you, fixed and pushed.

still errors here
[101-wolfssl-disable-usage-unimplemented-functions.patch]
```
--- a/src/openvpn/crypto_openssl.c
+++ a/src/openvpn/crypto_openssl.c
```
+++ must be "b"

2023-06-16 18:47 UTC, blackzafiqz commented
my bad, didn't staged that file. thank you sir.

2023-06-17 04:47 UTC, AuthorReflex commented
Refreshed && tested on my devices. LGTM

2023-06-17 12:48 UTC, AuthorReflex commented
@blackzafiqz  you need to push file 101-wolfssl-disable-usage-unimplemented-functions.patch after refreshing

2023-06-18 06:15 UTC, BKPepe requested changes

2023-06-18 06:15 UTC, BKPepe commented on net/openvpn/Config-mbedtls.in
> -config OPENVPN_mbedtls_ENABLE_MULTIHOME
Why this was removed? I can not see anything in the commit description.

2023-06-18 06:15 UTC, BKPepe commented on net/openvpn/Makefile
> +  DEPENDS:=+kmod-tun +libcap-ng +OPENVPN_$(1)_ENABLE_LZO:liblzo +OPENVPN_$(1)_ENABLE_LZ4:liblz4 +OPENVPN_$(1)_ENABLE_IPROUTE2:ip +OPENVPN_$(1)_ENABLE_DCO:libnl-genl $(3)
dtto

2023-06-18 06:15 UTC, BKPepe commented on net/openvpn/Makefile
> +PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
dtto. It appears that upstream changed the compression. There should be something in the commit description about that.

2023-06-18 19:52 UTC, AuthorReflex commented on net/openvpn/patches/101-wolfssl-disable-usage-unimplemented-functions.patch
> +@@ -51,7 +51,7 @@
```
@@ -1419,7 +1419,7 @@ engine_load_key(const char *file, SSL_CT
 #endif /* if HAVE_OPENSSL_ENGINE */
 }
 ```
 incorrect patch place causes an error

2023-06-21 17:58 UTC, jefferyto commented
I think your commit message needs to explain the changes you are making.

2023-06-22 11:53 UTC, blackzafiqz commented
i will update everything tomorrow

On Thu, 22 Jun 2023, 01:58 Jeffery To, ***@***.***> wrote:

> I think your commit message needs to explain the changes you are making.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/21322#issuecomment-1601325657>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AECGSRGMXZHHNAFLZKCYEP3XMMY4PANCNFSM6AAAAAAZBNKZ6E>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-05 11:52 UTC, sch-m commented
@blackzafiqz Are you still working on this PR?

I am also interested in getting openvpn-2.6.x with DCO support in and did some work here:
https://github.com/openwrt/packages/compare/master...TDT-AG:packages:pr/20230628-openvpn-dco

2023-07-05 16:33 UTC, danny30au commented
> @blackzafiqz Are you still working on this PR?
> 
> I am also interested in getting openvpn-2.6.x with DCO support in and did some work here: [master...TDT-AG:packages:pr/20230628-openvpn-dco](https://github.com/openwrt/packages/compare/master...TDT-AG:packages:pr/20230628-openvpn-dco)

Hopefully we can get this "Pushed" to master soonish the (offload kmod) will be very beneficial to the performance of OpenVPN tunnels and cpu usage for users :)

2023-08-11 05:10 UTC, closed without merging