net/iodine: enhance uci configuration
openwrt/packages pull request #21465
Opened 2023-06-28 21:19 UTC by Tabiskabis

Maintainer: Uwe Kleine-König <uwe+openwrt@kleine-koenig.org>
Compile tested: x86_64, Debian bookworm, OpenWrt 23.05.0-rc1
Run tested: x86_64, QEMU, OpenWRT 23.05.0-rc1: Tested start & stop functions

Description:
 * apply more arguments/options via init script
 * include enhanced config file w/ annotations
 * very small chance to breaking previous configs, since address no longer defaults to '0.0.0.0'
  iodined provides its own mechanism to do pretty much the same thing, which should be preferred
  iodined defaults to using port 53 if not specified

2023-06-29 07:39 UTC, feckert reviewed
While we are at it, refactor the init script.
We should also port it to the PROCD?

And please use the following pattern to add arguments on service start.
```
procd_open_instance
procd_set_param command /usr/sbin/iodined
[ -n "$password" ] && procd_append_param command -P "$password"
[ -n "$address" ] && procd_append_param command -l "$address"
[ -n "$port" ] && procd_append_param command -p "$port"
...
procd_set_param respawn
procd_close_instance


```

2023-06-29 20:59 UTC, Tabiskabis commented
> While we are at it, refactor the init script. We should also port it to the PROCD?
This is what you meant, i suppose? Great susggestion.
It'll probably also solve an issue where the process dies because DHCP or something.

2023-06-30 07:00 UTC, feckert requested changes
Looks good.

Could you also add the following lines to the init script:
```
service_trigger() {
	procd_add_reload_trigger iodined
}
```
So the service gets restarted on a config change.

2023-07-01 14:32 UTC, Tabiskabis commented
> Could you also add the following lines to the init script:
> ...
> So the service gets restarted on a config change.

This, plus I've added the ability to handle named instances, too.

2023-07-03 07:40 UTC, feckert requested changes
Unfortunately, I overlooked that in the review. But can you also please bump the PKG_RELEASE number by one?
https://github.com/openwrt/packages/blob/master/net/iodine/Makefile#L12

2023-07-03 17:51 UTC, Tabiskabis commented
> ... can you also please bump the PKG_RELEASE number by one? 

I should mention that I opened a [pull request to update iodine to v0.8](21403) (appears stuck) about a week before this one.
This being my first contribution to OpenWRT, I wasn't sure how long things take and whether they get acceptet at all.
Should I have merged this requestion into the other one, instead?

2025-12-15 17:16 UTC, GeorgeSapkin commented
@Tabiskabis still relevant? If so, there are merge conflicts and you can't use GitHub noreply email.

2026-06-05 08:52 UTC, closed without merging