Easyloggingpp: Add package
openwrt/packages pull request #21516
Opened 2023-07-08 16:38 UTC by VolkerChristian

Maintainer: me@vchrist.at
Compile tested: OpenWRT-23.05-rc2, arm_cortex-a7_neon-vfpv4, mips_24kc
Run tested: arm_cortex-a7_neon-vfpv4 (Linksys MR8300), mips_24kc (tplink_archer-a7), OpenWrt 23.05-rc2)

Description:
Easylogging++ is single header efficient logging library for C++ applications. It is extremely powerful, highly extendable and configurable to user's requirements.

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2023-07-15 17:37 UTC, 1715173329 requested changes
And I noticed the latest release was updated about 3 years ago, is it really active?

2023-07-15 17:37 UTC, 1715173329 commented on libs/easyloggingpp/Makefile
> +PKG_MIRROR_HASH:=9acdb77ca418b07feef4ffc4ae1858c0a11f9e44c44a0eff21d3e278844e4dc1
use codeload instead, for example:
https://github.com/openwrt/packages/blob/1cb2590c1743eeb4c357b1f0d7e3fb47b3640ae6/utils/yq/Makefile#L7-L9

2023-07-15 17:37 UTC, 1715173329 commented on libs/easyloggingpp/Makefile
> +PKG_LICENSE_FILES:=LICENSE
```suggestion
PKG_MAINTAINER:=Volker Christian <me@vchrist.at>
PKG_LICENSE:=MIT
PKG_LICENSE_FILES:=LICENSE
```

2023-07-15 17:37 UTC, 1715173329 commented on libs/easyloggingpp/Makefile
> +PKG_BUILD_DEPENDS:=toolchain
```suggestion
CMAKE_INSTALL:=1
```

- toolchain is always built, no need to specify
- use CMAKE_INSTALL to simplify InstallDev

2023-07-15 17:37 UTC, 1715173329 commented on libs/easyloggingpp/Makefile
> +
```suggestion
```

CMAKE_INSTALL does it already

2023-07-17 14:22 UTC, VolkerChristian commented
Thank you for the hint to use codeload and CMAKE_INSTALL! I have updated the pull request accordingly.

As for the activity of the project: Upstream has at least made some commits two month ago. But you are right - there is no new release since two and a half year ago.
Nevertheless, the software I want to bring to OpenWRT ([SNode.C](https://github.com/VolkerChristian/snode.c) and [MQTTBroker](https://github.com/VolkerChristian/mqttbroker)) relies heavily on easyloggingpp.

2023-07-18 13:18 UTC, 1715173329 approved these changes
otherwise LGTM - Thanks!

2023-07-18 13:18 UTC, 1715173329 commented on libs/easyloggingpp/Makefile
> +PKG_SOURCE_DATE:=2020-12-25
```suggestion
```
unused variables

2023-07-20 06:52 UTC, merged