librespeed-go: Reload the daemon after modifying the tls certificate
openwrt/packages pull request #22345
Opened 2023-10-09 02:17 UTC by muink

Maintainer: Tianling Shen cnsztl@immortalwrt.org @1715173329 
Compile tested: x86_64, x86/64, 22.03.5
Run tested: x86_64, x86/64, 22.03.5

Description:
Make the daemon reload after the tls certificate is updated

2023-10-09 03:34 UTC, 1715173329 requested changes
Please:
- Drop unnecessary description from your commit message
  `Make the daemon reload after the tls certificate is updated.` is enough
- Use a valid email address

2023-10-09 03:34 UTC, 1715173329 commented on net/librespeed-go/files/librespeed-go.init
> +	fi
```suggestion
	[ "$refresh" = "0" ] || procd_append_param file "$value"
```

btw i'd prefer `reload` over `refresh`

2023-10-09 06:37 UTC, 1715173329 approved these changes

2023-10-09 09:06 UTC, BKPepe commented
Requires to bump PKG_RELEASE in the Makefile.

2023-10-11 01:40 UTC, merged

2023-10-11 01:40 UTC, 1715173329 commented
Merged, thank you!