ddns-scripts: add new DDNS provider ipnodns.ru
openwrt/packages pull request #22371
Opened 2023-10-11 12:16 UTC by IgorBai

This is addition to #22237. I work directly from Chrome. Hope this online commit would be satisfactory. 
OS version: OpenWrt 23.05.0-rc4 r23482-7fe85ce1f2
ddns-scripts version 2.8.2-37

Subitted file has been working smoothly for about 2 weeks. Regards

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2023-10-11 14:44 UTC, BKPepe commented
Don't open new pull requests, if you have a previous one. Contributions via GitHub Web UI perfectly works even do I tried it once via my phone to commit such changes. 

Anyway, you need to bump PKG_RELEASE in the Makefile, squash the commits, rebase it and then force push it to get rid of merge commit.

2023-10-16 09:37 UTC, feckert requested changes
Sorry!
You also need to ad this ddns provider to this line https://github.com/openwrt/packages/blob/master/net/ddns-scripts/files/usr/share/ddns/list

2023-10-16 09:37 UTC, feckert commented on net/ddns-scripts/files/usr/share/ddns/default/ipnodns.ru.json
> +}
Missing new line.

2023-10-17 06:50 UTC, feckert commented
Ok the code is now correct. But you have add a Signed-off-by to your work. Please have a look to the other commits in this repository.
```
git commit --amend -s 
git push --force
```

2023-10-18 07:13 UTC, feckert commented
Sorry I know it is boring! But we still have a problem with this pullrequest, that blocks merging.
The mail address of the line `Signed-off-by` in the commit is still not correct.
`Signed-off-by: Igor Baidasov <C:\Users\igorb\AppData\Roaming\The Bat!>`
Please update your git config with a valid mail address and your rael name, then you could use `git commit -s`. This will add a valid `Sigend-off-by` to your commit.
Every thing else looks fine.

2023-10-18 08:58 UTC, feckert approved these changes

2023-10-18 09:13 UTC, BKPepe commented
Still formality CI fails

2023-10-18 09:57 UTC, feckert commented
@BKPepe The commit message is fine. But the `Author:`  is not the same as at `Signed-off-by`.
@IgorBai Do you have set the correct values in your git config file?

Output of git log:
```
Refs: [pr/upstream-22371]
Author:     Igor Baidasov <none>
AuthorDate: Sat Oct 14 16:02:21 2023 +0300
Commit:     Igor Baidasov <igorbay@bk.ru>
CommitDate: Wed Oct 18 11:35:17 2023 +0300
```
 But I think the commit is wrong in git.
@IgorBai

2023-10-18 11:09 UTC, feckert commented
Now everything fits :+1:
Thanks for your contribution!

2023-10-18 11:09 UTC, merged