strongswan: add eap-dynamic plugin
openwrt/packages pull request #22475
Opened 2023-10-22 08:13 UTC by tarvip

Maintainer: @pprindeville @Thermi
Compile tested: x86_64, 23.05.0
Run tested: x86_64, 23.05.0, configured the `eap-dynamic` as authentication method for a connection. Native Mac VPN client connected using `eap-tls`, while Android phone native VPN client is using `eap-mschapv2`.

```
# swanctl --stats
uptime: 2 hours, since Oct 22 09:03:55 2023
worker threads: 16 total, 11 idle, working: 4/0/1/0
job queues: 0/0/0/0
jobs scheduled: 0
IKE_SAs: 0 total, 0 half-open
loaded plugins: charon aes des rc2 sha2 sha1 md4 md5 mgf1 random nonce x509 revocation constraints pubkey pkcs1 pgp dnskey sshkey pem openssl fips-prf gmp xcbc hmac attr kernel-netlink resolve socket-default connmark vici updown eap-identity eap-mschapv2 eap-dynamic eap-tls xauth-generic
```

Description:

This plugin acts as a proxy that dynamically selects an EAP method that is supported/preferred by the client. If the original EAP method initiated by the plugin is rejected with an EAP-NAK message, it will select a different method that is supported/requested by the client.

For example it is possible to configure eap-tls as preferred authentication method for your connection while still allow eap-mschapv2.

2023-10-23 05:12 UTC, pprindeville requested changes
Needs a PKG_RELEASE bump on line 12.

2023-10-23 06:58 UTC, tarvip commented
> Needs a PKG_RELEASE bump on line 12.

Fixed

2023-10-29 08:36 UTC, BKPepe approved these changes

2023-11-04 18:56 UTC, pprindeville approved these changes

2023-11-04 18:56 UTC, merged

2023-11-04 18:57 UTC, pprindeville commented
Merged.  Thanks!