Wavemon: bump to latest
openwrt/packages pull request #22482
Opened 2023-10-23 10:39 UTC by xback

Maintainer: me / @neheb 
Compile tested: ipq40xx / OpenWRT Master
Run tested: ipq40xx / OpenWRT Master

Description:
This series bumps wavemon which is currently broken today.
The main reason for this is being out of sync with current supported mac80211 stack.
Each call ends in "no supported wireless interfaces found!"

This bump makes the package fully working again.

2023-10-24 07:20 UTC, trippleflux commented
Failed on my build-host, debian testing : 
```
./config.status
config.status: creating Makefile
 CC   about_scr.c
 CC   conf.c
 CC   conf_scr.c
 CC   error.c
 CC   help_scr.c
 CC   info_scr.c
 CC   iw_if.c
 CC   iw_nl80211.c
 CC   iw_scan.c
 CC   lhist_scr.c
lhist_scr.c: In function 'hist_plot':
lhist_scr.c:194:66: error: 'WACS_HLINE' undeclared (first use in this function); did you mean 'ACS_HLINE'?
  194 |                 mvwadd_wch(w_lhist, hist_y(level), hist_x(xval), WACS_HLINE);
      |                                                                  ^~~~~~~~~~
      |                                                                  ACS_HLINE
lhist_scr.c:194:66: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [Makefile:35: lhist_scr.o] Error 1
```

Any clues?

2023-10-24 07:41 UTC, xback commented
> Any clues?

Smells like a ncurses issue
I'll try to simulate

Thanks for testing!

2023-10-24 07:51 UTC, xback commented
@trippleflux 

Can you confirm that you've tested this on a fresh new master build?

2023-10-24 08:01 UTC, trippleflux commented
You are correct, my env variables seems to be too dirty being left over from various successful built.
Now managed to compile, really sorry for the false alarm, that's why I was so confused.

2023-10-24 08:06 UTC, xback commented
No worries.
Better safe than sorry 👍 

Thanks again for spending time testing this!

2023-10-26 10:46 UTC, xback commented
@BKPepe 
Can you merge this one please?  Look like @neheb is MIA :)

Thanks

2023-10-29 08:30 UTC, BKPepe requested changes
I can not merge this as it is, I am so sorry. 

For 1st commit:
 - Please avoid  copy&pasting Git hashes and their commit subjects, etc.
     It's not necessary and as you can see, it references commits here, which makes is misleading.
 There is no reason to do it like this, when upstream creates tagged releases and take their time to write changelog. You can see it here https://github.com/uoaerg/wavemon/releases/tag/v0.9.4 and that's what should be in the commit description.
 
 All these changes which are you saying are not relevant to the Makefile itself as it is usual update.
 
 - Describe why we need to have additional dependencies.
 
 For 2nd commit:
 - Woah, so many patches. They can not tag a new release?
 - Do we really need to have every patch, which you backported? It will stay in the history forever. We don't need the patch, which updates readme, right?

2023-10-29 08:30 UTC, BKPepe commented on net/wavemon/Makefile
> +  DEPENDS:=+libncurses +libpthread +libnl-genl +libnl-route +libnl-nf +libnl-cli
So many dependencies were added and there wasn't anything about this in the commit description

2023-10-30 11:48 UTC, xback commented
@BKPepe 
Thanks for your time reviewing this.
Highly appreciated :-)

Wavemon is not heavily developed anymore, as it 'Just Works' in the curent state .. and it has been more than 2 years already since the last tag to 0.9.4

What would you prefer?
- Just update to 0.9.4 and ignore newer fixes
- Wait for a 0.9.5 (I asked for it actively, but highly unlikely)
- Reduce custom patches? (like omitting the readme update)
- switch from tag pointing to commit pointing so we can just update based on commit?

Thanks again

2023-10-30 15:28 UTC, xback commented
@BKPepe 
The author has agreed to bump the version tonight.
I'll update this PR tomorrow then :-)

2023-10-30 16:17 UTC, BKPepe commented
Woah, that's great news!

Dne po 30. 10. 2023 16:28 uživatel Koen Vandeputte ***@***.***>
napsal:

> @BKPepe <https://github.com/BKPepe>
> The author has agreed to bump the version tonight.
> I'll update this PR tomorrow then :-)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/22482#issuecomment-1785466295>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVAOGY44PZNRMN4D5JDYB7BSFAVCNFSM6AAAAAA6L3ISFOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBVGQ3DMMRZGU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-31 09:12 UTC, BKPepe commented
We are again spamming inrelevant things caused by including Git hashes in the commit description, so it is really fine to put there link for changelog(s). It looks simple, readable and the commit description should contain only changes relevant to its Makefile.

2023-10-31 09:18 UTC, xback commented
@BKPepe
should be ok now .. i hope :)

2023-10-31 09:29 UTC, BKPepe approved these changes

2023-10-31 09:29 UTC, BKPepe commented
You did it! 👏 👏 

Looks good. Thank you so much!

2023-11-01 16:32 UTC, merged