owntone: Update to 28.8
openwrt/packages pull request #22523
Opened 2023-10-28 07:38 UTC by ejurgensen

Maintainer: me
Compile tested: x86, VM, OpenWrt trunk
Run tested: x86, VM, OpenWrt trunk

Description:
Update to 28.8

2023-10-28 19:15 UTC, BKPepe commented
Link to changelog, please

2023-10-28 22:49 UTC, ejurgensen commented
Sure: [ChangeLog](https://raw.githubusercontent.com/owntone/owntone-server/master/ChangeLog)

2023-10-29 08:32 UTC, BKPepe requested changes
Please stop slipping changes, which are not from upstream. Your commit subject as there is no commit description, not even in the pull request mentioned. 

This looks like usual update on the first sight and then you are enabling some stuff and no one knows why and it is not even in their changelog: https://github.com/owntone/owntone-server/releases/tag/28.8

2023-10-29 08:32 UTC, BKPepe commented on sound/owntone/Makefile
> +	+libevent2 +libevent2-pthreads +libdaemon +confuse +alsa-lib +libffmpeg-full \
Why do we need new dependency?

2023-10-29 08:32 UTC, BKPepe commented on sound/owntone/Makefile
> -	--without-libevent_pthreads
Why do you need to have it enabled?

2023-10-29 09:12 UTC, ejurgensen commented
> Please stop slipping changes

What do you mean by "stop slipping changes"? Is this something I have done before? I have added the "libevent2-pthreads" dependency simply because the build failed without it. That's all there is to it.

Maybe it's not your intent, but your feedback comes of as somewhat hostile. I am just keeping the package updated - as I suppose the primary duty of a maintainer is. I don't have ulterior motives by adding the dependency. What would they even be?

I get a bunch of PRs myself, and I understand the dread that can come with it, but remember that people are just trying to help.

2023-10-30 17:22 UTC, BKPepe commented
>  I have added the "libevent2-pthreads" dependency simply because the build failed without it. That's all there is to it.

Was it working previously without it? I can see that owntone is sucessfully compiled on OpenWrt buildbots, thus there is something wrong.

2023-10-30 20:40 UTC, Torxgewinde commented
Probably it is obvious to everyone, but to make sure i'd like to point out it is the main owntone author that is also maintaining the OpenWRT package here.

2023-10-31 00:47 UTC, ejurgensen commented
> Was it working previously without it? I can see that owntone is sucessfully compiled on OpenWrt buildbots, thus there is something wrong.

The dependency came in version 28.7, so that's why 28.5 can be built without. The changelog doesn't directly say it, but it is part of the "drop support for libevent < 2.1.4", ref. [this PR](https://github.com/owntone/owntone-server/pull/1576): "Support for libevent < 2.1.4 has been removed, and libevent pthreads is now a hard requirement." The configure option `--without-libevent_pthreads` also no longer exists.

2023-10-31 08:04 UTC, BKPepe commented
Okay, this one should be copy&pasted to the commit description.

Dne út 31. 10. 2023 1:47 uživatel ejurgensen ***@***.***>
napsal:

> Was it working previously without it? I can see that owntone is
> sucessfully compiled on OpenWrt buildbots, thus there is something wrong.
>
> The dependency came in version 28.7, so that's why 28.5 can be built
> without. The changelog doesn't directly say it, but it is part of the "drop
> support for libevent < 2.1.4", ref. this PR
> <https://github.com/owntone/owntone-server/pull/1576>: "Support for
> libevent < 2.1.4 has been removed, and libevent pthreads is now a hard
> requirement." The configure option --without-libevent_pthreads also no
> longer exists.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/22523#issuecomment-1786262981>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVFGHZO6SQ3LXQ5SEFLYCBDBBAVCNFSM6AAAAAA6T4LSZKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOBWGI3DEOJYGE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-01 09:25 UTC, ejurgensen commented
Ok, I have amended the commit message now

2023-11-01 22:56 UTC, merged