freeradius3: fix compile errors for pcre2
openwrt/packages pull request #22532
Opened 2023-10-29 16:05 UTC by crza

PCRE2 fix https://github.com/openwrt/packages/issues/22006

Maintainer: @odmdas / @neheb
Compile tested: compile & run tested on mediatek unifi-6-lr-v1 with musl openwrt 23.05
Run tested: compile & run tested on mediatek unifi-6-lr-v1 with musl openwrt-23.05 with sample configuration

Description:
libpcre is not available, compile fails. fix this by using libpcre2 instead.

2023-10-29 20:26 UTC, BKPepe commented
Formality check is failing for you:
```
=== Checking commit '17f45bf5a6c26f8b860e946b8ef6f01370554845'
: Author name (crza) need to be your real name 'firstname lastname'
: Commit subject line seems ok (freeradius3: fix compile errors for pcre2)
: Signed-off-by is missing or doesn't match author (should be 'Signed-off-by: crza <crza@users.noreply.github.com>')
```

2023-10-29 21:29 UTC, crza commented
should be fixed.

2023-10-30 17:07 UTC, BKPepe requested changes
Excuse me, but I don't understand the pull request description.

> libpcre is not available, compile fails. fix this by using libpcre2 instead.

What?  Do you have any output for those compile errors, which you mention?

Freeradius is actually correctly build and there are [no faillogs](https://downloads.openwrt.org/snapshots/faillogs/aarch64_cortex-a53/)

____

Then I am going back to your commit. Commit subject was said above.
Commit description should be imho revised. Please see it here: https://openwrt.org/submitting-patches
Use PCRE2, its okay, but it does not say why... which is important part here.

2023-10-30 18:20 UTC, crza commented
well ...
after repeating my steps from saturday (with fresh pulls from openwrt-23.05 branches) there is one difference in .config today (with a successful build): CONFIG_PACKAGE_libpcre=y exists, which was missing in saturdays .config

I will amend my commit & PR.

2023-10-30 20:42 UTC, BKPepe commented
Much better. :clap:

2023-10-30 21:01 UTC, merged

2023-11-06 12:26 UTC, clutch2sft commented
19ec302 also breaks [aarch64_cortex-a53](https://downloads.openwrt.org/releases/faillogs-23.05/aarch64_cortex-a53/)
![image](https://github.com/openwrt/packages/assets/25586286/e4ca2bb5-8918-432a-9c8a-611352f0baed)

2023-11-06 12:29 UTC, BKPepe commented
We know, we are working to fix it soon.

Dne po 6. 11. 2023 13:27 uživatel clutch2sft ***@***.***>
napsal:

> 19ec302
> <https://github.com/openwrt/packages/commit/19ec30255f1379cb2d25f7ace22523039cc8aa67>
> also breaks aarch64_cortex-a53
> <https://downloads.openwrt.org/releases/faillogs-23.05/aarch64_cortex-a53/>
> [image: image]
> <https://user-images.githubusercontent.com/25586286/280705429-e4ca2bb5-8918-432a-9c8a-611352f0baed.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/22532#issuecomment-1794709330>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVCFM2CBM3ASUXGAP73YDDJRPAVCNFSM6AAAAAA6U55656VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJUG4YDSMZTGA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-06 12:53 UTC, clutch2sft commented
@DKPepe Thank you.  I wasn't sure from reading the thread about the broad nature of the problem.  And thank you for working diligently to resolve it.  I also have a question if I may about the mechanics of this.

In my world a release is a point in time and it is never changed.  So 23.05.0 wouldn't revieve such change and it would come in the next stable release.  Indeed I see the commit was made to the master.  How did it get back-ported to the release?  To be clear this isn't a critisism - just a way to clarify my understanding of the release strategy for ongoing use.

2023-11-17 05:06 UTC, jefferyto commented
The build error was fixed in #22666 (#22670 for 23.05).