libsocketcan: new package
openwrt/packages pull request #22726
Opened 2023-11-22 08:48 UTC by yegorich

Readd and update the libsocketcan package from OpenWrt 14.07:

https://git.archive.openwrt.org/?p=14.07/packages.git;a=blob;f=libs/libsocketcan/Makefile;hb=a2d1927140548a805970f0859150556ea0b22a78

Maintainer: @yegorich 
Compile tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2
Run tested: ARMv7, TI Sitara AM335x, OpenWrt v23.05.2, tested with internal software

Description:

2023-11-22 09:08 UTC, yegorich commented
I have preserved the original copyright notice. Should I also add myself as a maintainer?

2023-11-22 09:27 UTC, BKPepe commented
It is not clear for me, why do we need to add this package to our repository. No one wanted it in the past and now suddenly, there is request. Since this was tested with internal software, can not you keep it in your own feed?

2023-11-22 09:30 UTC, BKPepe requested changes
A few things, which I spotted on.

2023-11-22 09:30 UTC, BKPepe commented on libs/libsocketcan/Makefile
> +PKG_MD5SUM:=958bc8e2841f73828013132320acb294
This is deprecated hash.

2023-11-22 09:30 UTC, BKPepe commented on libs/libsocketcan/Makefile
> +PKG_LICENSE:=LGPL-2.1
Outdated SPDX License Identifier

2023-11-22 09:30 UTC, BKPepe commented on libs/libsocketcan/Makefile
> +  TITLE:=libsocketcan
This title is not sufficient

2023-11-22 14:40 UTC, yegorich commented on libs/libsocketcan/Makefile
> +PKG_LICENSE:=LGPL-2.1
Fixed

2023-11-22 14:40 UTC, yegorich commented on libs/libsocketcan/Makefile
> +  TITLE:=libsocketcan
Fixed

2023-11-22 14:52 UTC, yegorich commented
First of all, this is a well known and stable project. It is packaged in many Linux distros like Debian, Fedora, Buildroot, etc.

AFAIK, we have used http://git.openwrt.org/packages.git feed for libsocketcan, and now I update the whole project and saw that the package is missing.

2023-11-24 08:09 UTC, yegorich commented
I have added myself as a maintainer and also fixed the PR description.

2023-12-01 19:27 UTC, merged

2023-12-02 07:55 UTC, yegorich commented on libs/libsocketcan/Makefile
> +include $(INCLUDE_DIR)/package.mk
Will do.