syncthing: fix duplicate command line parameters on service
openwrt/packages pull request #22767
Opened 2023-11-27 14:54 UTC by efahl

Maintainer: @BKPepe 
Compile tested: none
Run tested: linksys_e8450-ubi aarch64_cortex-a53

Description:
Fixes issue #22760, duplicate command line options at service startup.

2023-12-04 06:53 UTC, jefferyto requested changes
* `PKG_RELEASE` needs to be incremented
* Please indicate in the commit message that this fixes 9d17ba1a9387efdc08e236d4eaa937eb103472f4 and #22760

2023-12-09 10:51 UTC, jefferyto approved these changes
Thanks!

2023-12-09 10:51 UTC, merged

2023-12-09 10:54 UTC, jefferyto commented
I think this is relevant for 23.05? Perhaps you can backport this for the openwrt-23.05 branch?

2023-12-09 16:23 UTC, efahl commented
Yes, I believe the OP for this issue on the forums was running release code (maybe even 22.03).

What's the backport procedure?   In my repo, after syncing up to master, do something like this???

git checkout openwrt-23.05
git cherry-pick ec0ea77
git commit -m "syncthing: Backport issue #22760"
git push

2023-12-10 06:04 UTC, jefferyto commented
> What's the backport procedure? In my repo, after syncing up to master, do something like this???

Basically yes. In particular:

* Create a new branch based on openwrt-23.05
* Cherry-pick, I suggest using the `-x` option
* Can use the default commit message (from the cherry picked commit)

2023-12-10 17:34 UTC, efahl commented
Not sure I've got it right, the `commit:` line in the log doesn't show `(origin/openwrt-23.05...` like in ansuel's commit...  Is that expected, or did I branch it wrong, or ???
```
git checkout openwrt-23.05
git checkout -b backport-22760 openwrt-23.05
git cherry-pick -x -m 1 ec0ea77
- fix Makefile conflict in PKG_VERSION
git commit
git log -n2

commit 1621adf95be064383a708f09e4c2ac36a4debef4 (HEAD -> backport-22760)
Author: Jeffery To <jeffery.to@gmail.com>
Date:   Sat Dec 9 18:51:30 2023 +0800

    Merge pull request #22767 from efahl/issue-22760

    syncthing: fix duplicate command line parameters on service
    (cherry picked from commit ec0ea779279f9a0cabdbf6deaa6339d7431bb707)

commit 42cf7d0ed90b723f85a4737fe65f06c640343ed9 (origin/openwrt-23.05, openwrt-23.05)
Author: Christian Marangi <ansuelsmth@gmail.com>
```

2023-12-11 03:05 UTC, jefferyto commented
You need to cherry pick your commit (6849a9d) not the merge commit (ec0ea77).

2023-12-11 15:57 UTC, efahl commented
Ok, did that, now the commit message looks better, but still the commit line is showing HEAD instead of `openwrt-23.05`?

```
$  git log --oneline --graph -n5
* 0c2471b5c (HEAD -> backport-22760) syncthing: fix duplicate command line parameters on service
* 42cf7d0ed (origin/openwrt-23.05, openwrt-23.05) nginx: don't install all module for FULL variant
*   74b54c63a Merge pull request #21494 from jefferyto/python-typing-extensions-4.7.1-openwrt-23.05
|\
| * a10054900 python-typing-extensions: Update to 4.7.1
* | e0c713717 rclone: Update to 1.63.0
```

2023-12-11 16:04 UTC, jefferyto commented
> Ok, did that, now the commit message looks better, but still the commit line is showing HEAD instead of openwrt-23.05?

`HEAD` points to the tip of the current branch: https://stackoverflow.com/questions/2304087/what-is-head-in-git

2023-12-11 18:15 UTC, efahl commented
Read through the SO article, and since I created the branch on 23.05, I guess it's ok.  So I pushed it, created the PR and it's somehow grabbed 194 commits and wants to merge all that into master...