lvm
openwrt/packages pull request #22843
Opened 2023-12-08 11:54 UTC by sah-cdo

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

2023-12-08 16:17 UTC, dangowrt commented
Imho we don't need variants with readline. We don't need a fully-featured interactive CLI, it's enough to use lvm inside normal shell and for that we don't need readline.

2023-12-18 22:25 UTC, BKPepe requested changes
1. Squash commits
2. In the commit description, there should be reason, why libreadline was removed.
3. Of course, while adding/removing dependencies, then there should be release bump.

2024-02-07 13:28 UTC, sah-cdo commented
@BKPepe : could you provide a feedback on this MR?

2024-10-14 14:05 UTC, Rondom approved these changes
LGTM

2024-10-19 01:16 UTC, dangowrt commented
You should still add `--disable-readline` to CONFIGURE_ARGS, so libreadline won't picked up during build in case it is present.

2025-01-31 10:16 UTC, Matthiasfranck commented
Hi @BKPepe @Rondom @dangowrt, all comments are fixed and I think we should be good to go now :)

2025-12-15 16:55 UTC, GeorgeSapkin commented
@sah-cdo still relevant? If so there are merge conflicts.

2026-07-05 06:14 UTC, dangowrt commented
Superseded by 2a1e7734ed055a3107d673f3d147c0031ded532f

2026-07-05 06:14 UTC, closed without merging