libs/gpgme/Makefile: fix licence
openwrt/packages pull request #22860
Opened 2023-12-10 20:57 UTC by ffontaine

gpgme license is wrong since the addition of the package in commit https://git.openwrt.org/?p=feed/packages.git;a=commit;h=3e39633b75e7d26f3666bce9c2e97d268f0fd068

Indeed, gpgme has been licensed under LPGL-2.1+ since version 1.0.2 back in 2004 [1]:

```
Noteworthy changes in version 1.0.2 (2004-12-28)
------------------------------------------------

 * Changed the license of the library to the GNU Lesser General Public License (LGPL), version 2.1 or later.
```

[1] https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob;f=NEWS;h=2475a877a40817f575accd22a386bfd5f0a66aad;hb=HEAD

Maintainer: @dangowrt
Compile tested: Not needed
Run tested: Not needed

2023-12-10 21:04 UTC, neheb approved these changes

2023-12-18 22:05 UTC, BKPepe requested changes
1. Commit subject should be like: ``gpgme: Fix license``, we dont need to specify the category which is Library.

2023-12-19 06:45 UTC, ffontaine commented
PR updated

2023-12-19 08:46 UTC, BKPepe approved these changes

2023-12-20 02:52 UTC, merged

2023-12-20 02:52 UTC, 1715173329 commented
Merged, thank you!