snort3: compile with lzma support
openwrt/packages pull request #22908
Opened 2023-12-17 11:14 UTC by graysky2

Add lzma support for decompression of swf and pdf files

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

Maintainer: me and @flyn-org

2023-12-17 12:18 UTC, graysky2 commented
Recommend merge.

2023-12-18 20:36 UTC, BKPepe commented
> Recommend merge.

?? :-) You created PR and you recommend it to merge, right? Did I understand it, right? 😆

2023-12-18 21:10 UTC, graysky2 commented
I did not realize I had direct commit abilities.  Thought someone else had to do it.

2023-12-18 21:37 UTC, graysky2 commented
@BKPepe - do permissions need to be granted for me to commit?

```
% git push
ERROR: Permission to openwrt/packages.git denied to graysky2.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

And
```
% cat .git/config
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = git@github.com:openwrt/packages.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

2023-12-18 21:51 UTC, BKPepe commented
I think we are still not understanding each other. Of course, commit rights
needs to be granted and it needs to be deserved. My point was something
entirely different.

You created PR and the same person, who created PR recommeds his changes to
be merged. Thats quite obvious, isnt it? Your comment is really pointless
and the second maintainer should write it. Not you.

Dne po 18. 12. 2023 22:37 uživatel graysky ***@***.***>
napsal:

> @BKPepe <https://github.com/BKPepe> - do permissions need to be granted
> for me to commit?
>
> % git push
> ERROR: Permission to openwrt/packages.git denied to graysky2.
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.
>
> And
>
> % cat .git/config
> [core]
> 	repositoryformatversion = 0
> 	filemode = true
> 	bare = false
> 	logallrefupdates = true
> [remote "origin"]
> 	url = ***@***.***:openwrt/packages.git
> 	fetch = +refs/heads/*:refs/remotes/origin/*
> [branch "master"]
> 	remote = origin
> 	merge = refs/heads/master
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/22908#issuecomment-1861715166>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVD75LFSN5S3ANFNWS3YKCZRBAVCNFSM6AAAAABAYI5GHKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNRRG4YTKMJWGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-12-18 21:56 UTC, graysky2 commented
Thank you for the clarification. @flyn-org - can you please review?

2023-12-18 22:01 UTC, BKPepe requested changes
In the commit description, we got why do you need lzma support, but we need more details. Why it should be enabled by default? What is the size difference, etc? 

Shouldn't it be done rather as configuration option (e.g. similarly done as Config.in)?

2023-12-19 11:29 UTC, graysky2 commented
@BKPepe - I think I addressed your questions in the commit message.  As to your configuration option question, I think this represents the most straight-forward implementation.  Perhaps @flyn-org can comment on that point.

2023-12-20 10:31 UTC, BKPepe approved these changes

2024-01-02 23:29 UTC, merged