s/http:/https: for some PKG_SOURCE_URLs
openwrt/packages pull request #23098
Opened 2024-01-14 14:40 UTC by dcousens

**Maintainer:** N/A
**Compile tested:** N/A
**Run tested:** N/A

**Other**
I have opened the changed hosts and verified that HTTPS is supported, many are not configured properly and have been omitted from this pull request.

### Description:
(~copy of https://github.com/openwrt/openwrt/pull/10799)
This pull request changes a number of `PKG_SOURCE_URL`s that were using `http:`, to use `https:` if they were available.

I understand that this doesn't impact the integrity of the downloaded package, as `PKG_HASH` is for that purpose.
None-the-less, this is a beneficial change as HTTPS is the modern baseline.

2024-02-14 13:50 UTC, dcousens commented
Happy to rebase if necessary

2024-02-18 10:34 UTC, mhei requested changes
You should rebase and squash into a single commit with proper description etc and then force push to this PR. See contribution hints for details.

2024-02-18 11:48 UTC, dcousens commented
Rebased and squashed, I don't necessarily know what description that is wanted, as this touches a number of different packages.

2024-02-19 06:46 UTC, mhei commented
Yes, since it covers multiple packages, the first rule (prefixed package name) cannot apply here.
Let's just ignore it, don't use boilerplate like the star.

For the proper commit message, we can re-use wording from your PR. The following example is short and should be completely sufficient:

```
Use https for some PKG_SOURCE_URLs 

This changes a number of PKG_SOURCE_URLs that were using http:, to use https: if they were available.
It was verified that HTTPS is supported properly for the updated hosts.

Signed-off-by: ...
```

The SoB is missing in your commit, see https://github.com/openwrt/packages/blob/master/CONTRIBUTING.md#commits-in-your-pull-requests-should for details.

2024-02-19 10:26 UTC, dcousens commented
Thanks @mhei, I'll try and update everything this week

2024-10-28 07:48 UTC, BKPepe commented
Kind reminder.

2024-10-28 12:31 UTC, dcousens commented
Thanks @BKPepe, I will attempt to rebase this and re-sign soo

2024-11-11 09:39 UTC, dcousens commented
@BKPepe should be OK to go now

2025-05-13 11:22 UTC, closed without merging

2025-06-15 15:45 UTC, BKPepe commented
I am not sure, why this was closed. However, it is merged to the master branch - https://github.com/openwrt/packages/commit/8a6a3d6f5d92897cf191a12e8264e22010758113

2025-06-16 04:39 UTC, dcousens commented
Thanks @BKPepe! I didn't have time to keep the branch up to date, that's all 💙