Update etherwake-nfqueue to version 4
openwrt/packages pull request #23619
Opened 2024-03-11 08:26 UTC by 7ritn

Maintainer: Mister Benjamin / @mister-benjamin
Compile tested: x86, Manjaro Linux, OpenWRT 23.05 for ipq40xx
Run tested: ARMv7, ipq40xx, AVM FRITZ!Box 7530, OpenWRT 23.05.2, casual test with and without new mechanism

Description:
Update rewrites deprecated functions. Furthermore a defer mechanism was added which holds packets in queue until host responds, i.e., has woken up. This should prevent packets from being lost.

2024-05-28 06:15 UTC, 1715173329 requested changes
Please format your commits according to https://openwrt.org/submitting-patches#submission_guidelines.

Should have 2 commits:
1. Bump package, including adding new dependency
2. Add`defer` configuration

2024-05-28 06:15 UTC, 1715173329 commented on net/etherwake-nfqueue/Makefile
> +# Copyright (C) 2024 Mister Benjamin <144dbspl@gmail.com>
Please leave copyright as-is.

2024-05-28 06:15 UTC, 1715173329 commented on net/etherwake-nfqueue/Makefile
> +PKG_RELEASE:=4
This should be reset to `1`.

2024-05-28 06:15 UTC, 1715173329 commented on net/etherwake-nfqueue/files/etherwake-nfqueue.init
> +# Copyright (C) 2024 Mister Benjamin <144dbspl@gmail.com>
ditto

2024-06-14 14:55 UTC, 7ritn commented
> Please format your commits according to https://openwrt.org/submitting-patches#submission_guidelines.
> 
> Should have 2 commits:
> 
>     1. Bump package, including adding new dependency
> 
>     2. Add`defer` configuration

Done

2025-11-17 05:19 UTC, GeorgeSapkin commented
@7ritn is this still relevant? There are some merge conflicts.

2026-06-29 16:28 UTC, closed without merging