htop: fix dependency for lm-sensors
openwrt/packages pull request #23704
Opened 2024-03-21 09:56 UTC by graysky2

Use conditional to add libsensors depends when building htop with lm-sensors support.  Currnetly, users have to manually download libsensors in order to see the temp data.  Closes #23700.

Maintainer: @champtar

2024-03-21 09:57 UTC, graysky2 commented
@BKPepe

2024-03-21 10:31 UTC, BKPepe commented
Thanks for creating this PR. I will look at it today.

Dne čt 21. 3. 2024 10:57 uživatel graysky ***@***.***> napsal:

> @BKPepe <https://github.com/BKPepe>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/23704#issuecomment-2011791170>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVH45JY3E5M5EC3STYTYZKVJXAVCNFSM6AAAAABFBDL7JWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJRG44TCMJXGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-21 10:38 UTC, BKPepe requested changes
1. You need to change descriptipon for the config HTOP_LMSENSORS
2. Do we need to have this dependency as it was pointed out in https://github.com/openwrt/packages/issues/23700#issuecomment-2011859237 by @brada4 , we do have it also in the commit description and by looking how Debian does it - they have the dependency as suggested, not required - https://packages.debian.org/trixie/htop

Nitpick: your commit description has several typos, could you fix that? :-)

2024-03-21 10:38 UTC, BKPepe commented on admin/htop/Makefile
> +  DEPENDS:=+libncurses $(if $(CONFIG_HTOP_LMSENSORS),+libsensors)
Why so complicated? :-)

This one should work:
```suggestion
  DEPENDS:=+libncurses +HTOP_LMSENSORS:libsensors
```

Not tested, though.

2024-03-21 11:16 UTC, graysky2 commented
> You need to change description for the config HTOP_LMSENSORS

> Do we need to have this dependency as it was pointed out in https://github.com/openwrt/packages/issues/23700#issuecomment-2011859237 by @brada4 , we do have it also in the commit description and by looking how Debian does it - they have the dependency as suggested, not required - https://packages.debian.org/trixie/htop

I am confused by this statement.  If I do not have `libsensors` installed, I do not get temp data.  If `dlopen()` is a function within htop, the user still has to manually install libsensors.

> Nitpick: your commit description has several typos, could you fix that? :-)

Fixed the spelling error

2024-03-21 11:29 UTC, graysky2 commented
If I hard-code `--enable-sensors` or `--disable-sensors` into the `Makefile` the resulting binary does not change in size.  It is a constant 265720 bytes.

2024-03-21 11:32 UTC, graysky2 commented
OK so what is the intended behavior of that option in our package?  To me, if I select it in my `nconfig`, I expect the needed depends to get built and to get installed with it.  What is your expectation as to its behavior?

2024-03-21 14:32 UTC, BKPepe commented
> what is the intended behavior of that option in our package?

Keep it as it is. The dependency is optional, it is even written in the config option description in the Makefile, which you modifies. Feel free to ask htop developers.

Anyway: I dont see that you introduced my change and also the config option description is untouched.

2024-03-21 14:34 UTC, BKPepe commented
> I couldn't easily find your email address.

Hm, it should not be so hard based on this https://github.com/openwrt/packages/commits?author=BKPepe

2024-03-22 00:11 UTC, graysky2 commented
> Anyway: I dont see that you introduced my change and also the config option description is untouched. 

I did actually.  I do not understand why the changes are not reflected here.

```
% git diff HEAD~1
diff --git a/admin/htop/Makefile b/admin/htop/Makefile
index 155363106..9c5412077 100644
--- a/admin/htop/Makefile
+++ b/admin/htop/Makefile
@@ -9,7 +9,7 @@ include $(TOPDIR)/rules.mk
 
 PKG_NAME:=htop
 PKG_VERSION:=3.3.0
-PKG_RELEASE:=1
+PKG_RELEASE:=2
 
 PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
 PKG_SOURCE_URL:=https://codeload.github.com/htop-dev/htop/tar.gz/$(PKG_VERSION)?
@@ -33,7 +33,7 @@ define Package/htop
   SECTION:=admin
   CATEGORY:=Administration
   TITLE:=Interactive processes viewer
-  DEPENDS:=+libncurses
+  DEPENDS:=+libncurses +HTOP_LMSENSORS:libsensors
   URL:=https://hisham.hm/htop/
   MAINTAINER:=Etienne CHAMPETIER <champetier.etienne@gmail.com>
 endef
@@ -46,13 +46,11 @@ endef
 
 define Package/htop/config
        config HTOP_LMSENSORS
-               bool "Compile Htop with lm-sensors support"
+               bool "Enable support for reading temperature data"
                depends on PACKAGE_htop
                default y if TARGET_x86
                help
-                       Build htop with lm-sensors support.
-                       This doesn't add lm-sensors as dependency,
-                       if present it'll loaded using dlopen().
+                       This adds libsensors as dependency.
 endef
 
 CONFIGURE_ARGS += \
```

2024-03-22 00:53 UTC, brada4 commented
Present package with sensors lib optional is universally usable in container and out, you make it diverge.

2024-03-22 01:03 UTC, graysky2 commented
Should I close the PR?

On Thu, Mar 21, 2024 at 8:53 PM, Andrew ***@***.***(mailto:On Thu, Mar 21, 2024 at 8:53 PM, Andrew <<a href=)> wrote:

> Present package with sensors lib optional is universally usable in container and out, you make it diverge.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/openwrt/packages/pull/23704#issuecomment-2014123492), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AAECSJSSBCIUKO5TVBABOZTYZN6J7AVCNFSM6AAAAABFBDL7JWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMJUGEZDGNBZGI).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-03-22 01:37 UTC, brada4 commented
The literary part could explain better that th*s time we can read sensirs with libsensors. But extra dependency no no.

2024-03-22 08:29 UTC, champtar commented
https://downloads.openwrt.org/snapshots/packages/x86_64/packages/
htop is 113.4 KB
libsensors is 20.2 KB
sysfsutils is 9.3 KB

@graysky2 if the size change is minimal when can set CONFIG_HTOP_LMSENSORS default to y

2024-03-22 17:27 UTC, brada4 commented
@graysky2 change description to address your concern, like what would address your initial struggle that led you to this point.

2024-03-30 14:47 UTC, graysky2 commented
@champtar - how would you like to proceed if at all?

2024-03-31 00:35 UTC, champtar commented
(on my phone until Wednesday)
@graysky2 I would say just default CONFIG_HTOP_LMSENSORS to y so people just need to install libsensors, no need to build your own, but no need to pay the size price when you don't use it (I understand the 5k as uncompressed size, my sizes are compressed size).
I don't think APK has 'recommended' dependencies, opkg definitely does not, that would be a good solution.

2024-03-31 06:10 UTC, graysky2 commented
@champtar - I modified the PR.  Good to merge?

2024-03-31 12:01 UTC, champtar commented
@graysky2 I only see PKG_RELEASE being changed, nothing else

2024-03-31 13:36 UTC, graysky2 commented
Forgot to commit, please seen latest.  Test built as expected for me.

2024-03-31 13:58 UTC, merged

2024-03-31 14:40 UTC, brada4 commented
IMO diff summarizes intent - lmsensors supporting htop is built where sensors are likely.