vsftpd: update init script to use procd and publish service
openwrt/packages pull request #23766
Opened 2024-03-27 16:12 UTC by mhusaam

* update init script to use procd
* update init script to process UCI

Signed-off-by: Mohd Husaam Mehdi <husaam.mehdi@iopsys.eu>

2024-03-28 13:42 UTC, feckert commented
Can you please split this up in two commits.
* Switching the init to procd 
* Adding mdns
Then we could better port the procd init change to the other stable branches if we want.
These are two changes that should not be combined in one commit.

We should make the mdns handling configurable, just like we do with the [dropbear](https://github.com/openwrt/openwrt/blob/master/package/network/services/dropbear/files/dropbear.init#L356
). Not everyone wants to have mdns.

2024-04-04 14:40 UTC, mhusaam commented
Thanks for your comment. Sorry for the delay.

Mixing UCI and conf file, or, reading directly from the conf file in init script feels a little weird. This package does not have a UCI, so I will try to add UCI processing also.

2024-12-19 11:03 UTC, mhusaam commented
Hi @feckert, sorry for the delay, I finally got the time to add UCI support, and mdns is disabled by default. Kindly review.

2025-01-02 10:42 UTC, feckert requested changes
Nice work!

- See my comments.
- Can you also please bump also the PKG_RELEASE by one in this commit.
- Can you also change to tabs instead of spaces.

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +readonly TEMP_OUTPUT_CONF="/var/etc/vsftpd.conf.tmp"
I have never seen this `readonly` tag. Is this also common for the `ash` shell?

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +        value=$(echo "YES NO" | cut -d ' ' -f $((value == 1 ? 1 : 2)))
That looks kind of cryptic. Is there no better implementation for this check?
Have a look at the following implementation https://github.com/openwrt/packages/blob/master/net/miniupnpd/files/miniupnpd.init#L45

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +write_conf() {
I would also suggest to use separate function for strings boolean and numbers.

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +    : > "$TEMP_OUTPUT_CONF"  # Clear temporary file
`: >` I haven't seen that either. Does this also work with the ash?

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +    local disabled="$(uci -q get vsftpd.@global[-1].disabled)"
I would suggest to load the vsftpd function via `config_load vsftpd` at this point. So we can work with [config_get_bool](https://github.com/search?q=repo%3Aopenwrt%2Fpackages%20config_get_bool&type=code). This simplifies the validation of whether it is a boolean, as it does the mapping for us. It then no longer needs to be checked for `1` or `true`.

2025-01-02 10:42 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +    local mdns="$(uci -q get vsftpd.@global[-1].mdns)"
The same there. See my comments about `config_get_bool`

2025-01-07 07:15 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +readonly TEMP_OUTPUT_CONF="/var/etc/vsftpd.conf.tmp"
It seems to be working with busybox ash shell.

It is also in use in files like:
[net/https-dns-proxy/files/etc/init.d/https-dns-proxy
net/pbr/files/etc/init.d/pbr](https://github.com/openwrt/packages/blob/master/net/adblock-fast/files/etc/init.d/adblock-fast)
etc.

2025-01-07 08:44 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +        value=$(echo "YES NO" | cut -d ' ' -f $((value == 1 ? 1 : 2)))
I have updated to make this function logic clearer. I do not want to use config_get again because validation function already processes the values and passes them to setup_vsftpd.

2025-01-07 08:44 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +write_conf() {
Separated the boolean and non boolean functions.

2025-01-07 08:45 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +    : > "$TEMP_OUTPUT_CONF"  # Clear temporary file
It does work, but to be clear, I am updating it to use rm and touch.

2025-01-07 08:45 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +    local disabled="$(uci -q get vsftpd.@global[-1].disabled)"
Updated to use this approach.

2025-01-07 08:45 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +    local mdns="$(uci -q get vsftpd.@global[-1].mdns)"
Updated, kindly review.

2025-01-07 08:47 UTC, mhusaam commented
> Nice work!
> 
> * See my comments.
> * Can you also please bump also the PKG_RELEASE by one in this commit.
> * Can you also change to tabs instead of spaces.

Thank you for the kind words and reviewing, I have updated the PR, kindly review.

2025-01-07 09:48 UTC, feckert requested changes
See my comment.

2025-01-07 10:36 UTC, mhusaam commented on net/vsftpd/files/vsftpd.init
> +	local validation_result="$2"
Updated, kindly review.

2025-01-08 08:41 UTC, feckert requested changes

2025-01-08 08:41 UTC, feckert commented on net/vsftpd/Makefile
> +	$(INSTALL_BIN) ./files/$(PKG_NAME).uci $(1)/etc/config/$(PKG_NAME)
Its still `$(INSTALL_BIN)`.
Please change this to `$(INSTALL_DATA)` or `$(INSTALL_CONF)` have a look in the repository what is the correct makro for uci files in `/etc/config`

2025-01-08 08:41 UTC, feckert commented on net/vsftpd/files/vsftpd.init
> +		'background:bool:0' \
[If I remember correctly](https://openwrt.org/docs/guide-developer/procd-init-scripts#procd_init_scripts), then the job must not be set to background If `procd` is used. The service must run in foreground.

So I think the option `background` should not be configurable via uci . Please always set the option `background=NO` to the generated `vsftpd` config.

2025-01-08 13:22 UTC, mhusaam commented on net/vsftpd/Makefile
> +	$(INSTALL_BIN) ./files/$(PKG_NAME).uci $(1)/etc/config/$(PKG_NAME)
Updated to use $(INSTALL_CONF).

2025-01-08 13:40 UTC, merged

2025-01-08 13:41 UTC, feckert commented
Thanks for your work. Merged :+1:

2025-01-09 14:40 UTC, feckert commented
I thing you have to add a `/etc/config/vsftpd` with the following content.
```
config global
   option disabled '1'
   option conf_file "<path to your old vsftp file>
```
Please make also sure that the `background` option is set to `no`

2025-01-09 14:53 UTC, Alexey71 commented
> I thing you have to add a `/etc/config/vsftpd` with the following content.
> 
> ```
> config global
>    option disabled '0'
>    option conf_file "<path to your old vsftp file>
> ```
> 
> Please make also sure that the `background` option is set to `no`

Can you tell me where to look for this configuration file? The previous version worked immediately after installing the package....

2025-01-09 15:05 UTC, Alexey71 commented
> > hm, can we somehow detect this situation during upgrades and write a uci-defaults script that generates this config in such a case?
> 
> I'll have to see. But that could take a while.
> 
> @Alexey71 See my previous [comment](https://github.com/openwrt/packages/pull/23766#issuecomment-2580422511)

I edit `/etc/config/vsftpd`
```
config global 'global'
	option listen '1'
	option write_enable '1'
	option anonymous_enable '0'
	option local_enable '1'
	option mdns '0'
	option conf_file "/etc/vsftpd.conf"
```
The error is still there

2025-01-09 15:12 UTC, feckert commented
@mhusaam
I forgot during the review that we also have to add the following lines, otherwise the configuration will not be taken during a sysupgrade. 

```
define Package/vsftpd/conffiles
/etc/config/vsftpd
endef
```
Additional we should also add the folowing default uci config, so wie have the same behavior as before.
```
config global
   option disabled '0'
   option conf_file "/etc/vsftpd.conf"
```

> > > hm, can we somehow detect this situation during upgrades and write a uci-defaults script that generates this config in such a case?
> > 
> > 
> > I'll have to see. But that could take a while.
> > @Alexey71 See my previous [comment](https://github.com/openwrt/packages/pull/23766#issuecomment-2580422511)
> 
> I edit `/etc/config/vsftpd`
> 
> ```
> config global 'global'
> 	option listen '1'
> 	option write_enable '1'
> 	option anonymous_enable '0'
> 	option local_enable '1'
> 	option mdns '0'
> 	option conf_file "/etc/vsftpd.conf"
> ```
> 
> The error is still there

@Alexey71 Either you configure everything via uci or you only set the following uci configuration, that is starting the configuration, that is under `</etc/vsftpd.conf>` on the target.
```
config global
   option disabled '0'
   option conf_file "/etc/vsftpd.conf"
```

2025-01-09 15:30 UTC, Alexey71 commented
The problem is different. vsftpd is now unable to create the /var/run/`vsftpd` folder. I manually created a folder there and everything works until the reboot. The previous version created the folder without any problems

2025-01-09 15:48 UTC, Alexey71 commented
Fixed. Need edit `/etc/config/vsftpd` and add other path `option secure_chroot_dir '/etc/vsftpd'`
```
config global 'global'
	option listen '1'
	option write_enable '1'
	option anonymous_enable '0'
	option local_enable '1'
	option mdns '0'
	option secure_chroot_dir '/etc/vsftpd'
```

2025-01-09 22:56 UTC, BKPepe commented on net/vsftpd/files/vsftpd.init
> +BIN=vsftpd
Shouldnt we rather use hardcoded path as we do for all other packages in its init files instead of relying on (system) PATH?

2025-01-09 22:59 UTC, BKPepe commented on net/vsftpd/Makefile
> +	$(INSTALL_CONF) ./files/$(PKG_NAME).uci $(1)/etc/config/$(PKG_NAME)
Shouldnt we mark this file as conffile?

2025-01-09 23:00 UTC, BKPepe commented on net/vsftpd/Makefile
> +	$(INSTALL_CONF) ./files/$(PKG_NAME).uci $(1)/etc/config/$(PKG_NAME)
Oh, @feckert already noticed this and mention it in above in this PR.

2025-01-10 06:16 UTC, mhusaam commented
Hello, 
That's why I had added "secure_chroot_dir" option. I thought this problem had been present since before. I will add default options and address the comments. Thank you @Alexey71 for checking it out.

2025-01-10 10:32 UTC, mhusaam commented on net/vsftpd/Makefile
> +	$(INSTALL_CONF) ./files/$(PKG_NAME).uci $(1)/etc/config/$(PKG_NAME)
Yep.

2025-01-10 10:43 UTC, Alexey71 commented
@mhusaam Can you tell me what the empty /etc/vsftpd folder is created for? Maybe it is not needed at all? I don't see any files in there, it's just empty
https://github.com/openwrt/packages/pull/25720/files#diff-d5977cf9d2e8a4ce88b2f0228ecb3a4be8863c317e54f7f8e72f1b9d6d08997cR48

2025-01-10 11:06 UTC, mhusaam commented
Hi @Alexey71,

Currently it does not seem to be used practically. But it is intended for following things:
* If you place any conf files in this folder then they will be preserved over upgrades (if you choose the keep settings options). Since it is being mentioned in the vsftpd Makefile "Package/vsftpd/conffiles" section.
* It is being referred to in the default config as the place where one can keep certificate files, and userlist files.

Hope this helps.