kmsbd-tools: fix version after apk changes
openwrt/packages pull request #23784
Opened 2024-03-30 08:44 UTC by pesa1234

Solved strange package version 0~ to match apk format.

Maintainer: nobody
Compile tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25663-ce0cf80dac

Run tested: mediatek/filogic GL.iNet GL-MT6000 OpenWRT snapshot r25663-ce0cf80dac
Tested
-add new user
-mod existing user

Description:
Previous version
ksmbd-avahi-service `0~3.5.1-r1`
ksmbd-hotplug `0~3.5.1-r1`
ksmbd-server` 0~3.5.1-r1`

Actual:
ksmbd-avahi-service` 3.5.1-r2`
ksmbd-hotplug` 3.5.1-r2`
ksmbd-server `3.5.1-r2`

2024-03-30 11:35 UTC, BKPepe requested changes
1. Commit message should be like this:
- kmsbd-tools: use tagged release
- kmsbd-tools: switch to use tagged release

2. In the commit description:
Instead of checking Git sources, we will use now tagged releases, because of smth...

2024-03-30 13:02 UTC, pesa1234 commented
> 1. Commit message should be like this:
> 
> 
>     * kmsbd-tools: use tagged release
> 
>     * kmsbd-tools: switch to use tagged release
> 
> 
>     2. In the commit description:
>        Instead of checking Git sources, we will use now tagged releases, because of smth...

Thanks, I'll fix it

2024-03-30 14:08 UTC, 1715173329 commented
https://github.com/openwrt/packages/commit/de64b43e3cf7a3cb3501dfde3d8b1fbfe7478c76
It was changed to use git sources by purpose, not sure if it works properly nowadays.

2024-03-30 17:42 UTC, pesa1234 commented
> [de64b43](https://github.com/openwrt/packages/commit/de64b43e3cf7a3cb3501dfde3d8b1fbfe7478c76) It was changed to use git sources by purpose, not sure if it works properly nowadays.

I didn't see any strange things right now

2024-03-30 17:57 UTC, BKPepe commented
I think, I will leave here this discussion: https://lists.openwrt.org/pipermail/openwrt-devel/2024-March/042499.html

2024-03-30 18:11 UTC, pesa1234 commented
> I think, I will leave here this discussion:

Ok, I don't know to solve the strange version to make it compatible with apk. So, feel free to close and thanks!

Andrea

2024-03-31 07:52 UTC, BKPepe commented
Nono, Andrea you did not do anything wrong. You did yours best here, nothing to worry about. The timing was not perfect, but it happens. Many packages are downloading tarball or checking out Git sources, so we should not block this PR as there is no conclusion what is better/preferable.  

Hopefully, the issue which was pointed out by @1715173329 is narrowed down. Lets see it by merging this.

2024-03-31 07:52 UTC, merged

2024-03-31 09:57 UTC, 1715173329 commented
yeah