adguardhome: update to 0.107.48
openwrt/packages pull request #23825
Opened 2024-04-06 02:43 UTC by JiaY-shi

View the release notes for more information:
https://github.com/AdguardTeam/AdGuardHome/releases/tag/v0.107.48

Maintainer: Dobroslaw Kijowski
Compile tested: x86/64;openwrt main
Run tested: glinet gl-mt6000

Description: update to 0.107.48
Dependent on：https://github.com/openwrt/packages/pull/23824

Signed-off-by: Shi JiaYang <shi05275@163.com>

2024-04-12 09:01 UTC, 1715173329 requested changes

2024-04-12 09:01 UTC, 1715173329 commented on net/adguardhome/Makefile
> +PKG_RELEASE:=2
why? this should be kept as-is

2024-04-12 09:41 UTC, JiaY-shi commented on net/adguardhome/Makefile
> +PKG_RELEASE:=2
fixed

2024-04-12 12:25 UTC, 1715173329 commented
Cc @dobo90

2024-04-13 05:18 UTC, 1715173329 approved these changes

2024-04-13 21:08 UTC, merged