acme: fix script standalone error
openwrt/packages pull request #23962
Opened 2024-04-19 17:53 UTC by werwolfby

Maintainers: @tohojo, @stokito
Run tested: OpenWrt 23.05.3

Description:

Fix issue with `acme.sh`:

```
acme-acmesh: Running ACME for ****
/usr/lib/acme/hook: line 123: standalone: parameter not set
```

Here is few reported issues: 
https://github.com/openwrt/packages/issues/23756

Finally solution found here:
https://forum.openwrt.org/t/acme-not-working-on-openwrt-23-05-2/190724/3

And moved to this PR:
problem is that `hook` requres ` `standalone` variabe. So it is worth to be exported, to avoid script fail, even if the standalone already deprecated.

And the second issue is that comment about deprecated `state_dir` used `$CERT_DIR` that points to `/etc/ssl/acme`.
While actual default value is `/etc/acme`, so fixed it to use `$CERT_DIR`.

2024-04-19 19:30 UTC, stokito commented
Thank you for reporting. The hook doesn't use the `$standalone` var anymore but here it seems that you have an old version of the `acme-acmesh` package. So you upgraded only the `acme-common` but not upgraded the complimentary `acme-acmesh` package.

But anyway, given that the fix is small and can save someones time I would rather accept the PR and export the `standalone` for a backward compatibility.

But please also change the version number in Makefile to `PKG_VERSION:=1.1.2`.


> And the second issue is that comment about deprecated state_dir used $CERT_DIR that points to /etc/ssl/acme. While actual default value is /etc/acme, so fixed it to use $CERT_DIR.

Please revert the change. The state_dir is a "working directory" for the acme.sh where it stores settings, while the `/etc/ssl/acme` is a folder when the current generated certs are placed for a webserver.

Did you had any troubles with that?

2024-04-19 19:39 UTC, werwolfby commented
@stokito I've just upgrade my router to `23.05.3` and install `acme` from it. And this is the result of it. It wasn't working.

So I find this fixes and applied the changes.

Besides that `standalone` do not work it still fails in [this line](https://github.com/openwrt/packages/commit/4bec28b4d16d86cfb6f6f720c61072f5954a9b28#diff-9ad838d2e01d31c8e37bf4396ba86b71a3ffb69b9ad64e51bb6c62f182802382L123-L124) that was already removed from `master` but still not available for `23.05.3` (did we miss backport?):

```bash
	elif [ "$standalone" = 1 ]; then
```

According to `state_dir`. When I investigating the issue I found this in log:

```
WARN: Option "state_dir" is deprecated, please remove it. Certificates now exist in /etc/ssl/acme"
```

So I've update my scripts to point to this folder `/etc/ssl/acme`. Which is wrong because actual folder is `/etc/acme`.

So I thought that someone forge something. This message is still confusing and I don't know then what it should be...

2024-04-19 20:45 UTC, stokito commented
>  (did we miss backport?)

Yes. @tohojo please backport ASAP before many users will fail to renew certs and loose an access. This is critical.


> This message is still confusing and I don't know then what it should be...

See the commit for details
https://github.com/openwrt/packages/commit/b907223d57765d49858c2fb1bd6e0b0f4222db0e

2024-04-19 22:14 UTC, stokito requested changes

2024-04-19 23:00 UTC, werwolfby commented on net/acme-common/files/acme.init
> -		state_dir=/etc/acme
Sure will revert. But could you please clarify this from the above commit:

> With the new ACME package, certificates live in the standard location
/etc/ssl/acme, users who need to do certificate customizations should
look for them in that dir instead.

If default path is `/etc/ssl/acme` why do we set it to `/etc/acme`?

2024-04-20 10:26 UTC, tohojo commented on net/acme-common/files/acme.init
> -		state_dir=/etc/acme
`state_dir` is for all the other state acme.sh needs to run, only the certs themselves go into `/etc/ssl/acme` :)

2024-04-20 15:50 UTC, werwolfby commented on net/acme-common/files/acme.init
> -		state_dir=/etc/acme
But this is the problem. Withou changing `state_dir` certs where in `/etc/acme`. This is where confusion comes from. It advertise that certs will be in `/etc/ssl/acme`, which is not true without this change.

I’ll recheck this today. But probably it is the same backport issue 😞 .

2024-04-22 12:59 UTC, stokito commented
@tohojo please backport missing changes

2024-04-22 13:00 UTC, stokito commented on net/acme-common/files/acme.init
> -		state_dir=/etc/acme
> The state_dir is a "working directory" for the acme.sh where it stores settings, while the /etc/ssl/acme is a folder when the current generated certs are placed for a webserver.

Make ls inside of the dir to see a difference.
The state_dir deprecation was made earlier than my change so it shouldn't be related to the issue itself

2024-04-29 17:10 UTC, stokito commented
@tohojo please backport missing changes

2024-05-03 21:27 UTC, tohojo commented
Alright, pushed the update to acme-acmesh as 798738c9b7a86df2166d70192cd95963c1c9bbeb, so closing this...

2024-05-03 21:27 UTC, closed without merging

2024-05-04 04:45 UTC, stokito commented
@tohojo thank you! I also created a forum topic for support https://forum.openwrt.org/t/letsencrypt-acme-sh-and-luci-app-acme-support-topic/196821
Please subscribe to it.
I'm worried that the issue was reported on the forum for long time but I didn't noticed it. So now users can report issues in one topic and help each others.