tailscale: build with less features
openwrt/packages pull request #24706
Opened 2024-08-01 01:06 UTC by mochaaP

Maintainer: me
Compile tested: aarch64_cortex-a53 @ SNAPSHOT
Run tested: not yet

Description:
See <https://github.com/tailscale/tailscale/blob/main/build_dist.sh#L40>.
This shaves off about 500kb from the final executable.

2024-08-01 10:34 UTC, BKPepe commented
There is missing commit description itself to know in CLI and as well within git commands to know why those features were disabled.

2024-08-02 16:42 UTC, hnyman commented
package maintainer @ja-pa has been absent for a year. You might need to remove him as maintainer and assume the maintainer status in Makefile by yourself, as you @mochaaP or @p-w-p have been doing the updates lately.

2024-08-04 13:13 UTC, BKPepe requested changes

2024-08-04 13:13 UTC, BKPepe commented on net/tailscale/Makefile
> +GO_PKG_TAGS:=ts_include_cli,ts_omit_aws,ts_omit_bird,ts_omit_tap,ts_omit_kube,ts_omit_completion
However, you added commit description exactly the same as it is in the pull request, but still you have decided to build it with less features, you pointed us to https://github.com/tailscale/tailscale/blob/main/build_dist.sh#L40 and still I am not sure what was the reason to have fewer features. 

While looking at https://openwrt.org/submitting-patches, I see:
> It should explain to a competent reader why you made this commit.

2024-09-16 15:24 UTC, systemcrash commented
`ts_omit_aws` omits AWS from the build

https://github.com/tailscale/tailscale/commit/4f5ef82

`ts_omit_bird` [omits](https://github.com/tailscale/tailscale/blob/124ff3b034135dab4289155ecdbc3a9885858853/cmd/tailscaled/tailscaled_bird.go#L4) BIRD from the build. 

etc.

These omit flags are those proposed by the project authors themselves to reduce binary footprint (at cost of lesser used functionality).

2024-09-18 06:24 UTC, closed without merging

2024-09-18 06:44 UTC, mochaaP commented
continued in #24987

2024-09-18 06:46 UTC, BKPepe commented
There was no need to create a new PR, you could use the existing one.

Dne st 18. 9. 2024 8:44 uživatel Zephyr Lykos ***@***.***>
napsal:

> continued in #24987 <https://github.com/openwrt/packages/pull/24987>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwrt/packages/pull/24706#issuecomment-2357634952>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA7IDVBNMI2D2OGVL3XREOTZXEON7AVCNFSM6AAAAABLZQUJ42VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNJXGYZTIOJVGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2024-09-18 14:24 UTC, mochaaP commented
This one was on the master branch from my repo, so I have to open a new one.

2024-09-18 14:25 UTC, BKPepe commented
Never ever create pull request from the master branch, thats why you should use feature branches. You could also use master branch and create the other pull requests from different branch.