Update mwan3track
openwrt/packages pull request #24859
Opened 2024-08-21 16:07 UTC by ealdaz-seesai

The grep parameters in the nping test are in wrong order. grep expects pattern and then filename.

Run tested:
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='21.02.0'
DISTRIB_REVISION='r16279-5cc0535800'
DISTRIB_TARGET='ipq40xx/generic'
DISTRIB_ARCH='arm_cortex-a7_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt 21.02.0 r16279-5cc0535800'
DISTRIB_TAINTS='no-all busybox'
```

Description:
Setting nping as a track_method option in /etc/config/mwan3 would always result in the interface failing all tests and becoming offline.
```
config condition
	option interface 'mob2s1a1'
	option reliability '1'
	option count '1'
	option timeout '1'
	option down '3'
	option up '3'
	option track_method 'nping'
	list track_ip 'www.google.co.uk'
	option interval '2'
```

Changing the line in mwan3track
`result=$(grep $TRACK_OUTPUT Lost | awk '{print $12}')`
to 
`result=$(grep Lost $TRACK_OUTPUT | awk '{print $12}')
`
results in mwan3tracking behaving as expected, and the interface is correctly identified as being online.

2024-08-23 10:57 UTC, feckert requested changes
I have the following commits to this PR:
* Please change the commit message of your [commit](https://github.com/openwrt/packages/pull/24859/commits/e910aa833c47aab2591b62ebc03abd68592e31f4) in this PR from `Update mwan3track` to `mwan3: fix grep order for nping track methode`
* Add a valid Signed-off-by to this [commit](https://github.com/openwrt/packages/pull/24859/commits/e910aa833c47aab2591b62ebc03abd68592e31f4) so we have your realname and a valid email address.
* Also update the PKG_VERSION from `2.11.13` to `2.11.14`.

2024-09-02 07:27 UTC, feckert commented
CI/CD is still **not** happy! I think the name in your git config (your commit name) and your name in the Signed-off-by line is not the same.
Can you please also rebase again and bump the PKG_RELEASE by one. I have recently [merged](https://github.com/openwrt/packages/pull/24863) a commit with the same PKG_RELEASE number.

2024-09-04 06:42 UTC, feckert commented
@ealdaz-seesai I think something has gone wrong during rebase!

2024-09-04 06:43 UTC, feckert requested changes
We have now 4 commits! And the PKG_RELEASE is still not updated.
Please look at this again.

2024-09-04 11:29 UTC, ealdaz-seesai commented
Hi Florian
I’m going to get someone to help me with this asap. I’m not much of a git ninja. 

Eduardo

---

Eduardo Aldaz Carroll
CTO
sees.ai

E: ***@***.***
M: +44 (0) 7543 519191

> On 4 Sep 2024, at 07:44, Florian Eckert ***@***.***> wrote:
> 
> 
> @feckert requested changes on this pull request.
> 
> We have now 4 commits! And the PKG_RELEASE is still not updated.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/openwrt/packages/pull/24859#pullrequestreview-2279132108>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AIQJYAVHVVYWPBH6ZFKXL3DZU2T3ZAVCNFSM6AAAAABM4LGDDKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENZZGEZTEMJQHA>.
> You are receiving this because you were mentioned.
>

2024-09-04 13:33 UTC, ealdaz-seesai commented
Bumped up versions and changed author. 
Hope it's all OK now.

2024-09-05 09:39 UTC, feckert approved these changes

2024-09-05 12:38 UTC, merged

2024-09-05 12:38 UTC, feckert commented
Thanks merged!