mwan3: fix sed regex for tracking output ping check_quality
openwrt/packages pull request #24863
Opened 2024-08-22 14:01 UTC by wrsolichin

Run tested: RUTX12 Router, OpenWrt distribution release 21.02.0

Description: This PR attempts to fix `mwan3` features with `ping` when `check_quality` is enabled. I have recently tested the mwan3 features with the RUTX12 modem router, and I noticed that the loss outputs 0 when there is 100% packet loss. After debugging, I noticed a missing space is needed to output the correct packet loss, which is 100. I noticed that the space is still missing on master. The debugging process is shown below with the corresponding fix.

![mwan3_loss_bugfix](https://github.com/user-attachments/assets/0f175859-fe03-4cd1-8a8b-7cf5e36472bd)

2024-08-23 01:54 UTC, wlshdjj commented
ping -c 5 www.google.co.uk || echo “ping_status=$?”
ping_status=1

Well done!
I find that this does not have an effect on use because ping_status=1 when 100% lost.

TRACK_OUTPUT=/1
ping -c 5 www.google.co.uk > $TRACK_OUTPUT

loss="$(sed $TRACK_OUTPUT -ne 's/.* \([0-9]\+\)% packet loss.*/\1/p')"
ping_status=$?

if [ "$ping_status" -ne 0 ] || [ "$loss" -eq 100 ]; then
								latency=999999
								loss=100
fi

2024-08-23 11:04 UTC, feckert requested changes
I have the following commits to this PR:
* Please change the commit message of your [commit](https://github.com/openwrt/packages/pull/24863/commits/c2a0a0a1887b0b3746f16bf3fd38230828d501e1) in this PR from `Fix missing space for loss ` to `mwan3: fix sed regex for tracking output ping check_quality`
* Add a valid Signed-off-by to this [commit](https://github.com/openwrt/packages/pull/24863/commits/c2a0a0a1887b0b3746f16bf3fd38230828d501e1) so we have your real name and a valid email address.
* Also update the PKG_VERSION from `2.11.13` to `2.11.14`.

2024-08-23 11:04 UTC, feckert commented
@wlshdjj Sorry, I don't understand what you are trying to say

2024-08-23 12:46 UTC, wrsolichin commented
@wlshdjj I tried it for 50% packet loss, and it reports 0 without the space, you need the space to report the correct loss of 50 in this example as well.

2024-08-23 13:57 UTC, wrsolichin commented
@feckert updated, let me know if any other changes are needed.

2024-09-02 07:22 UTC, feckert approved these changes

2024-09-02 07:22 UTC, merged

2024-09-02 07:22 UTC, feckert commented
Thanks!