mwan3: add check_quality for httping
openwrt/packages pull request #24970
Opened 2024-09-13 15:51 UTC by wrsolichin

Run tested: RUTX12 Router, OpenWrt distribution release 21.02.0

Description: Currently, `check_quality` option is only available for track method `ping`. This PR adds `check_quality` option for track method `httping`.

2024-09-30 07:25 UTC, feckert requested changes
Please bump the PKG_RELEASE number by one

2024-09-30 13:42 UTC, wrsolichin commented on net/mwan3/files/usr/sbin/mwan3track
> +							loss="$(sed $TRACK_OUTPUT -ne 's/.* \([0-9]\+\).*% failed.*/\1/p')"
Updated the commit message to add example output of TRACK_OUTPUT.

2024-09-30 14:10 UTC, feckert commented
@wrsolichin 

> > Please bump the PKG_RELEASE number by one
> 
> The current master branch version is 2.11.15, and my current Makefile is 2.11.16. Should I bump it to 2.11.17?

That´s fine :+1:
I will check the new feature and then merge it if everything works as expected.

:+1:

2024-09-30 16:09 UTC, wrsolichin commented
> @wrsolichin
> 
> > > Please bump the PKG_RELEASE number by one
> > 
> > 
> > The current master branch version is 2.11.15, and my current Makefile is 2.11.16. Should I bump it to 2.11.17?
> 
> That´s fine 👍 I will check the new feature and then merge it if everything works as expected.
> 
> 👍

Thanks! Let me know if any other changes are needed.

2024-10-07 06:18 UTC, merged

2024-10-07 06:18 UTC, feckert commented
Thanks merged!