miniupnpd: 24.10 daemon fix, build updates... - replaced by 26793
openwrt/packages pull request #24988
Opened 2024-09-18 07:35 UTC by Self-Hosting-Group

#### miniupnpd: Update daemon to 2.3.9 and improve build/patches

- Update daemon to 2.3.9 to fix removal of nftables rules in `upnp_forward` and return the correct client port
- Build by git tar as release tar differ in generated code comments, more complex for backports
- Remove old (iptables variant) patches: `200-remove...` as it compiles and runs on OpenWrt 21.02 without it, and `300-macos...` as it is no longer required
- Build daemon with `--disable-pppconn` to remove legacy workaround not included in other implementations since >15y
- Remove `clean_ruleset_interval/threshold` UCI config options as not standard/working since OpenWrt 22.03, as nftables not supported

Close https://redirect.github.com/openwrt/openwrt/issues/18011
Close https://redirect.github.com/openwrt/luci/issues/7759
Close https://redirect.github.com/openwrt/packages/pull/26531

#### miniupnpd: Add patch: Clearer / less redundant protocol labels in description (optional, to merge with prior)

#### miniupnpd: Revised UCI and daemon config generation

- Revised daemon configuration generation
- Better document and reformat default `/etc/config/upnpd` UCI config
- Migrate the old UCI config options on daemon start
- Change `upnpd` UCI options as following:

`upnpd`/`config` UCI option | Change                    | Previous opt.
----------------------------|---------------------------|---------------
stun_host                   | Allow to include port (1) |
stun_port                   | Removed, no more needed   |
use_stun                    | Allow more values (2)     |
allow_third_party_mapping=0 | Inverted/extended (3)     | secure_mode=1
download_kbps               | In kbit/s and renamed (4) | download
upload_kbps                 | In kbit/s and renamed (4) | upload
upnp_igd_compat=igdv1       | Renamed/match default (5) | igdv1=1
enabled                     | Match default (5)         |
enable_pcp_natpmp           | Renamed                   | enable_natpmp
notify_interval             | Removed if <900s, minimum |
port                        | Removed if default        |
upnp_lease_file             | Removed if default        |

`upnpd`/`perm_rule` (ACL)   | Change                    | Previous opt.
----------------------------|---------------------------|---------------
action                      | ACL denied by default (6) |

1. Remove known incompatible STUN servers and set compatible default
2. More allowed values for IPv4 CGNAT use and migrate old options from OpenWrt/X-Wrt
3. Extended to apply to PCP
4. Gets converted, now defaults to interface link speed, remove 8/4 Mbit/s defaults
5. Init default now matches UCI/LuCi default of upnp_igd_compat=igdv1 and enabled=0
6. Empty ACL denied by default, added template entry including low ports

Corresponding LuCI PR https://redirect.github.com/openwrt/luci/pull/7822

Compile and run tested config generation, daemon init, and UCI migration on OpenWrt 24.10.1/21.02.7

2024-11-08 11:24 UTC, Neustradamus commented
@Self-Hosting-Group: Nice PR!

cc: @systemcrash

2025-01-06 15:55 UTC, systemcrash commented
A downgrade included in a patchset won't get accepted, since a downgrade may subtly reintroducing bugs for existing users, if we assume that point releases fix bugs only. Better to wait for a new release, and bump to that version. 

Migrations are probably a more serious matter: those must be carried basically 'forever'. The best way is simply to avoid those. One might introduce a new setting, and deprecate the old one, and change the UI over to use the new one. Still a bit of a bumpy road. 

I think personally this is minor in the grand scheme of things (rather unimportant settings), but other reviewers may take a much firmer stance on it since you are, after all, changing setting names.

2025-01-06 17:56 UTC, systemcrash commented
> What do you think about backporting the commit?

Acceptable. It just breaks compile at the next release bump when it no longer applies. Minor, I guess.

2025-01-13 14:01 UTC, systemcrash commented
Every single test-build failed: Dirty patches detected, please refresh and review the diff

2025-03-03 15:51 UTC, abubaca4 commented
This solve my problem https://github.com/openwrt/openwrt/issues/18011
While I search this problem I found https://community.wd.com/t/why-my-cloud-home-make-so-much-upnp-forwarding-up-to-115/473182 with this problem
And I know several people from 4pda.to that downgraded from  24.10 to 23.05.5 because of this problem

2025-04-04 16:17 UTC, systemcrash commented
OK, 2.3.8 is finally here. That's what's required. 

ping @BKPepe @neheb

2025-04-04 16:22 UTC, BKPepe commented
Several commits tend to not follow guidelines, I suggest to check what you can find here:
- https://openwrt.org/submitting-patches

Subjects are too long, some of them have really short commit description or even none at all.

2025-04-04 16:30 UTC, BKPepe commented on net/miniupnpd/patches/400-securemode-for-igd-ipv6.patch
> +--- a/upnpsoap.c
This patch should be backported here as https://github.com/miniupnp/miniupnp/commit/c79e25a.patch

It will have the Git header to make sure who is the author, subject, description and we know if is backported or not

2025-04-05 13:08 UTC, systemcrash commented
Just motivate briefly each commit; its reasoning. Separate commits are acceptable, and here possibly necessary in case any one step turns out to be problematic.

2025-05-16 21:40 UTC, systemcrash commented on net/miniupnpd/files/upnpd-migration.uci-defaults
This migration must be carried indefinitely. Just handle the old and new cases in the init script.

2025-05-17 12:59 UTC, systemcrash commented on net/miniupnpd/files/upnpd-migration.uci-defaults
Carry both options in the init script. Documenting the old and new options in the init script essentially clarifies their usage. Ignore the old usage if the new usage is present. This way migrations don't need to be carried forever.

2025-06-03 08:58 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +	# Migrate stun_host and stun_port and pre-configure compatible STUN server
Please put all migration stuff into a separate migration function. Call it from start_service(). 

Here you perform an in-place migration, which is acceptable. Document each moment why migrating each specific setting is necessary. The daemon no longer understands it?

2025-06-06 12:13 UTC, systemcrash commented
> Any comments?

Better. You've just given a description of the changes, not motivated the reason that the migrations must be there. Any other reviewer will look at the migration section and think 'do we really have to carry that forever?'. And in short, the answer is yes, unless you document this in the wiki, that a user must upgrade through certain versions to be sure a migration works, so that migration code can be dropped later on.

2025-06-11 09:01 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
This is getting more complicated than it should be. You are not using BUILD_VARIANT, thus it can be dropped.

2025-06-11 09:03 UTC, BKPepe commented on net/miniupnpd/patches/100-apply-securemode-conf-to-ipv6.patch
> +With IPv6 and UPnP IGD it could not be disabled before
I can not see that this patch was submitted to the upstream.

2025-06-11 10:35 UTC, Neustradamus commented
@Self-Hosting-Group: Oh yes, good catch, a new version was here:
- https://github.com/miniupnp/miniupnp/releases

2025-06-11 11:43 UTC, systemcrash commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
It's not defined anywhere in the Makefile

2025-06-11 12:25 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
But without it, it will not compile both variants:

```
cat feeds/packages/net/miniupnpd/Makefile | grep PKG_BUILD_DIR 
PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)/$(PKG_NAME)-$(PKG_VERSION)/miniupnpd
	echo "$(VERSION_NUMBER)" | tr '() ' '_' >$(PKG_BUILD_DIR)/os.openwrt

cat .config | grep miniupnpd
CONFIG_PACKAGE_miniupnpd-iptables=m
CONFIG_PACKAGE_miniupnpd-nftables=y

make -j$(nproc) V=sc package/feeds/packages/miniupnpd/{clean,compile}
...
Package miniupnpd-nftables is missing dependencies for the following libraries:
libip4tc.so.2
libip6tc.so.2
libnetfilter_conntrack.so.3
make[2]: *** [Makefile:147: /openwrt/bin/packages/arm_cortex-a9/packages/miniupnpd-nftables_2.3.9-r1_arm_cortex-a9.ipk] Error 1
make[2]: Leaving directory '/openwrt/feeds/packages/net/miniupnpd'
time: package/feeds/packages/miniupnpd/nftables/compile#0.16#0.26#0.38
    ERROR: package/feeds/packages/miniupnpd failed to build (build variant: nftables).
...
```

https://github.com/openwrt/packages/blob/5872070add7956524fd4d0d1b27625d5a40ce7c6/net/miniupnpd/Makefile#L81

https://github.com/openwrt/packages/blob/8dc916e888973a5d3f5bc4a1bdd47698442e75d3/net/miniupnpd/Makefile#L88

I also noticed that X-Wrt does the same thing:
https://github.com/x-wrt/packages/blob/5720d55b792fd898bf19f0438ed270c8a7d455a8/net/miniupnpd/Makefile#L17

2025-06-11 13:00 UTC, BKPepe commented on net/miniupnpd/patches/100-apply-securemode-conf-to-ipv6.patch
> +With IPv6 and UPnP IGD it could not be disabled before
Why I am already getting third notification that you respond to my comment, then you delete it, and then you write something else and that goes one more round?

I dont see why we should have this patch as upstream rejected it:
https://github.com/miniupnp/miniupnp/pull/678

Thus no, this patch is not getting in.

2025-06-11 13:03 UTC, BKPepe commented on net/miniupnpd/patches/100-apply-securemode-conf-to-ipv6.patch
> +With IPv6 and UPnP IGD it could not be disabled before
Your pull request is already huge, please do it how it should be and then it is possible to review it. Otherwise, it will take a lot of time to go through all of it.

2025-06-17 11:50 UTC, systemcrash commented
> * LuCI: How can the `stun_host` UI element only be required if it is enabled by the dependency (`use_stun`)? I was able to make the field unconditionally required by a LuCI function `validate`, but I could not make it required only if the field is also enabled (using `isActive`). Any tips?

This question is off-topic here, and should be posed in the luci repo (but you should consult the luci online documentation).

2025-06-17 11:51 UTC, systemcrash commented on net/miniupnpd/patches/100-apply-securemode-conf-to-ipv6.patch
> +With IPv6 and UPnP IGD it could not be disabled before
@BKPepe this PR looks more or less compliant now. The commit messages give reason to the changes.

2025-06-18 05:34 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
Well, before your update, it worked and there was no need and now, we need it. :) So, you are doing something wrong here.

2025-06-18 05:34 UTC, BKPepe commented on net/miniupnpd/patches/100-clearer-protocol-labels.patch
> +Subject: [PATCH] miniupnpd: Clearer / less redundant protocol labels in
Why do we need this patch? Why it is useful to have this merged?
It is not clear for me. I doubt that something like this is accepted by miniupnpd repository.

2025-06-18 06:20 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/100-clearer-protocol-labels.patch
> +Subject: [PATCH] miniupnpd: Clearer / less redundant protocol labels in
(IMHO: The problem with the daemon project is that hardly anything can be changed there. The project is essentially dying and just waiting for a new fork or project.)

2025-06-18 06:42 UTC, BKPepe commented on net/miniupnpd/patches/100-clearer-protocol-labels.patch
> +Subject: [PATCH] miniupnpd: Clearer / less redundant protocol labels in
👋 @miniupnp 

I think I dont agree with you, because looking at [miniupnp repository](https://github.com/miniupnp/miniupnp/commits/master/), there are still new commits, I think it is opposite to dying.

2025-06-18 07:05 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/100-clearer-protocol-labels.patch
> +Subject: [PATCH] miniupnpd: Clearer / less redundant protocol labels in
Sure, commits. I'm not saying nothing is happening, but important features such as an IPv6 ACL, reasonable logging (without debug), STUN CGNAT test that also opens the port so that it works in openwrt and improved IGDv2/IPv6 compatibility, are still missing in this project, which is almost 20 years old. Instead, support for macOS as a router has recently been fixed.

2025-06-18 10:31 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
```suggestion
PKG_NAME:=miniupnpd
PKG_VERSION:=2.3.9
PKG_RELEASE:=1

PKG_SOURCE_URL:=https://miniupnp.tuxfamily.org/files
PKG_SOURCE:=$(PKG_NAME)-$(PKG_VERSION).tar.gz
PKG_HASH:=66cb3c3d697ab2bb3a61d3c48628166d6ba328d7c2dbeb95898fdf2a3202af7b

PKG_MAINTAINER:=
PKG_LICENSE:=BSD-3-Clause
PKG_LICENSE_FILES:=LICENSE
PKG_CPE_ID:=cpe:/a:miniupnp_project:miniupnpd
```

This one works for me as it is. I haven't looked why your codeload does not work (yet). Maybe later.

2025-06-18 10:58 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
Yes, the previous Makefile. This makes backports more complicated, see https://github.com/openwrt/packages/pull/24988#discussion_r2153813061. If this issue gets fixed upstream, I'm very happy to remove this change. Also, note that `miniupnp.tuxfamily.org` was unreliable (https://redirect.github.com/miniupnp/miniupnp/issues/770), which was another reason for these build changes. (Note: I have only attempted to make changes where I see a reason to do so, but it can be removed.)

Let's see if this can be addressed upstream.

2025-06-18 11:33 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
You are still talking about backports. Which one? 2 patches are removed, you added 1 patch and thats not upstreamed and most likely it is not going to be accepted here.

2025-06-18 11:46 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
I still dont understand. What issue do you have currently then it needs to be switched to codeload? The current solution works and there were two patches. Patches can be applied there and you do have some unknown issues, where it does not work. Patches still can be applied while downloading tarball from website.

2025-06-18 12:07 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
Eh? You will still need to refresh the patch. Usually in GitHub provided tarballs, there might be something missing.

2025-06-18 12:29 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
No, I think it's an unusual release process that modifies files in an undesirable way. It seems that code comments are updated locally on the maintainer's side during the tar release process and included in the tar. However, these changes are not replicated to github, which leads to these differences. This surprised me, and perhaps the maintainer you pinged as well.

2025-06-18 12:57 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
Note: I'm not referring to code comments that get updated by e.g. quilt, but rather to the following differences, which then prevent the patches from being applied 1:1:

```
< # $Id: Makefile.linux,v 1.113 2025/03/30 22:36:04 nanard Exp $
---
> # $Id: Makefile.linux,v 1.114 2025/04/21 21:48:56 nanard Exp $
```

2025-06-30 12:56 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +		echo "enable_pcp_pmp=$(echo_yesno $enable_pcp_natpmp)"
No, that is not the case. The AI was hallucinating. Ask for a human review.

https://github.com/miniupnp/miniupnp/blob/master/miniupnpd/miniupnpd.conf#L82

2025-07-01 08:17 UTC, BKPepe commented on net/miniupnpd/files/miniupnpd.init
> +# Copyright (C) 2006-2025 OpenWrt.org
Are you affiliated somehow to OpenWrt? I would just keep it as it is.

2025-07-01 08:19 UTC, BKPepe commented on net/miniupnpd/Makefile
> +TAR_CMD=$(HOST_TAR) -C $(1)/.. $(TAR_OPTIONS)
Have you created issue about this in the upstream repository? I would just keep it as it was, thus using official tarball from the website instead of complicated things.

2025-07-01 12:06 UTC, BKPepe commented on net/miniupnpd/files/miniupnpd.init
> +	# Migrate old options from OpenWrt 19.07 and X-Wrt for CGNAT use
Do we need such migration from such old versions as 19.07?

2025-07-02 06:30 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	# Migrate old options from OpenWrt 19.07 and X-Wrt for CGNAT use
Good question. It's not just for an outdated version. I have clarified the comment in the code.
https://github.com/x-wrt/packages/blob/21.10/net/miniupnpd/files/upnpd.config#L5

2025-07-05 17:18 UTC, systemcrash commented on net/miniupnpd/files/upnpd.config
> +	option action                     deny
please quote all option values, i.e. `option blah 'value'`

2025-07-05 17:19 UTC, systemcrash commented on net/miniupnpd/files/upnpd.config
> +	option action                     deny
Also quote

2025-07-16 14:14 UTC, systemcrash commented
Fine by me.

2025-07-23 12:03 UTC, Self-Hosting-Group commented
Any comments or an expected date of acceptance?

2025-07-23 13:15 UTC, BKPepe commented
Sure, if it is ready. It doesnt look like it since every day you are doing some changes and force pushing it. It makes it harder for review..

2025-07-25 23:56 UTC, systemcrash commented
I'm fine with the changes. Just stop making them unless you're asked to do so.

2025-07-30 06:27 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	# Migrate old options from OpenWrt 19.07 and X-Wrt for CGNAT use
Migration for OpenWrt 19.07 option removed.

2025-07-30 07:13 UTC, BKPepe commented on net/miniupnpd/Makefile
> +	SECTION:=net
Why this was changed?

2025-08-04 08:00 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +	SECTION:=net
I have discovered that tabs have a special function in Makefiles, so these changes do not make sense. Removed.

2025-09-30 11:01 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +						[ "$(echo $unsafeport | cut -s -d "-" -f 2)" -le "65535" ] 2>/dev/null); then
I'm not sure if it's worth the reduced CPU cycles, but it is addressed.

2025-09-30 11:01 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +		upload="$(uci -q get upnpd.config.upload || echo 512)"
Addressed.

2025-09-30 13:33 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +			echo $extipv4 | grep -q -E "^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.|^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\." &&
Things like this are highly unreadable. Please test with a switch case (adjusting as necessary):

```sh
do_stuff() {
        echo "foo"
}

                case "$extipv4" in
                        # Private IPv4 RFC1918 ranges
                        10.* | 192.168.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].*)
                                do_stuff
                                ;;

                        # Private CGNAT IPv4 RFC6598 ranges
                        100.6[4-9]* | 100.[7-9]* | 100.1[0-1]* | 100.2[0-7]*)
                                do_stuff
                                ;;

                        # RFC 5737 documentation
                        192.0.2.* | 198.51.100.* | 203.0.113.*)
                                do_stuff
                                ;;

                        # Invalid, loopback, or RFC3927/5735 IPv4
                        0.* | 127.* | 169.254.*)
                                do_stuff
                                ;;

                        # IPv6 private or reserved ranges
                        fc* | fd* | fe[89a-f]*)
                                do_stuff
                                ;;

                        # # Anything else
                        # *)
                esac
```

2025-09-30 13:59 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +			echo $extipv4 | grep -q -E "^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.|^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\." &&
IMHO, the overhead is huge. However, I am trying to find a compromise. And we don't have to check for IPv6.

2025-09-30 14:14 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +			echo $extipv4 | grep -q -E "^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.|^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\." &&
OK - but grep spawns an additional subshell, whereas the case doesn't.

2025-09-30 14:15 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +			echo $extipv4 | grep -q -E "^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.|^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\." &&
Not sure if it's worth it? 4+ lines of code instead of one line.

```
case "$extipv4" in
10.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].* | 192.168.* | 100.6[4-9].* | 100.[7-9][0-9].* | 100.1[0-1][0-9].* | 100.12[0-7].*)
	extipv4private=1
	;;
esac
```

2025-09-30 14:20 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +			echo $extipv4 | grep -q -E "^10\.|^172\.1[6-9]\.|^172\.2[0-9]\.|^172\.3[0-1]\.|^192\.168\.|^100\.6[4-9]\.|^100\.[7-9][0-9]\.|^100\.1[0-1][0-9]\.|^100\.12[0-7]\." &&
much better. faster.

2025-09-30 14:27 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +				[ "$(echo $stun_host | cut -s -d ":" -f 2)" != "" ] && echo "ext_stun_port=$(echo $stun_host | cut -s -d ":" -f 2)"
Use variable/parameter substitution. 

`ext_stun_host="${stun_host%%:*}"`
`ext_stun_port="${stun_host##*:}"`

2025-09-30 19:30 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +		uci -q delete upnpd.config.notify_interval
I get the error `ash: out of range` if it doesn't exist.

2025-09-30 20:52 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +		uci -q delete upnpd.config.notify_interval
You should handle or prevent the error as (largely) per copilot suggestion.

2025-10-02 00:00 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +		uci -q delete upnpd.config.notify_interval
Tested with an empy/invalid/not-migratable/migratable string in ash/bash:
`[ "" -le "900" ] 2>/dev/null && echo true || echo false` returns `false`
`[ "xyz" -le "900" ] 2>/dev/null && echo true || echo false` returns `false`
`[ "1000" -le "900" ] 2>/dev/null && echo true || echo false` returns `false`
`[ "30" -le "900" ] 2>/dev/null && echo true || echo false` returns `true`

2025-10-02 11:42 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +	log "Check UCI options in /etc/config/upnpd to be migrated (to v2.0) ..."
Prior to logging, perform a check that the target `settings` doesn't already exist so we can bail early.

2025-10-03 12:20 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +			}
There was already logging for this case.

https://github.com/openwrt/packages/blob/e643c192353a4a34c2832f5c1439f5f3f2d924f4/net/miniupnpd/files/miniupnpd.init#L163-L170

But now perform this check earlier in the code and then exit.

https://github.com/openwrt/packages/blob/6ab6741c1e27f0d653f47f27c4d488651d6eaf6d/net/miniupnpd/files/miniupnpd.init#L79

2025-10-17 16:45 UTC, Self-Hosting-Group commented
1. Improved network-wide ACL preset reverted to 8 october (a7a685d) and redone (question 1)
2. Current question: Can the unnecessary/not-working config_foreach upnpd "upnpd" (question 5) be removed?
3. A new human/AI review?

2025-10-20 07:10 UTC, Self-Hosting-Group commented
Hello @BKPepe @systemcrash. Comment updated, PR pushed. A new review by humans/AI?

> Prior to logging, perform a check that the target `settings` doesn't already exist so we can bail early.

(was about migration)

This brings me to important questions that I have not yet asked, but which I would like to clarify first.

1. **System-wide ACL preset (was implemented, now reverted to use network-wide again, improved)**
~~Is the new access control, with the ACL presets that can be selected for each internal network (vs. system-wide), possibly over-engineered?~~
~~(The currently implemented functionality is best explained via LuCI [screenshot](https://github.com/user-attachments/assets/cb2edfb0-650a-4680-ae04-9fe011bfd193))~~
- ~~I still think that ACL presets are a good idea, even with the option to additionally check the custom ACL entries first, but I'm not sure whether a system-wide ACL preset makes more sense than one per network (this would also make the additional internal_network section obsolete).~~
- ~~However, the resulting reduction in init/migration code is only about 17 lines less, ~18 on the LuCI side.~~
- ~~Rather, the LuCI UI, UI and UCI configuration is simplified, with the disadvantage that no network-specific ACL presets can be selected.~~

2. **Remove acl_check_custom=last (keep first) functionality (now implemented)**
Perhaps the functionality of UCI `acl_check_custom=last`, which checks the custom ACL in addition to the ACL preset  last, can also be removed, since I believe that the `first` functionality, which was implemented later, is sufficient.
as these will not work with the LuCI flag element.

3. **Remove compatibility for on/off booleans/config_get_bool as as these will not work with LuCI checkboxes  (now implemented)**
I found another design flaw in the init, which I believe to be an early one, that I would also fix. Boolean UCI options get not handled in LuCI by default, so only an `1` and not an `on/true/yes/enabled` value get an flag UI element with a checked checkbox, the others then flip the boolean on LuCI changes. I am considering replacing the last three `config_get_bool` calls with `config_get` and migrate the `enabled`/`ipv6_disable`/`system_uptime` options. Furthermore, I could not find any use for values other than `0`/`1` with the package.

4. **Rename custom ACL entry section name during action/ports option migration for a one-time migration?**

5. **Remove unnecessary/not-working config_foreach upnpd "upnpd"**
I found another design flaw in the init, which I believe to be an early one, that I would also fix. The `config_foreach upnpd "upnpd"` without generating configuration files with different paths cannot work. I would remove this foreach and simplify the init.

6. **Add or not to add custom ACL template entries with an empty/default ACL?**
I think I will remove the code that creates template ACL entries (keeping them in default config file) when migrating from an empty or default custom ACL. Since the `accept-all-ports`/`accept-high-ports`/ ACL preset is applied during migration in this cases, the custom ACL can also be left empty. This will remove around 26 lines of code.

7. **Commit count and size**
~~If you plan to merge all the commits (including commit that updates custom the ACL UCI options) rather than using them individually, can I merge commits 3, 6, and 7 now (keep 4 as `shfmt` indents, and 5 as it moves large code blocks separately)? This would simplify the changes for me.~~ Keeping more than 3 commits due to large size.

8. **Cherry picking first commits for early daemon fix**
Now that OpenWrt 24.10.3/4 is being rolled out, and many will probably upgrade to 24.10 again, it would be great if the daemon issues that have existed since version 24.10.0 could be resolved prematurely.
- The commits have been split so that the first daemon and the first two LuCI commits can be adopted early via cherry picking. This provides users with an early fix for the bugs, given that version 24.10.0 has been available for over seven months.
- These first commits do not require migration (and have no other requirements either), and the LuCI commits introduces a notification prompting users when no suitable config file is found to update the daemon and LuCI packages, as it was recognised in a previous issue that users sometimes only update individual packages. This will make the subsequent update even smoother.
- Manual LuCI translation updates were also prepared to ensure that no translations were lost in these initial commits.
Good idea this cherry picking path?

So, what do you think about that? Can you give me your opinion (yes/no) on this?

2025-10-20 07:10 UTC, Self-Hosting-Group commented
1. Improved network-wide ACL preset reverted to 8 october (a7a685d) and redone (question 1)
2. Current question: Can the unnecessary/not-working config_foreach upnpd "upnpd" (question 5) be removed?
3. A new human/AI review?

2025-10-20 11:00 UTC, systemcrash commented
I will remove myself as a reviewer here - stop making changes. 

@copilot

2025-10-20 11:36 UTC, Self-Hosting-Group commented
> I will remove myself as a reviewer here - stop making changes.

OK. Thanks for the response. Perhaps you could review the LuCI PR. There are hardly any changes to be expected there.

2025-10-20 13:02 UTC, systemcrash commented
> OK. Thanks for the response. Perhaps you could review the LuCI PR. There are hardly any changes to be expected there.

Get this merged first.

2025-10-20 17:42 UTC, BKPepe commented
I've looked right now at only one commit, which should be quick and the easiest one to get merged:
https://github.com/openwrt/packages/pull/24988/commits/3e4c15d3bb7a5adcb65de011be4d61159c463c5a

I haven't reviewed the other commits yet, but to me, the overall description seems a bit too extensive. The use of ``redirect.github.com`` is interesting, and I understand the reasoning behind it — every force push would otherwise spam the related issue, which makes sense. However, the strikethrough text doesn’t work properly in the GitHub web UI, so it can be removed.

Also, I disagree with using a mirror that is only available over HTTP. That change should be done in a separate commit. If the project cannot ensure the reliability of its main website, even with the use of a CDN if necessary, that’s rather concerning.

I would focus only on the changes that are clear, simple, and low-risk — such as updating to the latest version, removing obsolete parts, or disabling unnecessary features.

I haven’t checked the remaining commits yet, because there are constant changes — new commits, updates to existing ones — and I’m hesitant to merge something that might immediately require follow-up fixes. It doesn’t feel ready to be merged yet.

Additionally, I’m concerned that the ``Signed-off-by`` line does not include a real name, which might be an issue for compliance.

2025-10-23 05:30 UTC, Self-Hosting-Group commented
Hello @BKPepe

Thanks for your comments.
The commits were recreated in a better order and now easier to review.

> I've looked right now at only one commit, which should be quick and the easiest one to get merged: [3e4c15d](https://github.com/openwrt/packages/commit/3e4c15d3bb7a5adcb65de011be4d61159c463c5a)

Yes, this commit was intended for cherry-picking, as were the two LuCI commits, as preparation to display a message in the event of an unsuitable config file being found, and are completely risk-free. Are the pushed makefile changes (https://github.com/openwrt/packages/pull/24988/commits/f8de9a96708b3bef61d8de5c762d181aa5953c76) a accepted solution to the mirror issues?

(The commits in bold were for cherry-picking, and those in italics were intended to be merged with the previous commit.)

Daemon:
1. **update daemon to 2.3.9 and improve build/patches**
2. new/revised UCI options and improve daemon init/config-gen
3. _group/rearrange config-gen slightly_
4. new/revised custom ACL UCI options and rename section
5. _rename UCI section name to settings (v2.0)_
6. _no restart by hotplug with custom config and format scripts_
7. _rearrange init functions_

LuCI:
1. **improve existing UI slightly**
2. **_add UPnP IGD Adjustments tab, rearrange as many options_**
3. ui redesign and adapt to new/revised package UCI options
4. new/revised custom ACL UCI options and rename section
5. _rename UCI section name to settings (v2.0)_

I think that this PR has now implemented all the functions, from my point of view (I'll now only optimise the migration). The following LuCI screenshots are provided to help you understand the new, powerful network-wide access control functionality during the review process. Thanks to the universal implementation of the `acl_accept_ports`/`acl_reject_ports` options, this functionality now provides a more useful alternative to existing custom ACL entries in many cases.

<img width="940" height="316" alt="luci-network-list" src="https://github.com/user-attachments/assets/7e89e59b-8458-4270-b590-4afce0c97546" />

<img width="900" height="444" alt="luci-network-edit" src="https://github.com/user-attachments/assets/f6eaf767-345d-4a3f-956a-ff13dbe7765a" />

2025-10-25 06:50 UTC, Self-Hosting-Group commented
Hello @BKPepe

Thanks for your comments.

The commits were recreated in a better order and now easier to review. I have deleted the comment with the questions. Because everything, including the separate service start and config-gen, has now been implemented or has been resolved in the meantime.

In my eyes, everything fits for me now, and I don't see anything else that needs to be done.
The optimisations took a while, but it's now ready for review ;-)

> I've looked right now at only one commit, which should be quick and the easiest one to get merged: [3e4c15d](https://github.com/openwrt/packages/commit/3e4c15d3bb7a5adcb65de011be4d61159c463c5a)

Yes, this commit was intended for cherry-picking, as were the two LuCI commits, as preparation to display a message in the event of an unsuitable config file being found, and are completely risk-free.

Are these pushed makefile changes a accepted solution to the mirror issues?

https://github.com/openwrt/packages/blob/34e1774907b47c7035884c61836838a260ca016e/net/miniupnpd/Makefile#L14

Daemon:
1. **update daemon to 2.3.9 and improve build/patches**
2. new/revised UCI options and improve daemon init/config-gen
3. _group/rearrange config-gen slightly_
4. new/revised custom ACL UCI options and rename section
5. _rename UCI section name to settings (v2.0)_
6. _refactoring by separate service start and config-gen_
7. _rearrange init functions_

LuCI:
1. **improve existing UI slightly**
2. **_add UPnP IGD Adjustments tab, rearrange as many options_**
3. ui redesign and adapt to new/revised package UCI options
4. new/revised custom ACL UCI options and rename section
5. _rename UCI section name to settings (v2.0)_

(The commits in bold were for cherry-picking, and those in italics were intended to be merged with the previous commit.)

I this PR has now implemented all the functions, from my point of view. The following LuCI screenshots are provided to help you understand the new, powerful network-wide access control functionality during the review process. Thanks to the universal implementation of the `acl_accept_ports`/`acl_reject_ports` options, this functionality now provides a more useful alternative to existing custom ACL entries in many cases.

<img width="940" height="316" alt="luci-network-list" src="https://github.com/user-attachments/assets/7e89e59b-8458-4270-b590-4afce0c97546" />

<img width="900" height="444" alt="luci-network-edit" src="https://github.com/user-attachments/assets/f6eaf767-345d-4a3f-956a-ff13dbe7765a" />

2025-11-03 20:30 UTC, Self-Hosting-Group commented
@BKPepe UPnP IGD daemon compatibility patch added. Please re-review.

2025-11-05 08:52 UTC, Self-Hosting-Group commented
As you can see, the rate of change has slowed down. Over the course of a week, there were only a few cosmetic changes. No bugs have been found for weeks!

2025-11-05 13:50 UTC, Neustradamus commented
@rbqvq: What do you think about this PR?

2025-11-10 13:40 UTC, Self-Hosting-Group commented
Hello @BKPepe. Now, no new pushes to this repository, package works well! Finally, some code was moved and now I think is the right time to review the following commits. ;-) The mirror issues are addressed by using the official GitHub releases, see below. And thanks for your comments.

https://github.com/openwrt/packages/blob/5ca92d916df664d6318fbaf488a0ef03d70b4962/net/miniupnpd/Makefile#L14

- The commits were recreated in a better order, and are easier to review
- Thanks to optimisations, the additional code for the new features in init is only ~37 lines, not counting the migration code
- I have deleted the comment with the questions. Because everything, including the separate service start and config-gen, and cancel earlier if no migration is necessary, has now been implemented or has been resolved in the meantime

In my eyes, everything fits, and I don't see anything else that needs to be done.
The optimisations took a while, but it's now ready for review.

> I've looked right now at only one commit, which should be quick and the easiest one to get merged: [aa7e58c](https://github.com/openwrt/packages/commit/aa7e58ce74c3c1ef8a1a60b85da40809daa78daf)

Yes, this commit was intended for cherry-picking, as were the two LuCI commits, as preparation to display a message to update in the event of an unsuitable config file being found, and get prepared for the section change. These commits have no dependencies.

Daemon PR:
1. **update daemon to 2.3.9 to fix issues and refresh building**
2. patch for UPnP IGD compatibility with Microsoft/Apple clients
3. patch to fix description filter option
4. new/revised UCI options and improve daemon init/config-gen
5. _group/rearrange config-gen and refactoring_
6. new/revised custom ACL UCI options and migrate section
7. _rename UCI section name to settings (v2.0)_
8. _refactoring by separate service start and config-gen_
9. _rearrange init functions_

[LuCI PR](https://github.com/openwrt/luci/pull/7822):
1. **improve existing UI slightly**
2. **_add UPnP IGD Adjustments tab, rearrange as many options_**
3. ui redesign and adapt to new/revised package UCI options
4. new/revised custom ACL UCI options and migrate section
5. _rename UCI section name to settings (v2.0)_

(The commits in bold were for cherry-picking, and those in italics were intended to be merged with the previous commit.)

This PR has now implemented all the functions, from my point of view. The following LuCI screenshots are provided to help you understand the new/extended network-wide access control functionality during the review process. Thanks to the universal implementation of the `acl_accept_ports`/`acl_reject_ports` options, this functionality provides a more powerful and useful alternative to existing custom ACL entries in many user cases.

The new network-wide access control functionality can best be described using the LuCI screenshots:

<details><summary>Enabled Networks / Access Control</summary>

<img width="900" height="316" alt="luci-network-list" src="https://github.com/user-attachments/assets/10d19e48-39f8-4114-98f9-4f716d07c674" />
</details>

<details><summary>Edit network access control settings</summary>

<img width="819" height="444" alt="luci-network-edit" src="https://github.com/user-attachments/assets/69185621-e4e8-40ea-80ec-6eb0bbc9980f" />
</details>

<details><summary>Advanced Settings tab with new CGNAT functionality</summary>

<img width="900" height="387" alt="luci-advanced" src="https://github.com/user-attachments/assets/40025b5e-65bd-4e2f-84b3-f05a47385e20" />
</details>

<details><summary>New UPnP IGD Adjustments tab</summary>

<img width="900" height="440" alt="luci-igd" src="https://github.com/user-attachments/assets/e05bb56a-a542-412d-a110-8567209a395c" />
</details>

<details><summary>LuCI notification if the related package is not updated</summary>

<img width="900" height="125" alt="luci-notification" src="https://github.com/user-attachments/assets/ba0095d7-3b7f-4dce-97f5-e0ce006c2dea" />
</details>

<details><summary>Full LuCI screenshot</summary>

<img width="900" height="1200" alt="luci-screenshot" src="https://github.com/user-attachments/assets/c8cf605a-f3d0-48ee-b29a-3b1d3ec7624e" />
</details>

2025-11-10 13:43 UTC, Self-Hosting-Group commented
@BKPepe As you can see, the rate of change has slowed down. This time, only a few of the UCI option names were shortened, with no code changes. No bugs have been found for months!

2025-11-10 16:43 UTC, aquanjsw commented
Just compiled and tested on my machine, it seems to be working fine.
But no plan to add `ext_allow_private_ipv4` related option?

2025-11-10 18:17 UTC, Self-Hosting-Group commented
Great! ;-) Thanks for testing.

> Just compiled and tested on my machine, it seems to be working fine. But no plan to add `ext_allow_private_ipv4` related option?

https://github.com/openwrt/packages/blob/5ca92d916df664d6318fbaf488a0ef03d70b4962/net/miniupnpd/files/miniupnpd.init#L123-L124

Setting the existing UCI option `external_ip` to, e.g., `203.1.2.3` (public IPv4) is a better solution in terms of client compatibility than using `ext_allow_private_ipv4=yes`.

The `ext_perform_stun=allow-filtered` daemon option, which was added shortly afterwards (my contribution, unfortunately not published under my name because the maintainer (@miniupnp) blocked me), is IMHO better, as it returns the correct IPv4.

Even though `ext_allow_private_ipv4=yes` option had to be corrected after its introduction and unexpectedly changed the logging ([new issue](https://redirect.github.com/miniupnp/miniupnp/issues/863)), I am no longer sure whether it should have been introduced at all, with all this trouble and regression. I know of others that were recently introduced, but the maintainer does not want me to submit them to get resolved.

And the reason why `allow-filtered` with STUN is necessary at all under OpenWrt with an unrestricted endpoint-independent IPv4 CGNAT is that the CGNAT test in the daemon has always been badly implemented. This requires that all UDP ports (random test ports) on the external IPv4 are open, which is not the case in any modern route OS for security reasons, instead of what would make much more sense, namely adding regular port maps to itself (internal IP) for the test, which would then work directly everywhere. This idea was also well received by a FreeBSD developer.

<details><summary><b>Screenshot of Advanced Settings tab with new CGNAT functionality</b></summary>

<img width="900" height="387" alt="luci-advanced" src="https://github.com/user-attachments/assets/40025b5e-65bd-4e2f-84b3-f05a47385e20" />
</details>

2025-11-10 18:57 UTC, Neustradamus commented
@Self-Hosting-Group: Good job since more one year about it.
I hope to see the merging one day!
Maybe you can update the title, it is not only for 24.10...

2025-11-11 04:58 UTC, aquanjsw commented
> Great! ;-) Thanks for testing.
> 
> > Just compiled and tested on my machine, it seems to be working fine. But no plan to add `ext_allow_private_ipv4` related option?
> 
> https://github.com/openwrt/packages/blob/5ca92d916df664d6318fbaf488a0ef03d70b4962/net/miniupnpd/files/miniupnpd.init#L123-L124
> 
> Setting the existing UCI option `external_ip` to, e.g., `203.1.2.3` (public IPv4) is a better solution in terms of client compatibility than using `ext_allow_private_ipv4=yes`.
> 
> The `ext_perform_stun=allow-filtered` daemon option, which was added shortly afterwards (my contribution, unfortunately not published under my name because the maintainer (@miniupnp) blocked me), is IMHO better, as it returns the correct IPv4.
> 
> Even though `ext_allow_private_ipv4=yes` option had to be corrected after its introduction and unexpectedly changed the logging ([new issue](https://redirect.github.com/miniupnp/miniupnp/issues/863)), I am no longer sure whether it should have been introduced at all, with all this trouble and regression. I know of others that were recently introduced, but the maintainer does not want me to submit them to get resolved.
> 
> And the reason why `allow-filtered` with STUN is necessary at all under OpenWrt with an unrestricted endpoint-independent IPv4 CGNAT is that the CGNAT test in the daemon has always been badly implemented. This requires that all UDP ports (random test ports) on the external IPv4 are open, which is not the case in any modern route OS for security reasons, instead of what would make much more sense, namely adding regular port maps to itself (internal IP) for the test, which would then work directly everywhere. This idea was also well received by a FreeBSD developer.
> 
> Screenshot of Advanced Settings tab with new CGNAT functionality

Thanks for your explanation, but there actually exist some scenarios that only `ext_allow_private_ipv4` can resolve, at least in my test.

Hope we can add this in the future when it becomes stable.

2025-11-11 07:35 UTC, Self-Hosting-Group commented
> Thanks for your explanation, but there actually exist some scenarios that only `ext_allow_private_ipv4` can resolve, at least in my test.

Could you please explain this in more detail and describe a scenario in which the STUN function cannot work with `allow-filtered`?

> Hope we can add this in the future when it becomes stable.

How? The fact that some PCP/NAT-PMP clients are not compatible when a private IPv4 address is returned will not change. They require a public IPv4 address to function, with these protocols, it is required that the external IP address (reported by the router) must be sent along with the [renewal](https://datatracker.ietf.org/doc/html/rfc6887#section-11.2.1). Therefore, I see the only option as sending a public IPv4 address so that port mapping works with all clients. And I don't want to suggest new, additional options that create compatibility issues.

Removing the comment of this code would work immediately and would be a more compatible alternative to the daemon option if someone does not want to use STUN:
```
# [ "$allow_cgnat" = "allow-private-ext-ipv4" ] && external_ip=203.1.2.3
```

If we have a use case, I will gladly enable the code.

2025-11-11 07:52 UTC, Self-Hosting-Group commented
With UCI/LuCI this is already possible:
<img width="459" height="50" alt="luci-ext-ipv4" src="https://github.com/user-attachments/assets/486e436f-a08a-4acd-824e-3ba05bdf0999" />

2025-11-11 08:26 UTC, aquanjsw commented
> > Thanks for your explanation, but there actually exist some scenarios that only `ext_allow_private_ipv4` can resolve, at least in my test.
> 
> Could you please explain this in more detail and describe a scenario in which the STUN function cannot work with `allow-filtered`?
> 
> > Hope we can add this in the future when it becomes stable.
> 
> How? The fact that some PCP/NAT-PMP clients are not compatible when a private IPv4 address is returned will not change. They require a public IPv4 address to function, with these protocols, it is required that the external IP address (reported by the router) must be sent along with the [renewal](https://datatracker.ietf.org/doc/html/rfc6887#section-11.2.1). Therefore, I see the only option as sending a public IPv4 address so that port mapping works with all clients. And I don't want to suggest new, additional options that create compatibility issues.
> 
> Removing the comment of this code would work immediately and would be a more compatible alternative to the daemon option if someone does not want to use STUN:
> 
> ```
> # [ "$allow_cgnat" = "allow-private-ext-ipv4" ] && external_ip=203.1.2.3
> ```
> 
> If we have a use case, I will gladly enable the code.

If I do want a PCP/NAT-PMP client to get private IP of the wan port reported, not sure if there is any other way, but in my test, only `ext_allow_private_ipv4` works for me.

2025-11-11 09:30 UTC, Self-Hosting-Group commented
Hello @AquanJSW

> but in my test, only `ext_allow_private_ipv4` works for me.

These incompatible clients don't actually care if the returned IPv4 address is the real public IP, as long as it's not private. The mapping actually works, but the API returns an error, which is shown to the user.

1. Since UCI `allow_cgnat=allow-filtered` has worked reliably in all my tests, and in order to follow up on this, please provide debug logs (`log_output=debug`, best collapsed in the comment) when setting the option. Have you tested it with a custom (compatible?) STUN server? Defaults to `stun.nextcloud.com`
2. And what does not work with the provided alternative, setting UCI `external_ip=203.1.2.3`?

Please also note that an additional bug in the `ext_allow_private_ipv4` option exists in daemon version 2.3.9 that affects UPnP IGD clients (it has recently been [fixed](miniupnp/miniupnp@9ff3c71bfb6c7f7bf525d6bda447387de7257aff), but not yet released). Therefore, this option currently has another disadvantage.

I want to cover all user cases with the revision of the packages. Therefore, it is important to me that this also works for you. 

(And possibly not quote the entire comment, to avoid making the PR history even longer.)

2025-11-11 10:14 UTC, aquanjsw commented
> Hello @AquanJSW
> 
> > but in my test, only `ext_allow_private_ipv4` works for me.
> 
> These incompatible clients don't actually care if the returned IPv4 address is the real public IP, as long as it's not private. The mapping actually works, but the API returns an error, which is shown to the user.
> 
> 1. Since UCI `allow_cgnat=allow-filtered` has worked reliably in all my tests, and in order to follow up on this, please provide debug logs (`log_output=debug`, best collapsed in the comment) when setting the option. Have you tested it with a custom (compatible?) STUN server? Defaults to `stun.nextcloud.com`
> 2. And what does not work with the provided alternative, setting UCI `external_ip=203.1.2.3`?
> 
> Please also note that an additional bug in the `ext_allow_private_ipv4` option exists in daemon version 2.3.9 that affects UPnP IGD clients (it has recently been [fixed](miniupnp/miniupnp@9ff3c71bfb6c7f7bf525d6bda447387de7257aff), but not yet released). Therefore, this option currently has another disadvantage.
> 
> I want to cover all user cases with the revision of the packages. Therefore, it is important to me that this also works for you.
> 
> (And possibly not quote the entire comment, to avoid making the PR history even longer.)

Sorry I didn't make it clear, if two tailscale client that behind a same private network want a direct connection between themselves though that private network but not a public one, they need to known the private IP each other, but not a pseudo or real public IP.

2025-11-11 11:07 UTC, Self-Hosting-Group commented
> Sorry I didn't make it clear, if two tailscale client that behind a same private network want a direct connection between themselves though that private network but not a public one, they need to known the private IP each other, but not a pseudo or real public IP.

This user case is still not fully clear to me. These two clients should share the same IPv4 subnet so they can connect to each other directly, and they cannot learn each other's IPv4 addresses using this service, only the router's external address.

For this specific use case, I could, if the other reviewers also wish, incorporate a UCI option that would then work for Tailscale but cause more problems for standard clients.

Would a UCI option be sufficient for you? I would prefer not to burden LuCI users with an additional/confusing UI option, but could also add it when wished, with an client compatibility warning. Had this long time ago in, but removed it when I discovered the current UPnP IGD daemon bug with the option.

Old LuCI CGNAT option screenshot including this additional option:
<img width="238" height="229" alt="luci-cgnat-old" src="https://github.com/user-attachments/assets/c8b0153b-2a83-43aa-bfc7-c41d1b5d278b" />

2025-11-11 11:13 UTC, aquanjsw commented
> > Sorry I didn't make it clear, if two tailscale client that behind a same private network want a direct connection between themselves though that private network but not a public one, they need to known the private IP each other, but not a pseudo or real public IP.
> 
> This user case is still not fully clear to me. These two clients should share the same IPv4 subnet so they can connect to each other directly, and they cannot learn each other's IPv4 addresses using this service, only the router's external address.
> 
> For this specific use case, I could, if the other reviewers also wish, incorporate a UCI option that would then work for Tailscale but cause more problems for standard clients.
> 
> Would this UCI option be sufficient for you? I would prefer not to burden LuCI users with an additional UI option, even with the current bug.

My test looks like this:

```
Client A: 192.168.1.100 -- Router A: 192.168.1.1 & 10.0.0.100 -- Router ... PUBIP A
Client B: 192.168.2.100 -- Router B: 192.168.2.1 & 10.0.0.101 -- Router ... PUBIP B
```

So if one wish the direct connection happens at `10.0.0.100 - 10.0.0.101`, a private IP report is needed then.

2025-11-11 11:33 UTC, Self-Hosting-Group commented
> Client A: 192.168.1.100 -- Router A: 192.168.1.1 & 10.0.0.100 -- Router ... PUBIP A
> Client B: 192.168.2.100 -- Router B: 192.168.2.1 & 10.0.0.101 -- Router ... PUBIP B

OK. But you never mentioned having multiple routers before.

> Would this UCI option be sufficient for you? I would prefer not to burden LuCI users with an additional UI option, even with the current bug.

?

2025-11-11 11:44 UTC, AquanJSW commented
> Would this UCI option be sufficient for you? I would prefer not to burden LuCI users with an additional UI option, even with the current bug.

Yes, it would be better for me to have a `ext_allow_private_ipv4` related UCI option :)

2025-11-11 12:06 UTC, Self-Hosting-Group commented
> Yes, it would be better for me to have a `ext_allow_private_ipv4` related UCI option :)

One more question about your setup. Does it currently work (tested?) by manually setting up firewall rules instead of using the service in OpenWrt, since the service has not been working so far for this specific user case (except with the X-Wrt enhancements)?

If you have a testable setup, would you be willing to do a full test, including trying out the LuCI UI, to see if it works for you? I would then add this option as an additional, optional commit and see if the other reviewers also find this useful.

2025-11-11 12:31 UTC, aquanjsw commented
> One more question about your setup. Does it currently work (tested?) by manually setting up firewall rules instead of using the service in OpenWrt, since the service has not been working so far for this specific user case (except with the X-Wrt enhancements)?

No, manually setting up firewall rules doesn't work in this case.

> If you have a testable setup, would you be willing to do a full test, including trying out the LuCI UI, to see if it works for you? I would then add this option as an additional, optional commit and see if the other reviewers also find this useful.

The LuCI UI seems to be working fine to me so far.

2025-11-11 13:30 UTC, Self-Hosting-Group commented
> No, manually setting up firewall rules doesn't work in this case.

I'll add the commit, and then can you run the Tailscale test? I only want to introduce this option if it's proven to work with it. Otherwise, we probably don't need it.

By the way: You need an unrestricted endpoint-independent (1:1) CGNAT to test with your setup whether the port maps between the routers work when they are not located at the same site.

2025-11-11 13:39 UTC, aquanjsw commented
> By the way: You need an unrestricted endpoint-independent (1:1) CGNAT to test with your setup whether the port maps between the routers work when they are not located at the same site.

I'm here thanks to my symmetric NAT, so probably I can't perform such a test.

> I'll add the commit, and you'll run the test? I only want to introduce this option if it's proven to work with Tailscale. Otherwise, we probably don't need it.

Yeah, glad to test :)

2025-11-11 14:03 UTC, Self-Hosting-Group commented
> I'm here thanks to my symmetric NAT, so probably I can't perform such a test.

Perhaps you will find someone for such a Tailscale test.

2025-11-12 07:49 UTC, AquanJSW commented
The new `ext_allow_private_ipv4` related function seems to be working fine generally in my test so far, except for a small bug (maybe?):

```patch
--- a/net/miniupnpd/files/miniupnpd.init
+++ b/net/miniupnpd/files/miniupnpd.init
@@ -107,7 +107,7 @@ upnpd_generate_config() {
        ! uci -q get upnpd.@internal_network[0].interface >/dev/null && log "No internal networks configured, not starting" daemon.err && exit 1
        # Only perform an STUN CGNAT test when necessary with a private/CGNAT external IPv4
        local extipv4 extipv4private
-       network_get_ipaddr extipv4 "$ifname"
+       network_get_ipaddr extipv4 "$external_iface"
        case "$extipv4" in
        10.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].* | 192.168.* | 100.6[4-9].* | 100.[7-9][0-9].* | 100.1[0-1][0-9].* | 100.12[0-7].*) extipv4private=1 ;;
        esac
```

According to the function decription of `network_get_ipaddr`, it accept a logical interface but not a l3_device.

> Perhaps you will find someone for such a Tailscale test.

By the way, I'm afraid I can't fulfill your expectations.

2025-11-12 13:21 UTC, Self-Hosting-Group commented
@AquanJSW

> The new `ext_allow_private_ipv4` related function seems to be working fine generally in my test so far, except for a small bug (maybe?):

`maybe?`: Have you tested it? It works here.

> According to the function decription of `network_get_ipaddr`, it accept a logical interface but not a l3_device.

Have you looked at the lines of code directly above this?

https://github.com/openwrt/packages/blob/c11d3704c0f1d9f799fc6aa115badeeb606cf3e4/net/miniupnpd/files/miniupnpd.init#L89-L104

https://openwrt.org/docs/guide-user/network/routedclient

> > Perhaps you will find someone for such a Tailscale test.

> By the way, I'm afraid I can't fulfill your expectations.

As I said, given the disadvantages described, I would prefer not to add an additional CGNAT option that could confuse users and is not tested with your proposed user case. I hope it can still be tested by the end of the review process. @BKPepe What do you think?

2025-11-12 14:54 UTC, aquanjsw commented
> `maybe?`: Have you tested it? It works here.

Yeah, tested. You can also check the usage of `network_get_ipaddr`, it should want the result of `network_find_wan` but not `network_get_device`.

In your code, the result of `network_get_ipaddr` should always be empty.

2025-11-12 15:22 UTC, Self-Hosting-Group commented
> > `maybe?`: Have you tested it? It works here.

Here it works!

> Yeah, tested. You can also check the usage of `network_get_ipaddr`, it should want the result of `network_find_wan` but not `network_get_device`.

And what kind of error do you get?

> In your code, the result of `network_get_ipaddr` should always be empty.

Not here. Can you provide more precise information (as always) since it works here, please add this line for testing, or propose code to be changed:

```
        # Only perform an STUN CGNAT test when necessary with a private/CGNAT external IPv4
        local extipv4 extipv4private
        network_get_ipaddr extipv4 "$ifname"
+       log "extipv4"
        case "$extipv4" in
        10.* | 172.1[6-9].* | 172.2[0-9].* | 172.3[0-1].* | 192.168.* | 100.6[4-9].* | 100.[7-9][0-9].* | 100.1[0-1][0-9].* | 100.12[0-7].*) extipv4private=1 ;;
        esac
```

2025-11-12 15:26 UTC, aquanjsw commented
code:
```bash
        network_get_ipaddr extipv4 "$ifname"
        echo "extipv4=$extipv4"
        network_get_ipaddr extipv4 "$external_iface"
        echo "extipv4=$extipv4"
```
result:
```
extipv4=
extipv4=10.193.81.227
```

2025-11-12 15:27 UTC, Self-Hosting-Group commented
I don't like sentences with `maybe` or `should`, I prefer precise information.

2025-11-12 15:30 UTC, Self-Hosting-Group commented
Here both works:
```
extipv4=192.168.1.100
extipv4=192.168.1.100
```

2025-11-12 15:35 UTC, aquanjsw commented
> > ```shell
> >         network_get_ipaddr extipv4 "$ifname"
> >         echo "extipv4=$extipv4"
> >         network_get_ipaddr extipv4 "$external_iface"
> >         echo "extipv4=$extipv4"
> > ```
> 
> Here both works:
> 
> ```
> extipv4=192.168.1.100
> extipv4=192.168.1.100
> ```

Can you check the wan information in the output of `ubus call network.interface dump`, mine:

```
{
        "interface": [
                {
                        "interface": "wan",
                        "l3_device": "pppoe-wan",
                        "ipv4-address": [
                                {
                                        "address": "10.193.81.227",
                                        "mask": 32,
                                        "ptpaddress": "10.193.255.254"
                                }
                        ]
                }
        ]
}
```

If the interface and l3_device are different, it should be my situation.

2025-11-12 16:15 UTC, Self-Hosting-Group commented
OK. Thank you! That last, concrete, constructive comment was helpful ;-) Here, `interface` was the same as `l3_device`, so it worked for me. I've just applied the change.

2025-11-12 16:36 UTC, Self-Hosting-Group commented
@BKPepe Now that the packages (including the LuCI app) have been tested by AquanJSW and are working, it may be time to review the following commits (all after the first one).

2025-11-14 06:41 UTC, Self-Hosting-Group commented
OK. Thank you! That last, concrete, comment (ubus call output) was helpful ;-) Here, `interface` was the same as `l3_device`, so it worked for me. I've just applied the change.

2025-11-14 14:01 UTC, Self-Hosting-Group commented
@BKPepe Is it possible to keep the build artefacts for a single CI build? Then I could invite more people to test without having to compile the daemon package for all target platforms.

2025-11-17 08:34 UTC, Self-Hosting-Group commented
> @Self-Hosting-Group: Good job since more one year about it. I hope to see the merging one day! Maybe you can update the title, it is not only for 24.10...

What do you all think about using this as a better describing PR title? (Other suggestions welcome!)
`miniupnpd: Update, revision, new network access control and UCI options…`

2025-11-17 10:00 UTC, Self-Hosting-Group commented
I no longer expect answers to questions here… but to get it merged once! ETA?

2025-11-17 10:09 UTC, GeorgeSapkin commented
> @BKPepe Is it possible to keep the build artefacts for a single CI build? Then I could invite more people to test without having to compile the daemon package for all target platforms.

The artifacts are stored up to 90 days by default.

2025-11-17 10:14 UTC, GeorgeSapkin commented on net/miniupnpd/Makefile
> +PKG_SOURCE_URL:=https://github.com/miniupnp/miniupnp/releases/download/miniupnpd_$(shell echo $(PKG_VERSION) | tr "." "_")
I'm not sure if this has already been discussed, and I feel like I'm adding fuel to the fire at this point, but why not add a `PKG_SRC_VERSION` instead? Otherwise make has a native `subst` function.

2025-11-17 10:47 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +PKG_SOURCE_URL:=https://github.com/miniupnp/miniupnp/releases/download/miniupnpd_$(shell echo $(PKG_VERSION) | tr "." "_")
> I'm not sure if this has already been discussed

No, nobody pointed that out.

> I feel like I'm adding fuel to the fire at this point, but why not add a `PKG_SRC_VERSION` instead? Otherwise make has a native `subst` function.

No, this constructive code review was helpful, thank you. I initially attempted to implement it as it functions in FreeBSD, which does not work in OpenWrt, but thank you for the tip regarding the native GNU make `subst` function. I pushed this right away, but I can also introduce a `PKG_SRC_VERSION` if desired. However, I hope that this will no longer be necessary at some point when the project has tags with unmodified version numbers.
https://github.com/freebsd/freebsd-ports/pull/402/files#diff-6a7deda7d5f719803864b747210e5875ca0ff59aa67b85fc19394f9a14165c99R7

2025-11-17 11:09 UTC, Self-Hosting-Group commented
> The artifacts are stored up to 90 days by default.

Thanks! Great! Do you have any advice on how to download these? I can only see the `Download log archive` link.

2025-11-17 11:11 UTC, GeorgeSapkin commented
> Thanks! Great! Do you have any advice on how to download these? I can only see the `Download log archive` link.

Are they not visible for you under Summary > Artifacts?

<img width="740" height="281" alt="image" src="https://github.com/user-attachments/assets/b96cb7dd-4969-4ab3-8e09-373934b0f505" />

2025-11-17 11:49 UTC, 1715173329 requested changes

2025-11-17 11:49 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	procd_set_param file "$conf" "/etc/config/firewall"
consider using `procd_add_reload_trigger "firewall"` instead of listening `/etc/config/firewall`

2025-11-17 11:49 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
any reason to execute this at every start? this should be done via uci-defaults script

2025-11-17 11:49 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
please add proper line breaks to improve the readability, the same below.

2025-11-17 12:11 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
Yes

2025-11-17 12:15 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
With `if/fi` and line breaks, 9 more lines (3x3). OK?

2025-11-17 13:31 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> any reason to execute this at every start? this should be done via uci-defaults script

Yes, that's what I had at first. But systemcrash wanted it in the init. https://github.com/openwrt/packages/pull/24988#discussion_r2093704067

2025-11-17 13:45 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
The [LuCI](https://github.com/user-attachments/assets/69db00bc-e5e3-4c3b-a1f8-ac4b7a756d88) UI is currently worded in this way. It also helps if someone copies an old config file and restarts the service.

2025-11-17 13:56 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	procd_set_param file "$conf" "/etc/config/firewall"
(By the way, I used this line of code unchanged from the old plugin.)

2025-11-17 14:43 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	[ "$enabled" != "1" ] && log "Service disabled, UCI enabled is not set" && exit 1
`if` block is great, but actually I mean add line breaks between different commands to not mix them together, e.g.

```
	upnpd_uci_migration

	config_load "upnpd"

	local enabled config_file log_output conf
	config_get enabled settings enabled 0
	config_get config_file settings config_file
	config_get log_output settings log_output

	if [ "$enabled" != "1" ]; then
		log "Service disabled, UCI enabled is not set"
		exit 1
	fi

	if [ -n "$config_file" ]; then
		conf="$config_file"
	else
		local tmpconf="/var/etc/miniupnpd.conf"
		conf="$tmpconf"
		mkdir -p /var/etc
		upnpd_generate_config "$tmpconf"
	fi

	if [ "$FW" = "fw4" ]; then
		nft -s -t -n list chain inet fw4 upnp_forward >/dev/null 2>&1 || fw4 reload
	else
		iptables -L MINIUPNPD >/dev/null 2>&1 || fw3 reload
	fi
```

2025-11-17 15:08 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> But systemcrash wanted it in the init.

Honestly we don't really handle uci migrations this way, it doesn't make sense to do this in daemon.
So IMO -1, but I'm not against if other maintainers are fine with it.

>> This migration must be carried indefinitely. Just handle the old and new cases in the init script.
>> Carry both options in the init script. Documenting the old and new options in the init script essentially clarifies their usage. Ignore the old usage if the new usage is present. This way migrations don't need to be carried forever.

I don't understand this. For backwords compatibility you have to do the migration forever as users can upgrade from _any_ old version, and the "documentation" only applies to those already upgraded.
I believe users who can edit the configuration manually, they should also know what they're doing and it's not hard to see the changes without the "documentation". For users using LuCI they don't need to care this at all.

2025-11-17 15:22 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +		exit 1
```suggestion
		return 1
```

See #19617

2025-11-17 15:22 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +		exit 1
ditto

2025-11-17 15:22 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +		exit 1
ditto

2025-11-17 19:05 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +		exit 1
And here we have the problem that it is not the `start_service` function, so we would then need:
```
-               upnpd_generate_config "$tmpconf"
+               upnpd_generate_config "$tmpconf" || return 1
```

2025-11-17 19:05 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +		exit 1
Here too.

2025-11-17 20:22 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
I'm fine with either option. But there is another argument in favour of migration in `init`. I have noticed on several occasions that users only update individual packets on their router via the integrated package manager and then forget the related packet, hence the LuCI notification.

If I understand correctly, `uci-defaults` scripts (how I implemented it at the beginning) are only executed by default when the router starts up, and not, for example, during a package update via LuCI UI. I know that package manager updates are not the official way to update in OpenWrt, but many people do it anyway.

2025-11-17 20:28 UTC, systemcrash commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> Honestly we don't really handle uci migrations this way, it doesn't make sense to do this in daemon.
> So IMO -1, but I'm not against if other maintainers are fine with it.

Well, we either carry the migration script indefinitely or bake it in here, where it provides a few more guarantees. Half the point of this PR seems to be to escape the deprecated variable names.

2025-11-18 08:01 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> If I understand correctly, `uci-defaults` scripts (how I implemented it at the beginning) are only executed by default when the router starts up, and not, for example, during a package update via LuCI UI. 

uci-defaults will be executed at [postinst](https://github.com/openwrt/openwrt/blob/9d2882f3c0c1827cedcd1e3fe6475e00dd6fa85c/package/base-files/files/lib/functions.sh#L377) stage by the package manager.

There was a time that the {pre,post}inst script was not properly configured for apk upgrade, it has been fixed in openwrt/openwrt@03880e2551cb already.

2025-11-18 14:00 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> uci-defaults will be executed at [postinst](https://github.com/openwrt/openwrt/blob/9d2882f3c0c1827cedcd1e3fe6475e00dd6fa85c/package/base-files/files/lib/functions.sh#L377) stage by the package manager.

> There was a time that the {pre,post}inst script was not properly configured for apk upgrade, it has been fixed in [openwrt/openwrt@03880e2551cb](https://github.com/openwrt/openwrt/commit/03880e2551cb) already.

Great that it works now! It didn't work when I tested it, but it doesn't seem to have been included in 24.10/23.05 yet. One possible solution would be to call the uci-defaults script from init, so that it is always executed, but now only once. Is that a path we should go?

(Since I don't want to revise the migration code for the third time and then undo it again, perhaps a +1 from another reviewer would be helpful.)

2025-11-18 14:05 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
> but it doesn't seem to have been included in 24.10/23.05 yet.

24.10 and lower uses opkg which is unaffected by this issue, postinst works fine on those branches.

2025-11-24 12:20 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	upnpd_uci_migration
@1715173329 Is this what you prefer?

2025-11-24 12:48 UTC, 1715173329 commented on net/miniupnpd/Makefile
> +	$(INSTALL_BIN) ./files/upnpd-migration.uci-defaults $(1)/etc/uci-defaults
```suggestion
	$(INSTALL_BIN) ./files/upnpd-migration.uci-defaults $(1)/etc/uci-defaults/99-miniupnpd-migration
```

2025-11-24 12:48 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	[ -f "/etc/uci-defaults/upnpd-migration.uci-defaults" ] && sh /etc/uci-defaults/upnpd-migration.uci-defaults
this script will be executed and removed by the package manager, you don't really need to add a check here.

2025-11-24 12:48 UTC, 1715173329 commented on net/miniupnpd/files/upnpd-migration.uci-defaults
> +! uci -q get upnpd.@acl_entry[0] >/dev/null && if ! uci -q get upnpd.@perm_rule[0] >/dev/null; then
```suggestion
if ! uci -q get upnpd.@acl_entry[0] >/dev/null && ! uci -q get upnpd.@perm_rule[0] >/dev/null; then
```

2025-11-24 13:35 UTC, Self-Hosting-Group commented on net/miniupnpd/Makefile
> +	$(INSTALL_BIN) ./files/upnpd-migration.uci-defaults $(1)/etc/uci-defaults
I deliberately named the script the same as the config file, and also so that it can be easily executed again for multiple migrations without renaming it. For example, with:
`wget -P /etc/uci-defaults https://raw.githubusercontent.com/openwrt/packages/130cf62eb3a960b23e4e9ff18afc38a57f297198/net/miniupnpd/files/upnpd-migration.uci-defaults`

2025-11-24 13:35 UTC, Self-Hosting-Group commented on net/miniupnpd/files/miniupnpd.init
> +	[ -f "/etc/uci-defaults/upnpd-migration.uci-defaults" ] && sh /etc/uci-defaults/upnpd-migration.uci-defaults
> this script will be executed and removed by the package manager, you don't really need to add a check here.

Yes, I know. This has been implemented for snapshot builds that have not yet executed it. Should I remove it?

> There was a time that the {pre,post}inst script was not properly configured for apk upgrade, it has been fixed in [openwrt/openwrt@03880e2551cb](https://github.com/openwrt/openwrt/commit/03880e2551cb) already.

2025-11-24 13:35 UTC, Self-Hosting-Group commented on net/miniupnpd/files/upnpd-migration.uci-defaults
> +! uci -q get upnpd.@acl_entry[0] >/dev/null && if ! uci -q get upnpd.@perm_rule[0] >/dev/null; then
The else case then changes in an undesirable way.

2025-11-24 13:50 UTC, 1715173329 commented on net/miniupnpd/files/upnpd-migration.uci-defaults
> +! uci -q get upnpd.@acl_entry[0] >/dev/null && if ! uci -q get upnpd.@perm_rule[0] >/dev/null; then
Thanks for clarification. It looks a bit odd though.

2025-11-25 06:49 UTC, 1715173329 commented on net/miniupnpd/files/miniupnpd.init
> +	[ -f "/etc/uci-defaults/upnpd-migration.uci-defaults" ] && sh /etc/uci-defaults/upnpd-migration.uci-defaults
> Should I remove it?

Yes please

2025-11-25 06:52 UTC, 1715173329 commented on net/miniupnpd/Makefile
> +	$(INSTALL_BIN) ./files/upnpd-migration.uci-defaults $(1)/etc/uci-defaults
but why do they need to rename this? it's still executable by `sh upnpd-migration.uci-defaults`

2025-11-25 06:55 UTC, 1715173329 commented
```console
2025-11-24T14:10:26.2882353Z mipsel-openwrt-linux-musl-gcc -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -Wl,--gc-sections,--as-needed  -Wl,-z,now -Wl,-z,relro -pie -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib  miniupnpdctl.o  -lip4tc -lip6tc -lnetfilter_conntrack -lnfnetlink -lmnl -lcap-ng -luuid -o miniupnpdctl
2025-11-24T14:10:26.2911390Z mipsel-openwrt-linux-musl-gcc -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -Wl,--gc-sections,--as-needed  -Wl,-z,now -Wl,-z,relro -pie -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib  testupnpdescgen.o upnpdescgen.o  -lip4tc -lip6tc -lnetfilter_conntrack -lnfnetlink -lmnl -lcap-ng -luuid -o testupnpdescgen
2025-11-24T14:10:26.3062452Z mipsel-openwrt-linux-musl-gcc -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/usr/lib -L/builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/lib -fuse-ld=bfd -znow -zrelro -Wl,--gc-sections,--as-needed  -Wl,-z,now -Wl,-z,relro -pie -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib -L/builder/staging_dir/target-mipsel_24kc_musl/usr/lib  testgetifstats.o getifstats.o  -lip4tc -lip6tc -lnetfilter_conntrack -lnfnetlink -lmnl -lcap-ng -luuid -o testgetifstats
2025-11-24T14:10:26.3759479Z /builder/tmp/ccdrvTJm.ltrans0.ltrans.o: in function `main':
2025-11-24T14:10:26.3778948Z <artificial>:(.text.startup+0x8): relocation R_MIPS16_26 against `socket' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3797809Z <artificial>:(.text.startup+0x14): relocation R_MIPS16_26 against `perror' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3822096Z <artificial>:(.text.startup+0x32): relocation R_MIPS16_26 against `strncpy' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3848483Z <artificial>:(.text.startup+0x3c): relocation R_MIPS16_26 against `connect' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3854544Z <artificial>:(.text.startup+0x48): relocation R_MIPS16_26 against `perror' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3856342Z <artificial>:(.text.startup+0x4e): relocation R_MIPS16_26 against `close' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3857855Z <artificial>:(.text.startup+0x58): relocation R_MIPS16_26 against `puts' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3859357Z <artificial>:(.text.startup+0x62): relocation R_MIPS16_26 against `write' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3861010Z <artificial>:(.text.startup+0x76): relocation R_MIPS16_26 against `read' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3862556Z <artificial>:(.text.startup+0x84): relocation R_MIPS16_26 against `perror' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3864305Z <artificial>:(.text.startup+0x8a): relocation R_MIPS16_26 against `close' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3866034Z <artificial>:(.text.startup+0xa0): relocation R_MIPS16_26 against `fflush' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3867603Z <artificial>:(.text.startup+0xa6): relocation R_MIPS16_26 against `fileno' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3869097Z <artificial>:(.text.startup+0xb8): relocation R_MIPS16_26 against `write' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3870587Z <artificial>:(.text.startup+0xc4): relocation R_MIPS16_26 against `perror' cannot be used when making a shared object; recompile with -fPIC
2025-11-24T14:10:26.3872721Z /builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/14.3.0/../../../../mipsel-openwrt-linux-musl/bin/ld.bfd: non-dynamic relocations refer to dynamic symbol connect
2025-11-24T14:10:26.3875339Z /builder/staging_dir/toolchain-mipsel_24kc_gcc-14.3.0_musl/bin/../lib/gcc/mipsel-openwrt-linux-musl/14.3.0/../../../../mipsel-openwrt-linux-musl/bin/ld.bfd: failed to set dynamic section sizes: bad value
```

```
ifeq ($(BUILD_VARIANT),iptables)
	TARGET_CFLAGS += -flto
endif
```

looks like we need to remove lto flag for mips(el).

2025-11-25 15:00 UTC, Self-Hosting-Group commented
@1715173329

> looks like we need to remove lto flag for mips(el).

I assume that you do not want to remove this for all architectures. How then can the block be excluded for `mips`/`mipsel`, using `ARCH`?

2025-11-25 15:02 UTC, 1715173329 commented
~~`ifeq ($(filter mips mipsel, $(ARCH)),)` should work~~

EDIT: try `ifeq ($(filter $(ARCH),mips mipsel),)`

2025-11-25 15:35 UTC, Self-Hosting-Group commented
> ~`ifeq ($(filter mips mipsel, $(ARCH)),)` should work~
> 
> EDIT: try `ifeq ($(filter $(ARCH),mips mipsel),)`

Thanks a lot! I'll give it a try.

2025-11-25 16:16 UTC, Self-Hosting-Group commented
@1715173329 Thank you very much for your reviews, the comments were very constructive and helpful. You have helped me to make significant progress with this PR.

I think I have now addressed all your wishes, even the more cosmetic ones, as you gave me the helpful tip to fix the mips builds. But let's take a look at the CI results first.

I will address the remaining issues you pointed out in the migration code (if case) in the next update.

2025-11-26 07:33 UTC, Self-Hosting-Group commented
@1715173329 Thank you very much for your reviews, the comments were very constructive and helpful. You have helped me to make significant progress with this PR.

I think I have now addressed all your wishes, even the more cosmetic ones, as you gave me the helpful tip to fix the mips builds. Now the `mips`/`mipsel` CI checks are working too!

2025-11-26 12:55 UTC, 1715173329 approved these changes
LGTM - Thank you!

2025-11-26 14:03 UTC, GeorgeSapkin commented
@Self-Hosting-Group consider marking commits meant to be squashed as [fixups](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---fixupamendrewordcommit) so it's easier to understand what goes where. Or alternatively squash them as needed yourself.

2025-11-27 17:41 UTC, Self-Hosting-Group commented
@1715173329

> LGTM - Thank you!

Wow, nice! But first, we would need to look at the corresponding LuCI PR, and there is also a problem with the PR description to be updated. Can you take a look at it?
https://github.com/openwrt/luci/pull/7822

2025-11-27 19:42 UTC, Neustradamus commented
@Self-Hosting-Group team: Maybe good to do the missing steps before ;)

2025-11-28 04:34 UTC, 1715173329 commented
> Can you take a look at it? [openwrt/luci#7822](https://github.com/openwrt/luci/pull/7822)

Unfortunately it's locked and I cannot make any comments.
I'm not an expert in LuCI, and I don't have time to check it recently.

2025-11-28 06:41 UTC, Self-Hosting-Group commented
> Unfortunately it's locked and I cannot make any comments. I'm not an expert in LuCI, and I don't have time to check it recently.

Thank you very much for checking. Perhaps someone else with the necessary permissions could correct this.

2025-12-04 11:48 UTC, 1715173329 commented
I guess this should be fine to go

2025-12-04 12:08 UTC, GeorgeSapkin commented
@Self-Hosting-Group are you going to squash the commits marked with `(to merge with prior)`?

2025-12-07 22:22 UTC, ldir-EDB0 commented
I've tried this and it resolves a problem with old mappings hanging around.

2025-12-07 22:24 UTC, ldir-EDB0 approved these changes
LGTM

2025-12-11 09:20 UTC, Self-Hosting-Group commented
If anyone here has a newer Microsoft Xbox (One/Series) console, or knows someone who does, and could log the UPnP IGD traffic for analysis, this would be very helpful in testing if the introduced UPnP IGDv2 compatibility patch would work with the newer consoles as well. I have created a short how-to for logging.

#### How to log UPnP SSDP/SOAP requests, helpful for analysis, from Xbox One/Series X/S (360 tested)
1. Install `tcpdump` via LuCI software package manager or ssh (for logging, latest version of UPnP IGD service not required; only IGDv1 must be enabled)
2. Shut down the console before testing for full protocol handshakes
3. Start logging SSDP/SOAP requests on the OpenWrt router via a root SSH shell as follows:
`tcpdump -i br-lan -UnnX -w /dev/stdout 'ip && (port 1900 || port 5000)' | grep -iaEo 'MAN:.*|SOAPAction:.*|GET .*|POST .*|User-Agent.*|.*NewLeaseDuration.*'`
4. Start the console and start a multiplayer game, and check if the ports get opened / shown in the OpenWrt LuCI UI
5. Stop logging, and forward the log with the model of the console used, and whether the firmware is up to date

Note: Replace the LAN interface with the correct name. To log only the specific console IPv4 address, replace `'ip && (port 1900 || port 5000)'` with `'host 192.168.1.123 && (port 1900 || port 5000)'`

2025-12-15 18:23 UTC, GeorgeSapkin commented
@Self-Hosting-Group does this address any of the:
- #11971
- #17258 
- #21685

2025-12-17 14:10 UTC, Self-Hosting-Group commented
@1715173329

> I guess this should be fine to go

Yes, here, but there are still a few code comments in the dependent LuCI PR for which I would like to see a solution. However, no one has discovered this there yet ;-) I would also like to see a review of the wording there, possibly by @systemcrash?

The first commit here, and the first two (merged) from the LuCI PR, have no prerequisites and could be early cherry-picked, and the PRs then left open. With the first commit, we resolve the critical open issue (2 reported) that has existed since OpenWrt 24.10.0, and which @ldir-EDB0 mentioned again. Hopefully, we will have another upstream daemon update by the official release of 25.12, then we will need two fewer patches here, and I would like to leave open the possibility of changing the default of a new option in the current PR, and get your opinion on it, or rename an option name. Is this a viable path to go?

@GeorgeSapkin

> @Self-Hosting-Group are you going to squash the commits marked with `(to merge with prior)`?

Before squashing: At the beginning, it was written that the commit messages were insufficient, so I adjusted them. Now I've heard that they are extensive (too extensive?), or perhaps that referred more to the scope of the PR. What do you think they should be like? How many commits? Extensive text, or shorter (%, example)? Or parts of the description only in the PR? I am aware that the refactoring commits probably do not belong between the feature commits (beginning/end?). If you want multiple commits to merge the PR, I would redo them again.

> @Self-Hosting-Group does this address any of the:
>     * [miniupnpd log spamming #11971](https://github.com/openwrt/packages/issues/11971)
>     * [miniupnpd: logspam(?) - error flood #17258](https://github.com/openwrt/packages/issues/17258)
>     * [miniupnpd: Required key not available - flood every 30 seconds #21685](https://github.com/openwrt/packages/issues/21685)

OpenWrt now offers the option of selecting not only the very-verbose debug level for extra logging, but also the info level, which is usually sufficient. The logging is still unsatisfactory and confusing in the daemon. Insignificant things such as a non-existent (not yet) IPv6 lease file, which the daemon then deletes itself, is logged as error, but the essential port mapping requests, from the newly introduced info level onwards, are still not clear and mapping protocol agnostic. I have added your mentioned issues, and other related (5 in OpenWrt), as the last item on my core issues list. However, I have just checked the specific logging with this PR under OpenWrt. With the default log level, such flooding logging no longer occurs under normal circumstances. Even restarting the service only logs a few lines. In the event of errors or the previous debug logging, however, it is still extensive until this is improved in the daemon.

miniupnpd: Core functionality issues
https://github.com/Self-Hosting-Group/miniupnpd-issues

2025-12-19 01:37 UTC, 1715173329 commented
> Yes, here, but there are still a few code comments in the dependent LuCI PR for which I would like to see a solution. However, no one has discovered this there yet ;-)

So let's merge this firstly so someone will notice the LuCI is broken ;)

2025-12-19 07:31 UTC, Self-Hosting-Group commented
> So let's merge this firstly so someone will notice the LuCI is broken ;)

Let us first merge the first commit here so that users who are updating to OpenWrt 24.10.5 or 25.12.0.rc1 right now are satisfied. Could you cherry-pick that commit (removing the `redirect.` prefix from the commit message) and merge it the 24.10 and 25.12 branch?

2025-12-23 12:30 UTC, Self-Hosting-Group commented
> So let's merge this firstly so someone will notice the LuCI is broken ;)

As I am actively searching for solutions to issues for OpenWrt users and developers, I have just added an additional daemon patch to improve logging, as a small end-of-year gift.

But when I think of the users who have been affected by critical bugs in the daemon since OpenWrt 24.10.0 in February and have been waiting for a solution, I would feel better if we could merge the fixes for them as soon as possible... So, once again, my request:

Let us first merge the first commit here, so that users who are updating to OpenWrt 24.10.5 or 25.12.0.rc1 right now are satisfied. Can the first commit be cherry-picked (removing the `redirect.` prefix from the commit message) and merged into the 24.10 and 25.12 branches?

2025-12-24 02:07 UTC, 1715173329 commented
> Let us first merge the first commit here

Applided to 70ce349f1c9d915d4f3f49758a3aff2bb83664db, thanks!

2025-12-24 08:15 UTC, Self-Hosting-Group commented
> Applided to [70ce349](https://github.com/openwrt/packages/commit/70ce349f1c9d915d4f3f49758a3aff2bb83664db), thanks!

Thank you very much for merging! That's a gift!

2025-12-24 08:15 UTC, Self-Hosting-Group commented
What about merging into the 24.10 and 25.12 branches?
If 23.05 daemon/LuCI packages are still being built, could the daemon improvements possibly be incorporated there as well?

2025-12-24 08:54 UTC, 1715173329 commented
> What about merging into the 24.10 and 25.12 branches?

no ETA, but probably a few days later if our buildbot on master branch is happy

> If 23.05 daemon/LuCI packages are still being built

I guess no. The upnp package on 23.05 branch is even older and I don't want to take the risk of updating it.

2025-12-24 10:44 UTC, Self-Hosting-Group commented
> > What about merging into the 24.10 and 25.12 branches?
> 
> no ETA, but probably a few days later if our buildbot on master branch is happy

I didn't know this was automated. Nice!

(PR description and PR updated to reflect that the first commit is merged, and added request for Xbox logging.)

2025-12-28 10:11 UTC, 1715173329 commented
25.12: 976f67e8cf3a
24.10: 489c5227de3a

2025-12-29 12:45 UTC, BKPepe commented on net/miniupnpd/patches/10-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
Have you tried to upstream it?

2025-12-29 12:45 UTC, BKPepe commented on net/miniupnpd/patches/20-improve-logging.patch
> ++++ b/minissdp.c
This should be send to upstream first.

2025-12-29 13:01 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/010-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
I have also considered creating a maintained fork of the project, creating tested releases there, and maintaining the patches as individual branches, including documentation.

2025-12-29 13:16 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/10-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
This is unfortunately not possible for me directly, as I have been banned by the sole maintainer.
See note at the end of:
miniupnpd: Core functionality issues
https://github.com/Self-Hosting-Group/miniupnpd-issues

2025-12-29 13:16 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/10-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
Since this patch is already integrated into two other router operating systems, I have also considered creating a maintained fork of the project for these, having git tags tested, and maintaining the patches as individual branches, including documentation.

2025-12-29 13:30 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/20-improve-logging.patch
> ++++ b/minissdp.c
For this, I still have an old PR that I was able to extend ;-)
https://github.com/miniupnp/miniupnp/pull/764

2025-12-29 19:22 UTC, Neustradamus commented on net/miniupnpd/patches/10-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
@Self-Hosting-Group: I have sent you several messages and e-mails.
Have you progressed?

2025-12-29 23:28 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/010-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
@Neustradamus Please delete such off-topic comments here

2025-12-30 11:20 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/010-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
I regularly receive SPAM from Neustradamus. Please don't add to it here as well.

2025-12-30 11:32 UTC, Self-Hosting-Group commented on net/miniupnpd/patches/10-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
All over messages like that:
https://redirect.github.com/dani-garcia/vaultwarden/discussions/5170

2025-12-30 13:51 UTC, Neustradamus commented on net/miniupnpd/patches/010-upnp-igdv2-compat.patch
> +Link: https://github.com/Self-Hosting-Group/miniupnp/tree/upnp-igdv2-compat
Attention, important to read it!

@Self-Hosting-Group: I have contacted you by e-mails to explain why your account is not legal and it does not respect GitHub TOS. No e-mail answer. Recently, I have received a comment from this account to remove my previous comment and threats.

"@Neustradamus Confirm! Can we agree on that. Otherwise I have to block you and report to GitHub"

"An please remove this commen, AGAIN!
https://redirect.github.com/openwrt/packages/pull/24988#discussion_r2651612512

If you don't delete it I will block/report you! You don't helping you You're too pushy.

Learn something from other people's respect."

2026-01-10 03:54 UTC, Self-Hosting-Group commented
I reported this to GitHub: https://redirect.github.com/openwrt/luci/pull/7822#issuecomment-3731725055

Update: New bloated comment: Is this an repeating/off-topic/abusing SPAM bot???? ;-(

Can we do something about that? E.g. @GeorgeSapkin. Could you help?
https://redirect.github.com/openwrt/luci/pull/7822#issuecomment-3731817179

2026-01-10 04:46 UTC, Neustradamus commented
To follow my initial comment published here: https://github.com/openwrt/luci/pull/7822#issuecomment-3731725055
I have done a new detailled comment here: https://github.com/openwrt/luci/pull/7822#issuecomment-3731817179

Two PRs do not respect the OpenWrt "Submission Guidelines":
- https://github.com/openwrt/luci/pull/7822
- https://github.com/openwrt/packages/pull/24988

-------------

Attention: To add more informations, warnings specified in my previous comment are here, it is not from me (I have previously cited only the latest one):
- https://github.com/openwrt/luci/pull/7822#issuecomment-3670234835
- https://github.com/openwrt/luci/pull/7822#issuecomment-3670235305
- https://github.com/openwrt/luci/pull/7822#issuecomment-3680961083
- https://github.com/openwrt/luci/pull/7822#issuecomment-3692921716
- https://github.com/openwrt/luci/pull/7822#issuecomment-3693021638
- https://github.com/openwrt/luci/pull/7822#issuecomment-3696348671
- https://github.com/openwrt/luci/pull/7822#issuecomment-3705195119
- https://github.com/openwrt/luci/pull/7822#issuecomment-3710407821
- https://github.com/openwrt/luci/pull/7822#issuecomment-3712245147
- https://github.com/openwrt/luci/pull/7822#issuecomment-3712249538
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729913335
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729948495
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729960591
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729968788
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729971046
- https://github.com/openwrt/luci/pull/7822#issuecomment-3729973836
- https://github.com/openwrt/luci/pull/7822#issuecomment-3730608179

🔶 Author name (Self-Hosting-Group) seems to be a nickname or an alias
🔶 Committer name (Self-Hosting-Group) seems to be a nickname or an alias

Recall:
- Self-Hosting-Group has been banned by miniupnp team.
- I have already informed the PR author about the needed changes (nothing must be merged before changes).

The OpenWrt "Submission Guidelines" is here and clear:
- https://openwrt.org/submitting-patches

It is specified:
- all commits must contain `Signed-off-by: My Name <my@email.address>` where you write your real name and real email address, in accordance with Section 11 of the Linux Kernel patches guide: http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416
- GitHub web interface or GUI application for git: you must append the `Signed-off-by:` line manually in the commit description
- git command-line interface:
`git commit --signoff`
- the `Author` field must match the `Signed-off-by:` line
- GitHub web interface: you must specify your real name in the `Name` field and the `Primary email address` to match the `Signed-off-by:` line
- git command-line interface:
`git config --global user.name "my name"`
`git config --global user.email "my@email.address"`

2026-01-11 01:25 UTC, Self-Hosting-Group commented
> @GeorgeSapkin @BKPepe: I feel harassed by Nostradamus for the third time. I would like to have him blocked here if possible, and LuCI. Otherwise, I cannot continue with this PR. Reason: `Be nice to each other (formerly known as “Rule 12”)
`

2026-01-11 01:27 UTC, GeorgeSapkin commented
@Self-Hosting-Group I pinged some people for assistance, but I don't have access to anything, so can't do much. Sorry.

2026-01-11 01:49 UTC, Self-Hosting-Group commented
Thanks. I can also justify my request with examples. However, I do not want to draw any more attention to this cold wind if this is not necessary. I see someone here who is offended. And who is also spreading falsehoods (e.g. there's no miniupnp team, only single maintainer with repo privileges, and no ToS missuse...).

Note: We have 8 off-topic/abusive/zero-content comments from this user on this PR alone (+2 on LuCI, +2 new issues)
None of them refer to technical aspects or code improvements.

> I do not want a mistake in OpenWrt source code.

?

2026-01-11 02:38 UTC, Self-Hosting-Group commented
I'm not going to let my PRs be ruined after all that work.

2026-01-11 03:35 UTC, Neustradamus commented
Dear all, and Self-Hosting-Group (who is blocked from upstream by MINIUPNP project team),

I do not want a mistake in OpenWrt source code.

You do not understand the situation, like I have informed you since several months, you must to respect the GitHub TOS and you must to respect the OpenWrt "Submission Guidelines", please READ a new time.

IMPORTANT: You have attacked me previously, I have all messages to confirm the situation, public places and your private places, I prefer to keep good, I have only informed you several time to solve it but badly, you do not understand.

A very good point, after me, the OpenWrt GitHub Actions has informed you too! :)
For example here: https://github.com/openwrt/luci/pull/7822#issuecomment-3670234835 (all links have been sent previously), Attention: All OpenWrt GitHub Action comments have been minimized and it is needed to click on "Show comment" to read it.

```
github-actions bot:
- /!\ Warning
- Some formality checks failed.
- Consider (re)reading submissions guidelines.

Failed checks
For more details, see the full job log: https://github.com/openwrt/luci/actions/runs/20338048200/job/58429548533?pr=7822#step:4:1.
Something broken? Consider providing feedback: https://github.com/openwrt/actions-shared-workflows/issues.
```

And when we click on "Failed checks":
🔶 Author name (Self-Hosting-Group) seems to be a nickname or an alias
🔶 Committer name (Self-Hosting-Group) seems to be a nickname or an alias

The OpenWrt "Submission Guidelines" is here and clear:
- https://openwrt.org/submitting-patches

It is specified:
- all commits must contain `Signed-off-by: My Name <my@email.address>` where you write your real name and real email address, in accordance with Section 11 of the Linux Kernel patches guide: http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416
- GitHub web interface or GUI application for git: you must append the `Signed-off-by:` line manually in the commit description
- git command-line interface:
`git commit --signoff`
- the `Author` field must match the `Signed-off-by:` line
- GitHub web interface: you must specify your real name in the `Name` field and the `Primary email address` to match the `Signed-off-by:` line
- git command-line interface:
`git config --global user.name "my name"`
`git config --global user.email "my@email.address"`

I have always detailled you the problem, to change it, to have good PRs.
You do not listen, it is for this that your have been blocked by MINIUPNP project team :/

Note: More one year ago, I have specified you: https://github.com/openwrt/packages/pull/24988#issuecomment-2464468158 but the respect of rules must be done:
```
Self-Hosting-Group: Nice PR!
cc: systemcrash
``

2026-01-12 16:10 UTC, GeorgeSapkin commented
@Neustradamus you are not contributing anything to this PR besides noise. In fact I don't see you contributing anything to OpenWrt in general. I would think your comments being marked as spam and hidden would be signal enough, but no. Please stop.

2026-01-12 22:43 UTC, Neustradamus commented
Dear @GeorgeSapkin,

Please read the OpenWrt "Submission Guidelines" that all PR contributors must to respect.

I have done the detail but I need always to republish to other people because YOU have marked like SPAM but it is important to read.

I have informed this PR contributor about GitHub TOS and OpenWrt "Submission Guidelines".
Currently no change.

The OpenWrt GitHub Action said same than me.

Recall, this PR contributor has been blocked by MINIUPNP team.

Hope that all comments will be showed.

Thanks in advance.

2026-01-12 23:33 UTC, Self-Hosting-Group commented
(IMHO: Given the full story, an abuse tag would actually be more appropriate.)

2026-01-13 03:14 UTC, 1715173329 commented
I have enough with this, honestly.

Let's back to the code, any more changes needed before we merging this? LuCI changes?

@Self-Hosting-Group I hope you can still reply this thread ;)

2026-03-05 16:10 UTC, systemcrash commented
Can we pull the trigger on this, finally?

2026-03-09 06:33 UTC, 1715173329 commented
so is this okay for merge?

2026-04-21 08:01 UTC, schuettecarsten commented
The patch needs to be rebased

2026-08-06 06:30 UTC, closed without merging