add ddns-scripts for huaweicloud
openwrt/packages pull request #25120
Opened 2024-10-11 06:50 UTC by sxlehua

Maintainer:  @feckert
Compile tested: all supported targets
Run tested: mediatek/filogic

Description:
add ddns-scripts for huaweicloud

2024-10-11 14:34 UTC, feckert requested changes
Also please bump the PKG_RELEASE by one,

2024-10-11 14:34 UTC, feckert commented on net/ddns-scripts/Makefile
> +	rm $(1)/usr/share/ddns/default/huaweicloud.com.json.json
json.json?

2024-10-11 14:34 UTC, feckert commented on net/ddns-scripts/files/usr/share/ddns/default/huaweicloud.com.json
> +}
newline is missing

2024-10-11 14:34 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_huaweicloud_com.sh
> +#!/bin/sh
Please use <tabs> for indentation.

2024-10-11 14:34 UTC, feckert commented on net/ddns-scripts/files/usr/lib/ddns/update_huaweicloud_com.sh
> +local __HOST __DOMAIN __TYPE __ZONE_ID __RECORD_ID
`local` is not allowed for ash in global context as I know?

2024-10-11 15:34 UTC, sxlehua commented on net/ddns-scripts/Makefile
> +	rm $(1)/usr/share/ddns/default/huaweicloud.com.json.json
I will fix it

2024-10-11 16:39 UTC, 1715173329 commented
Please format your commit title and SoB according to https://openwrt.org/submitting-patches.

2024-10-11 17:16 UTC, sxlehua commented
> Please format your commit title and SoB according to https://openwrt.org/submitting-patches.

is ok?

2024-10-15 07:13 UTC, merged

2024-10-15 07:13 UTC, feckert commented
Thanks merged!