Add a prometheus exporter for Modem Manager Signal
openwrt/packages pull request #25283
Opened 2024-11-09 21:08 UTC by macjl

Maintainer: Jean-Laurent Girod
Compile tested: No compile test done
Run tested: ath79/generic, GL.inet GL-X300B, OpenWrt 23.05.5

Description:
Add a prometheus exporter that rely on modemmanager to provide signal strength informations.

2024-11-11 07:58 UTC, feckert commented
Please use one commit for this change, and also change the commit header to `prometheus-node-exporter-lua: add modemmanager exporter`.
How does the exporter behave if there is more than one modem in the system?

Please have in mind, that  if the modem is reattached The object ID in the ModemMananager Service is increment by one on every reattach. Is this handled by your code correctly?

2024-11-13 21:42 UTC, macjl commented
> Please use one commit for this change, and also change the commit header to `prometheus-node-exporter-lua: add modemmanager exporter`.

This is done !

> How does the exporter behave if there is more than one modem in the system?
> Please have in mind, that if the modem is reattached The object ID in the ModemMananager Service is increment by one on every reattach. Is this handled by your code correctly?

I don’t found any informations about the output of mmcli command when there are 2 modems, as I just have one modem to test it. Is there a way I could simulate a second one ?

2025-05-12 20:19 UTC, macjl commented
I changed the code to handle multiples modems as labels.

2025-06-23 18:03 UTC, champtar requested changes
@macjl your commit is missing the `Signed-off-by` line

2025-06-26 22:26 UTC, macjl commented
> @macjl your commit is missing the `Signed-off-by` line

I’ve just added it.

2025-09-06 23:45 UTC, GeorgeSapkin commented
@macjl is this still relevant? There are currently merge conflicts.

2026-05-06 17:27 UTC, GeorgeSapkin commented
@macjl you need to add a commit description.

2026-05-06 17:31 UTC, champtar commented
@macjl also the commit author should be you, claude can be added as `Co-authored-by`

2026-05-06 17:51 UTC, champtar reviewed
@macjl can you bump the PKG_VERSION ? then we can launch the CI and merge
```suggestion
PKG_VERSION:=2026.05.06
```

2026-05-06 18:01 UTC, champtar approved these changes

2026-05-24 11:22 UTC, closed without merging

2026-05-24 11:24 UTC, champtar commented
Tried to update your branch and it decided to close the PR, sorry about that

2026-05-24 11:30 UTC, champtar commented
I pushed openwrt packages `master` into the PR branch (also master), 0 commits difference so it closed the PR

2026-05-24 13:27 UTC, champtar commented
Push to master: 1b18489df87f5b511875bba5fee2b2dd1097ac79