strongswan: fix compilation with GCC14
openwrt/packages pull request #25353
Opened 2024-11-14 22:58 UTC by neheb

This API does not exist in libubox.

Maintainer: @pprindeville @Thermi

2024-11-19 15:53 UTC, pprindeville reviewed
Need this one explained to me.

2024-11-19 15:53 UTC, pprindeville commented on net/strongswan/patches/010-gcc14.patch
> ++		if (uci_lookup_next(this->ctx, &element, this->list, "name") == UCI_OK)
This looks like we're changing the logic of the function?

2024-11-22 21:17 UTC, neheb commented
```
strings libuci.so | grep uci_lookup
uci_lookup_next
uci_lookup_ptr
uci_lookup_ext_section
uci_lookup_list
uci_lookup_next
uci_lookup_ptr
uci_lookup_list
uci_lookup_next
uci_lookup_ptr
```

there's no uci_lookup. ping @jow-

2025-03-24 21:48 UTC, neheb commented
enjoy.

2025-03-24 21:53 UTC, Thermi commented
@neheb looks like most of the CI failed because of an incorrect signature. Could you please retry tomorrow?

2025-03-24 22:02 UTC, neheb commented
uci_lookup went away in 2008: https://git.openwrt.org/?p=project/uci.git;a=commit;h=563f8dd6

Hilarious that this code is still here. Probably unused and untested.

2025-03-24 22:15 UTC, neheb commented
@Thermi refreshed.

2025-03-24 22:55 UTC, neheb commented on net/strongswan/patches/010-gcc14.patch
> ++		if (uci_lookup_next(this->ctx, &element, this->list, "name") == UCI_OK)
I'm guessing this should be &this->current->list ?

2025-04-07 02:03 UTC, pprindeville commented on net/strongswan/patches/010-gcc14.patch
> +--- a/src/libcharon/plugins/uci/uci_parser.c
Can we get a descriptive header?

2025-04-07 02:04 UTC, pprindeville requested changes
Needs a `PKG_RELEASE` bump.

2025-04-27 19:41 UTC, pprindeville commented on net/strongswan/patches/010-gcc14.patch
> +--- a/src/libcharon/plugins/uci/uci_parser.c
Still hoping to merge this, but I need the review comments resolved.

2025-05-04 21:21 UTC, pprindeville commented on net/strongswan/patches/010-gcc14.patch
> ++		if (uci_lookup_next(this->ctx, &element, this->list, "name") == UCI_OK)
@nbd168 Can you please give guidance?

2025-05-04 22:34 UTC, pprindeville commented
@nbd168 What does the old `uci_lookup()` call now map to?

2025-05-04 22:45 UTC, neheb commented on net/strongswan/patches/010-gcc14.patch
> ++		if (uci_lookup_next(this->ctx, &element, this->list, "name") == UCI_OK)
I changed it. I doubt this code even runs.

2025-05-24 18:22 UTC, BKPepe commented on net/strongswan/patches/010-gcc14.patch
> +--- a/src/libcharon/plugins/uci/uci_parser.c
Ping @neheb

2025-07-12 03:33 UTC, neheb commented
I'm going to assume this was fixed by removing the code.

2025-07-12 03:33 UTC, closed without merging