net-snmp: refactor Makefile for optional variant with openssl and logging
openwrt/packages pull request #25444
Opened 2024-11-25 09:27 UTC by Chris1189

Maintainer: @stintel 
Compile tested: x86_64, Openwrt 23.05
Run tested: x86_64, Openwrt 23.05

Description:
Openssl is needed to implement encryption and authentification for SNMPv3.
As discussed in PR #25178 , I added a variant for net-snmp that compiles libnetsnmp 
with libopenssl (for SNMPv3). The default compilation is with the former variant.

The features for SNMPv3 are added to snmpd.init file and the possibility
to log messages to syslog or a log file.

2024-11-28 09:06 UTC, Chris1189 commented
@stintel : I updated the Makefile in a way that it is possible to compile snmp with or without openssl.
It also works for my purposes. Please review it when possible. Thank you!

2024-12-03 06:28 UTC, Chris1189 commented
@stintel : Did you find time to look into the changes?
One check failed because i updated the comment to change to Openwrt 24.10

2024-12-03 07:22 UTC, stintel commented
> @stintel : Did you find time to look into the changes?

Sorry, a bit busy with life. Might be a while. Without reviewing the code the following question comes to mind: can the user still do `opkg install libnetsnmp`?

2024-12-03 09:16 UTC, Chris1189 commented
I understand that and I didn't have in mind to pressure you.
I checked and saw that it was not possible.
So i added `PROVIDES:=libnetsnmp`to both variants and no it is possible

2025-02-13 12:26 UTC, Chris1189 commented
Hello @stintel ,
I think you might still  be busy. May I ask you if you could suggest a different maintainer, who may see into the PR?
Only to get things going.

2025-02-14 17:54 UTC, stintel requested changes
Also please add example sections in net/net-snmp/files/snmpd.conf for both SNMPv3 and logging.

2025-02-14 17:54 UTC, stintel commented on net/net-snmp/Makefile
> +
Remove extra newline.

2025-02-14 17:54 UTC, stintel commented on net/net-snmp/Makefile
> +  	    +snmpd-ssl
Please list dependencies in alphabetical order.

2025-02-14 17:54 UTC, stintel commented on net/net-snmp/Makefile
> +  	    +snmpd
Please list dependencies in alphabetical order.

2025-02-14 17:54 UTC, stintel commented on net/net-snmp/Makefile
> +	--without-perl-modules \
Remove trailing backslash.

2025-02-14 17:54 UTC, stintel commented on net/net-snmp/Makefile
> +$(eval $(call BuildPackage,net-snmp-nossl))
Please maintain alphabetical order here.

2025-02-14 18:04 UTC, stintel commented
Build test on qoriq shows a bunch of conflicts. I ran `make oldconfig` and said yes to the -ssl variants. You should probably remove the old variants (libnetsnmp, snmp-utils, snmpd) and only keep the -ssl and -nossl variants. Have both variants provide the old package name. And make sure you cannot enable both the -ssl and -nossl variants at the same time.

```
Collected errors:
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * opkg_install_cmd: Cannot install package libnetsnmp-ssl.
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * opkg_install_cmd: Cannot install package snmp-utils-ssl.
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmphelpers.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpmibs.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * opkg_install_cmd: Cannot install package snmpd-ssl.
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmp.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib/libnetsnmpagent.so.40.2.1
        But that file is already provided by package  * libnetsnmp
 * check_data_file_clashes: Package libnetsnmp-ssl wants to install file /home/stijn/Development/OpenWrt/openwrt/build_dir/target-powerpc64_e5500_musl/root-qoriq/usr/lib [...]

2025-02-17 05:37 UTC, Chris1189 commented
Thank you for your review!
I resolved your requested changes and now it should be only possible to build one package of the two.
The old packages are now virtually provided by them.

2025-02-18 08:27 UTC, Chris1189 commented
@stintel : Are these changes what you had in mind?

2025-02-22 19:51 UTC, stintel commented
The config examples should be in the commit that adds that specific config option. Also, I noticed you added meta packages net-snmp-ssl and net-snmp-nossl, these should go in a separate commit also. And finally, I'm not getting these errors during make oldconfig:

```
tmp/.config-package.in:56157:error: recursive dependency detected!
tmp/.config-package.in:56157:   symbol PACKAGE_libnetsnmp-ssl depends on PACKAGE_libnetsnmp-nossl
tmp/.config-package.in:56139:   symbol PACKAGE_libnetsnmp-nossl depends on PACKAGE_libnetsnmp-ssl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

tmp/.config-package.in:113995:error: recursive dependency detected!
tmp/.config-package.in:113995:  symbol PACKAGE_net-snmp-nossl depends on PACKAGE_net-snmp-ssl
tmp/.config-package.in:114009:  symbol PACKAGE_net-snmp-ssl depends on PACKAGE_net-snmp-nossl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

tmp/.config-package.in:115760:error: recursive dependency detected!
tmp/.config-package.in:115760:  symbol PACKAGE_snmp-utils-nossl depends on PACKAGE_snmp-utils-ssl
tmp/.config-package.in:115770:  symbol PACKAGE_snmp-utils-ssl depends on PACKAGE_snmp-utils-nossl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

tmp/.config-package.in:115780:error: recursive dependency detected!
tmp/.config-package.in:115780:  symbol PACKAGE_snmpd-nossl depends on PACKAGE_snmpd-ssl
tmp/.config-package.in:115796:  symbol PACKAGE_snmpd-ssl depends on PACKAGE_snmpd-nossl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"

tmp/.config-package.in:115812:error: recursive dependency detected!
tmp/.config-package.in:115812:  symbol PACKAGE_snmptrapd-nossl depends on PACKAGE_snmptrapd-ssl
tmp/.config-package.in:115822:  symbol PACKAGE_snmptrapd-ssl depends on PACKAGE_snmptrapd-nossl
For a resolution refer to Documentation/kbuild/kconfig-language.rst
subsection "Kconfig recursive dependency limitations"
```

2025-02-25 08:10 UTC, Chris1189 commented
@stintel : I resolved the error log reason. 
Please reach out if the commits need some maintenance, but I added the config to the introduction of the modified init script and separated into the old snmp version and the new ssl variant in two separate commits.

Again, thank you for your review!

2025-03-25 07:27 UTC, closed without merging