strongswan: swanctl: Add support for encap
openwrt/packages pull request #25472
Opened 2024-12-01 19:07 UTC by kevinoid

Maintainer:  @pprindeville @Thermi
Compile tested: None.  Script only change.
Run tested: aarch64, Linksys E8450 mediatek/mt7622, OpenWrt 23.05.5, checked generated `swanctl.conf` and operation

Description:
Support the [encap] connection configuration option to force UDP encapsulation of ESP packets to work around connectivity issues with middleboxes which block ESP packets.

This work is based on a patch by @aleks-mariusz in https://forum.openwrt.org/t/confusion-regarding-setting-up-ikev2-vpn-service-with-strongswan-using-ipsec-and-swanctl/169587/9 This PR uses `encap` for the option name instead of `force_encapsulation` for consistency with [swanctl.conf](https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#:~:text=encap).

Thanks for considering,
Kevin

[encap]: https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#_connections

2025-03-24 21:32 UTC, Thermi reviewed
Thank you, please rerun CI, LGTM!

2025-03-24 21:33 UTC, Thermi approved these changes

2025-03-24 21:57 UTC, Thermi approved these changes
LGTM

2025-04-07 01:54 UTC, pprindeville requested changes
Needs a `PKG_RELEASE` bump

2025-04-14 02:23 UTC, pprindeville commented
As a single commit...

2025-04-14 16:05 UTC, kevinoid commented
@pprindeville Squashed and bumped to 8.

2025-04-27 18:22 UTC, pprindeville approved these changes
LGTM

2025-04-27 19:35 UTC, merged