strongswan: swanctl: Add support for send_certreq
openwrt/packages pull request #25473
Opened 2024-12-01 19:12 UTC by kevinoid

Maintainer:  @pprindeville @Thermi
Compile tested: None.  Script only change.
Run tested: aarch64, Linksys E8450 mediatek/mt7622, OpenWrt 23.05.5, checked generated `swanctl.conf` and operation

Description:
Support the [send_certreq] connection configuration option to disable offering trusted root CA certificates and reduce the size of the initial IKE packets.

This work is based on a patch by @aleks-mariusz in https://forum.openwrt.org/t/confusion-regarding-setting-up-ikev2-vpn-service-with-strongswan-using-ipsec-and-swanctl/169587/9  This PR uses `send_certreq` for the option name instead of `remote_sendcert` for consistency with [swanctl.conf](https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#:~:text=send_certreq).

Thanks for considering,
Kevin

[send_certreq]: https://docs.strongswan.org/docs/latest/swanctl/swanctlConf.html#_connections

2025-03-24 21:32 UTC, Thermi approved these changes
Thank you, please rerun CI, LGTM!

2025-03-24 21:50 UTC, kevinoid commented
Thanks for taking a look at it @Thermi!

I rebased the PR on the current `master` branch to rerun CI.  If that isn't what you had in mind, my apologies.

2025-03-26 22:05 UTC, Thermi commented
LGTM

2025-04-07 01:53 UTC, pprindeville commented
It will need a `PKG_RELEASE` release bump.

2025-04-07 01:55 UTC, pprindeville requested changes
This will need a `PKG_RELEASE` bump

2025-04-07 02:59 UTC, kevinoid commented
Thanks @pprindeville.  I just added a `PKG_RELEASE` bump to #25472.  If you'd like me to add a second bump to this PR (after merging?) let me know.

2025-04-27 18:21 UTC, pprindeville commented
> Thanks @pprindeville. I just added a `PKG_RELEASE` bump to #25472. If you'd like me to add a second bump to this PR (after merging?) let me know.

Yes, the expectation is that each separate PR increments the `PKG_RELEASE`.

2025-05-01 16:11 UTC, kevinoid commented
Thanks again @pprindeville.  I've added a `PKG_RELEASE` bump and rebased onto the current `master` branch.

2025-05-18 17:33 UTC, pprindeville approved these changes
LTGM

2025-05-18 17:35 UTC, merged