cpupower: add new package
openwrt/packages pull request #25536
Opened 2024-12-11 15:37 UTC by graysky2

Linux kernel userspace tool to examine and to tune power saving related features of the processor

Build system: x86/64
Build-tested: x86/64/AMD Cezanne
Run-tested: x86/64/AMD Cezanne

2024-12-30 20:04 UTC, mhei commented
Seems that the buildbots are not yet happy with the include dirs regarding libpci?

2024-12-30 20:17 UTC, graysky2 commented
@mhei - happy to have any suggestions you may have

2025-01-02 14:21 UTC, mhei commented
Please have a look at https://github.com/mhei/packages/commit/49a2cafbf8a0b7fc606ecb6740fbd6ef67632c39
It works at least with SDK build and "native-complete" build on my local system.

2025-01-03 20:04 UTC, graysky2 commented
Thanks @mhei - I picked/merged it.

2025-01-03 23:01 UTC, mhei commented
Looks like we are getting closer... the new issue with the buildbots can most probably prevented by adding `NLS=false` to the build vars, so that msgfmt is not required anymore. I'm assuming that there is no need on localized messages, though. I'm currently kind of AFK, can only test it later.

2025-01-04 01:27 UTC, graysky2 commented
That's fine, I am out of steam on this one.  Thanks for the collaboration.

2025-01-04 21:55 UTC, mhei commented
I've updated: https://github.com/mhei/packages/commit/7a69c3210ec8a9f49485d8368f641579e9af0e6b

2025-01-05 13:28 UTC, mhei commented
Buildbots are finally happy... nice :+1: I'd kindly ask whether you could rebase on latest master because merging via Github Web UI is blocked at the moment.

2025-01-05 15:44 UTC, graysky2 commented
Done

2025-01-05 19:21 UTC, mhei requested changes

2025-01-05 19:21 UTC, mhei commented on utils/cpupower/Makefile
> +  VERSION:=$(LINUX_VERSION).$(PKG_RELEASE)
I'm so sorry, I overlooked this line. It should be dropped since it is generated automatically from PKG_VERSION and PKG_RELEASE.
Thanks for your contribution and patience.

2025-01-05 19:34 UTC, graysky2 commented on utils/cpupower/Makefile
> +  VERSION:=$(LINUX_VERSION).$(PKG_RELEASE)
Done!

2025-01-06 06:39 UTC, mhei approved these changes

2025-01-06 06:39 UTC, merged

2025-01-06 18:12 UTC, anomeome commented
Is this really supposed to be in a new _utils_ section, rather than under _utilities_

2025-01-06 18:49 UTC, mhei commented
Ha, no... you're right. Thanks for spotting this. It slipped through. Will prepare a follow-up fixup.