prometheus-node-exporter-lua: Add support for `node_filesystem_*` metrics
openwrt/packages pull request #25535
Opened 2024-12-11 12:40 UTC by wjam

Maintainer: @champtar 
Compile tested: Lua only, so not compilable
Run tested: TP-Link Archer C7 v2, OpenWrt v23.05 - I've been running it for a while with no issues and the publicly available Grafana dashboard (https://grafana.com/grafana/dashboards/1860-node-exporter-full/) has been happy with the data

Description:

Add a collector for the various fileystem metrics which matches the node-exporter behaviour. This collector supports the following metrics:

* node_filesystem_size_bytes
* node_filesystem_free_bytes
* node_filesystem_avail_bytes
* node_filesystem_files
* node_filesystem_files_free
* node_filesystem_readonly

2024-12-11 12:46 UTC, wjam commented
Minor comments for @champtar to review:
* I went with `filesytem` rather than `disk` or `disk_use` which was mentioned in #14358 as it matched the node-exporter collector name.
* As commented in the code, `/` is excluded as it's an overlay filesystem which does mean the linked Grafana dashboard has a widget showing `N/A` - which is the same behaviour as node-exporter.

2025-04-20 14:47 UTC, wjam commented
Hi @champtar. Could you review this PR please?

2025-06-23 11:58 UTC, champtar requested changes
@wjam sorry for the delay, you are missing `Signed-off-by` in your commit

2025-07-06 09:15 UTC, wjam commented
> @wjam sorry for the delay, you are missing `Signed-off-by` in your commit

Apologies for missing that. I've updated the commit message and PR comment so it's ready for re-reviewing now.

2025-09-17 10:35 UTC, wjam commented
@champtar Can you re-review this PR please?

2025-11-04 20:34 UTC, wjam commented
@champtar Can you re-review this PR please?

2025-11-04 21:28 UTC, GeorgeSapkin requested changes
You need to bump (i.e. increase by one) the `PKG_RELEASE`, prefix your commit subject with `prometheus-node-exporter-lua:` and start the rest of the subject with lower case.

2025-11-07 16:52 UTC, wjam commented
> You need to bump (i.e. increase by one) the `PKG_RELEASE`, prefix your commit subject with `prometheus-node-exporter-lua:` and start the rest of the subject with lower case.

Changes pushed

2025-11-10 15:53 UTC, GeorgeSapkin requested changes
Please check and resolve the CI build issues.

2026-01-19 20:19 UTC, Zerogiven commented
@wjam any time ot check this? Would be very nice to see it in the openwrt package feed. For now i just copied your file to lua dir but i think disk usage metrics are something what many needs. An alert in grafana for example is a typical use case if disk is near full 🙂 

However, @GeorgeSapkin i looked into one(mips24kc) of the failed builds and it looks like it is/was a problem with some completely different package called "ltq-adsl". So maybe the ci was failing because of some other issue than from the package. Maybe you can restart the action.

last lines from check-compile.txt
```
Updating goal targets....
Considering target file '.compile'.
 File '.compile' does not exist.
  Considering target file '/builder/staging_dir/target-mips_24kc_musl/stamp/.ltq-adsl.danube_installed'.
   File '/builder/staging_dir/target-mips_24kc_musl/stamp/.ltq-adsl.danube_installed' does not exist.
    Considering target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.built'.
     File '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.built' does not exist.
      Considering target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.configured_68b329da9893e34099c7d8ad5cb9c940'.
       File '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.configured_68b329da9893e34099c7d8ad5cb9c940' does not exist.
        Considering target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.prepared_8a86650391487eeb3af8f94b53038c0f_18f1e190c5d53547fed41a3eaa76e9e9'.
         File '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.prepared_8a86650391487eeb3af8f94b53038c0f_18f1e190c5d53547fed41a3eaa76e9e9' does not exist.
          Considering target file '/builder/dl/drv_dsl_cpe_api_danube-3.24.4.4.tar.gz'.
           File '/builder/dl/drv_dsl_cpe_api_danube-3.24.4.4.tar.gz' does not exist.
           Finished prerequisites of target file '/builder/dl/drv_dsl_cpe_api_danube-3.24.4.4.tar.gz'.
          Must remake target '/builder/dl/drv_dsl_cpe_api_danube-3.24.4.4.tar.gz'.
          Target file '/builder/dl/drv_dsl_cpe_api_danube-3.24.4.4.tar.gz' needs to be remade under -q.
         Finished prerequisites of target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.prepared_8a86650391487eeb3af8f94b53038c0f_18f1e190c5d53547fed41a3eaa76e9e9'.
        Giving up on target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.prepared_8a86650391487eeb3af8f94b53038c0f_18f1e190c5d53547fed41a3eaa76e9e9'.
       Finished prerequisites of target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.configured_68b329da9893e34099c7d8ad5cb9c940'.
      Giving up on target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.configured_68b329da9893e34099c7d8ad5cb9c940'.
     Finished prerequisites of target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.built'.
    Giving up on target file '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.built'.
   Finished prerequisites of target file '/builder/staging_dir/target-mips_24kc_musl/stamp/.ltq-adsl.danube_installed'.
  Giving up on target file '/builder/staging_dir/target-mips_24kc_musl/stamp/.ltq-adsl.danube_installed'.
 Finished prerequisites of target file '.compile'.
Giving up on target file '.compile'.
make[2]: Leaving directory '/builder/feeds/base_root/package/kernel/lantiq/ltq-adsl'
```

Last lines compile.txt
```
  CC [M]  /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/pm/drv_dsl_cpe_api_pm_danube.o
  CC [M]  /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/ceoc/drv_dsl_cpe_danube_ceoc.o
  LD [M]  /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.o
  MODPOST /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/Module.symvers
ERROR: modpost: "DSL_BSP_FWDownload" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_SendCMV" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_DriverHandleGet" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_MemoryDebugAccess" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_AdslLedInit" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_EventCBUnregister" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_EventCBRegister" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_DriverHandleDelete" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_KernelIoctls" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
ERROR: modpost: "DSL_BSP_Showtime" [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/drv_dsl_cpe_api.ko] undefined!
make[7]: *** [scripts/Makefile.modpost:145: /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src/Module.symvers] Error 1
make[6]: *** [/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/linux-6.12.57/Makefile:1897: modpost] Error 2
make[5]: *** [Makefile:224: __sub-make] Error 2
make[5]: Leaving directory '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/linux-6.12.57'
make[4]: *** [Makefile:1932: drv_dsl_cpe_api.ko] Error 2
make[4]: Leaving directory '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/src'
make[3]: *** [Makefile:490: all-recursive] Error 1
make[3]: Leaving directory '/builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4'
make[2]: *** [Makefile:89: /builder/build_dir/target-mips_24kc_musl/linux-ath79_tiny/ltq-dsl-danube/drv_dsl_cpe_api-3.24.4.4/.built] Error 2
make[2]: Leaving directory '/builder/feeds/base_root/package/kernel/lantiq/ltq-adsl'
time: package/feeds/base/ltq-adsl/danube/compile#18.29#3.20#30.59
```

2026-01-20 12:45 UTC, GeorgeSapkin commented
CI can't be restarted, probably due to merge conflicts.

2026-05-24 14:43 UTC, champtar commented on utils/prometheus-node-exporter-lua/files/usr/lib/lua/prometheus-collectors/filesystem.lua
> +#!/usr/bin/lua
this file is not executable, going to remove that

2026-05-24 15:02 UTC, merged